### ISSUE TITLE
Backup replication

### ISSUE THREAD

**Issue by klamontagne** [grke/burp#113]
"Backup import" feature

A replica can currently be made with rsync --link-dest without too much trouble, if **hardlinked_archive=1** 

It becomes problematic when backups that were previously hardlinked are transformed into deltas.

One possible implementation would be:

* Write backup data to file, with
  * client name?
  * Base backup number
  * data sent by the client in phase 1 and 2
* Add a server option to import a backup data file.

It would be useful as part of an multi-server or offsite replication scheme.

See also  #112 so the replica server can delete old backups.

**Comment by grke** [comment]
I am not sure that there are any actions to take with this issue.
I am closing it now. If there are actions needed, a new issue can be created with a concise summary.
