### ISSUE TITLE
unable to start the server on debian 

### ISSUE THREAD

**Issue by logg-sar** [grke/burp#127]
hi there

i´ve downloaded and installed burp (version 1.3.10) but i cant start the server.
when i´m entering 
server:/etc/burp$ sudo burp -c /etc/burp/burp-server.conf -F

2012-10-13 16:02:55: burp[3970] unable to bind socket on port 4972: Cannot assign requested address
2012-10-13 16:02:55: burp[3970] unable to bind listening socket on port 4972

i´ve of course already tried different ports, but it doesnt work.

is it my fault?

thx

**Comment by C-Otto** [comment]
I have the same issue. I disabled IPv6 on purpose, and according to strace this seems to be the cause:

```bind(5, {sa_family=AF_INET6, sin6_port=htons(4972), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)```

Is there a way to use burp in Debian without IPv6 and without recompiling manually?

**Comment by grke** [comment]
Hello,

No, if your server is on 1.x.x.
Yes, if your server is on 2.0.8 or newer.

**Comment by C-Otto** [comment]
Debian Stable uses 1.3.48, so no then.
https://packages.debian.org/jessie/burp
