### ISSUE TITLE
Resume partially transferred files

### ISSUE THREAD

**Issue by grke** [grke/burp#133]
Currently, burp resumes at file level granularity.

If it is interrupted in the middle of a large file, it will have to start the large file again.

Add the ability to combine partial transfers together to generate a combined librsync signature
that would make the client send a suitable librsync delta.

**Comment by unode** [comment]
Hi Graham (@grke),

Apologies for the 8 year old necrobump but I can't seem to find specific documentation on this feature.
I found [this post in the user mailing list](https://sourceforge.net/p/burp/mailman/message/33524327/) dating back to 2015. Do I understand correctly that this is currently not possible with protocol 0/1? (server: 2.2.18/2.3.36 , client: 2.2.18)

I'm precisely trying to backup a large file over a slow connection and interruptions are causing it to always restart (according to `pv -d <client PID>`).
The server is using:
```
protocol = 0
hardlinked_archive = 0
working_dir_recovery_method = resume
```
and `burp -c /var/lib/burp/burp.conf -t | grep 'librsync\|hardlinked\|protocol\|working_dir'` reports:
```
                        protocol: 0
              hardlinked_archive: 0
     working_dir_recovery_method: resume
                        librsync: 1
               librsync_max_size: 0
```

**Comment by grke** [comment]
Hello,
The feature was implemented, but it worked so badly that everybody was better off with it being removed.
