### ISSUE TITLE
Do not use symlinks on the backup directory if the filesystem does not support them

### ISSUE THREAD

**Issue by Ernest0x** [grke/burp#178]
Burp is using symlinks on the server's backup directory in order to keep track of the status of its tasks. E.g. it creates a 'working' symlink, a 'finishing' symlink and a 'current' symlink. However, this approach would not work in filesystems that do not support symlinks.

Consider the scenario in which the server mounts locally a remote CIFS filesystem in order to store backups to a remote site. This is quite common, especially in environments with windows systems and network drives that export their shares only through CIFS/SMB. Unfortunately, CIFS does not support symlinks.

**Comment by grke** [comment]
Had a try at this today, and it was more trouble than I once thought it would be.
For example, a lot of code tries to access files in the working directory through the 'working' symlink.
All that code would need to be rewritten to extract the path from the symlink, and then access the actual directory directly.
I think that this is more trouble than it is worth, so I will not be doing it (unless somebody wants to offer me some cash reward).
So, I am closing.
