### ISSUE TITLE
 Maybe look at the timer script regularly

### ISSUE THREAD

**Issue by basd82** [grke/burp#18]
Maybe look at the timer script regularly. If the time is now out of the  defined range, interrupt the backup in such a way that it will pick up from where it left off the next time round.

**Comment by grke** [comment]
From the mailing list:

I was wondering would be possible to pause initial large backup.

For example EX1 server backup is about 2 TB which would take two long to
Initially backup over 10Mbps link to server EX2.
Would be possible to pause or how to do it backup and then continue when
backup is
allowed to run say don't work from 8:00 AM - 17:00 PM.

Also I pretty sure this option does not exist but would be possible to
implement time base rate limiting.
I am using for rsync or rdiff this utility  which is great something like
that in burp would be awesome.

https://code.google.com/p/bwlimit/

**Comment by grke** [comment]
Feature implemented in git master, for the next release.
