### ISSUE TITLE
2 Servers backing up to each other, both server and both client

### ISSUE THREAD

**Issue by megapearl** [grke/burp#184]
What am I doing wrong? Having the error on both servers (both FreeBSD 9.2)

Backup starts but gives error after couple of minutes:

Crontab mail:
2013-12-31 20:03:00: burp[50461] before client
2013-12-31 20:03:00: burp[50461] begin client
2013-12-31 20:03:01: burp[50461] auth ok
2013-12-31 20:03:01: burp[50461] Server version: 1.4.10
2013-12-31 20:03:01: burp[50461] nocsr ok
2013-12-31 20:03:01: burp[50461] Client uses TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384
2013-12-31 20:03:02: burp[50461] Compression level: 9
2013-12-31 20:03:02: burp[50461] do backup client
2013-12-31 20:03:02: burp[50461] Phase 1 begin (file system scan)

ddffffffffdddfddffdddffffffffdddffdffffdddffffdffdfffddfffdfdfff 64
fffdfffffffffffffffffffffffffffffffffffffffffffffffffdffffffffff 128
fffffffffffffffffffffffffffffffffffffffffffffffdfffdffdfdffffffd 192
fddffffffffffffffffdffffffffffffffffdfdfffdffdffffffffffffffffdf 256
fffffffffddfdfffffffffffffffffffffffddffffffffffffdffffddffffdff 320
ffffffffffdffffffffffffdffffffffffffdfffffffffdffffffffdffffffff 384
ffffffffffffffffffffffffffddddddddfdddddddddddddddfdddfddddddddd 448
ddddddddddddddddfdddddddddfdddddfdddddddddddddddddddfdfddfdddfdd 512
dddddddddddfddddddddfdddfdfdddddddddddddddddddddddfddddddddddddd 576
ddfdddddddddddddddddfddddfddddfdddddddddddfdddfdfddddddddddddddd 640
ddddddfdddddfddddddfddddddddddddfddddddddddddddddddddddddfdddfdd 704
ddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddd 768
dddddddddddddddfdddddddfddddddddddddddddddddfdfdddddddddfdddddfd 832
ddddddddddddddddddddddddddfddfdddddddddfdfdddddfdddddddddddddddd 896
dddfdddddfddddddddddddddddddddddfddddddddddddfdddddfdddfdddddddf 960
dddddddddddddddddddddddddddfddddddddddddddddddddddddddfdddddfdfd 1024
ddddddfdddddddddfddddfdddfdddddddddddddddfdddddddddfdfdddddddddd 1088
ddddfddddddddfddddfdddddfdddddddddddfddfdddddddddddfddddfddddddd 1152
ddddddddddddddfdddddfdddddddddddddddddddddddddddddddfddddfdddddd 1216
ddfdddddddddddddddddddddddddfdddddfddddfddddfdddddfdddfddddddddd 1280
fdddddddddddddddddfddddddddddfdddddddddddddddddfdfddddddfdfdddfd 1344
ddddfdddfdddddddfdddddfdddfddddfdfddddddddddddddddddddddddddddfd 1408
ddddddddddddddddfddddddfddddddfdddddddfdddddddddddddddfddfddfddd 1472
ddddfddddddddddddddddddfdddfdddfdddfdddfddfdffffffffffffffffffff 1536
ffffffdfddffffffffffffffffffffffffffffffffdfffffffffffffffffffff 1600
fffffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffff 1664
fffdffffffdfffffffffffffffdffffdffdfffffffffffffffffffffffffffff 1728
fffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1792
ffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffff 1856
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1920
fffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1984
fffffffffffffffffffffffffffffffffffffffffffffffdffffffffffffffff 2048
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 2112
ffffffffffffffffffffffffffffffffdffffffffffdffffffffffffffffffff 2176
ffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffffff 2240
fffffffffffffffffffffffffffffffffffffffffffffffffffffdffffffffff 2304
fffffffffffffffffffdffffffffffdfffffffffffffffffffffffffffffffff 2368
ffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffffff 2432
fffffffdfffffffffffffffffffffffffffffdffffffffffffffffffffffffff 2496
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 2560
ffffffffffffffddddddffffffffffffffffffffffffffffffffffffffffdfff 2624
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 2688
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 2752
ffffffffffffffffffdffffffffffffffffffffffffffffffdffffffffffffff 2816
ffffffffffffffffffffffffffffffffffdffdffffdffffffffdffffffffffff 2880
dffffffffffffdfffffffffffffffffdffffffdfffffdfffffffffffffffffff 2944
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3008
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3072
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3136
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3200
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3264
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3328
fdffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffff 3392
fffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3456
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3520
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3584
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3648
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3712
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3776
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3840
dffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffffff 3904
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 3968
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 4032
ffffffffffffffffffffffffffffffffdfffffffffffffffffffffffffffffff 4096
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 4160
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 4224
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 4288
ffdffffffffffffffffdffffffffffffffffffffffffffffffffffffffffffff 4352
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffff 4416
ffffffffffffdffdffffffddfffffffddfffffffffffffffffffffffffffffff 4480
ffffffffffffffffffffffffffffffddffffffffffffffffffffffffffffffdf 4544
fffffffffffffffffffffffffffffdfffffffffffdfffffffdfffdffffffffff 4608
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 4672
fffffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffff 4736
fffffffffffffffffffffffffffffffffffffffffdfffffffffdffffffffffff 4800
ffffffffffdffdffffdfffffffdfffffffffffffffffffffffffffffffffffff 4864
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 4928
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdffff 4992
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd 5056
ffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffff 5120
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 5184
fffffffffffffffffffffffffffffffffffffffffffffffffffffdffffffffdf 5248
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 5312
ffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffffdf 5376
ffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 5440
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 5504
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 5568
ffffffffdffffffffffffffffffffffffffffffffffffdffffffffdfffffffff 5632
fffffffffffffdffffdfffffffffffffffffffffffffffffffffffffffffffff 5696
ffffffffffffffffffdfffffffffffffffffffffffffffffffffdfffffffffff 5760
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 5824
fffffffffffffffffffffffffffffffffffffffdffffffffffffffffffffffff 5888
fffffffffffffffffffffffffffffffffdfffffffffffffffffffffffffdfffd 5952
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 6016
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 6080
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 6144
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 6208
ffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffdf 6272
ffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffffffdf 6336
fffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffffff 6400
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 6464
fffffffffffffffffffffffffffffffffffffffffffffffffdffffffffffffff 6528
dffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffffff 6592
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 6656
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 6720
fffffffffffffffffffffffffffffffffffffffffdffffdfffffffffffffffff 6784
ffffdffffffffffffffffffffffffffffffffffffffffffdffdfffffdfffffff 6848
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffddffffdf 6912
ffffffffffffffffffffffffffffffffddffdfffffffffffffffffffffffffff 6976
ffffffffffffdffffffffffffffffffffdffffffffffffffffffffffffffffff 7040
fffffffffffffffffffffffffffffffffffffffdfffffffffffddfffffffdfff 7104
fddfffffffffffffffffffdfffffffffffffffffdfffffffffffffffffffffff 7168
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 7232
ffffffffffffffffffffffffdfffffdfffffffffffffffdfffffffffffffffff 7296
ffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffffff 7360
fffffffffffffffffffffffffffffffffffffdffffffffffffffffffffffffff 7424
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffff 7488
dffdfffffffffffffffffffffffffffffffdffffffffffffffffdfffffffffff 7552
fffffffffffffffffffdfffffffdffffffffffffffffffffffdffffffdffffff 7616
ffffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 7680
fffffffffffffffffffffffffffffffffffffffdffffffffffffffffffffffff 7744
ffffffffffffffffffffffffdfffffffffffffffffdfffffffffffffffffffff 7808
fffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 7872
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 7936
ffffffffffffffffffffffffffffffffffffffffffffffffffffdffffffffdff 8000
ffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffffffff 8064
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 8128
fffffffffffffffffffffffffffffffffffffffffffdfffffffffffffdffffff 8192
fffffffffffffffffffffffffffffffffffdffffffffffffffffffffffffffff 8256
ffffffffffffffffffffffffffdfffffffffffffffffffffffffffffffffffff 8320
ffffffffffffffffffffffffffffffffffffffffffffffffdfffffffffffffff 8384
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 8448
ffffffffffffffffffffffffffffffffffffffffffffffffdfffffffffffffff 8512
fffffffffffdfffffffffffffffffffffffffffffffffffdfffffffffffdffff 8576
fffffffffffffffffffffffffffffdffffffffffffffffdffffffffffffffffd 8640
ffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffffff 8704
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 8768
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 8832
ffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffffff 8896
fffffdffffffffffffffffffffdfffffffffffffffffffffffffffffffffffff 8960
fffffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9024
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9088
fffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffffff 9152
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9216
ffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffdfffff 9280
ffdffffffffffffffdffffffffffffffffffffffffffffffffffdfffffffffff 9344
ffffffffffffffffffffffffffffdfffffdfffdfffffffffffffffffffffffff 9408
fffffffffffffffffffffffffffffffffffffffffffdffffffffffffffffffff 9472
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9536
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9600
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9664
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9728
ffffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffff 9792
fffffffffffffffffffdffffffdfffffffdffffffffffffffffdffffffffffff 9856
ffffffffffffffffffffffffffdfffffffffffffffffffffffffffffffffffff 9920
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 9984
fffffffffffffffffffffffffffffffffffffffffffffffffffdfffdffffffff 10048
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 10112
dfffffffffffffffffffdffffffffffffdffffffffffffffffffffffffffffff 10176
fffffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffff 10240
fffffffffffffffffffffffffffdfffffffffffffffffffffffffffffdffffff 10304
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfff 10368
ffffffffffffffffffffffffffffffffffffffffdffffffffffffdffffffffff 10432
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffdffffff 10496
ffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffff 10560
ffffffffffffdffffffffffffffffdffffffffffffffffffffffffffffffffff 10624
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffff 10688
fffffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffff 10752
fffffffffffffffffffffffffffffffffffffffffffffffffffdffffffffffff 10816
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 10880
fffffffffffffffffffffffffffffffdffffffffffffffffffffffffffffffff 10944
fdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 11008
fffffffffffffffffffffffffffffffffffffffffffdffffffffffffffffffff 11072
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 11136
fffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffffff 11200
ffffffffdfffffffffffffffffffffffffffffffffffffffffffffffffffffff 11264
fffffdffffffffffffffffffffffffffffffffffffdffffffffffdffffffffff 11328
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 11392
ffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffffffff 11456
fffffffffffffffffffffffffffffffffffffffffffffffffffffdffffffffff 11520
fffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffffff 11584
ffffffffffffffffffffffffffffffffffddffffffffffffffffffffffffffff 11648
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 11712
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 11776
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 11840
ffffffffffffffffffffffffffffffffffffffffffffffffffdfffdfffffffff 11904
ffffffffdffffffffffddffffdffdffffdffffffffffffdffffffffdfffffdff 11968
fffdfffffdfffffdfffffdffffffffdfffffffffffffffffffffffffffffffff 12032
ffffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffdf 12096
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 12160
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 12224
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 12288
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 12352
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 12416
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 12480
fffffffffffffffffffddffffffffffffdfddffdffffffffffffffffffffffff 12544
ffffffffffffffffffffffdfffffffffffffffdfdfdffdffdfdfffffffdfdffd 12608
ffffffffffffffffffffffffffffffffffffffdfffffffffffdfffffffffffff 12672
ffffffffffffffffffffffffffffffffdfdffffffffffffffffdffdffddfdfff 12736
fffdfdffffffffffffffffffdfffdffffffffffffffffffffffffffffffffdff 12800
fdfffffddfffdfffddffffffffffffffffdffddffffdffdfffffffffdfffffff 12864
ffffffffffffffffffffffffffffffffdffffffffdfddfffffffffffffffffff 12928
fffffffffffdfffffffffffdffffffffffffffffffffffffffffffffffffffdf 12992
fffffffffffffffffffffffffffdffffffldffffffffffffffffffffffffffff 13056
ffffffffffffffffffffffffffffdfffffffffffffffffffffffffffffffffff 13120
fffffffddffffffddfffffffffffffffffffffffffffffffffffffffffffffff 13184
ffffffffffffffdffffffffddffffffffffffffffffffffffffffffdffffffff 13248
ffffffffffffffffffffffdfffffffffffdffffffffffffffffffdffffffffff 13312
fffffffffffffffffffffffffffdfffffffffffdffffffdfffdfffffffffffff 13376
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 13440
ffffffffffdfffffffffffffffffffffffffffffffffffffffffffffffffffff 13504
ffffffffffffffffffffffffffffffffffffdfffffffffffffffffffffffffff 13568
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 13632
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 13696
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 13760
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 13824
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 13888
ffffffffffffffffffffffffffffdfffffffffffffffffffffffffffffffffff 13952
fdfffffffffffffffffffffffffffffffffffffffffffffdffffffffffffffff 14016
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14080
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14144
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14208
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14272
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14336
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14400
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14464
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14528
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14592
fdfffdfdffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14656
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14720
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14784
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14848
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14912
fffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 14976
ddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15040
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15104
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15168
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15232
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15296
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15360
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15424
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 15488
ffffffffffdfffffffffffffffffffffffffffffffffffffffffffffffffffff 15552
fffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffffff 15616
ffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffffff 15680
fffffffffffffffffffffffffffffffffdffffffffffffffffffffffffffffff 15744
ffffffffffffffffffffffffffffffdfffffffffffffffffffffffffffffffff 15808
ffffffffffffffffffffffdfffffffffffffffffffffffffffffffffffffffff 15872
fffffffffffffffffffffffffffffffffffffffdfffffffffffddfffffffffff 15936
fffffddffdfffdfffdfffdfffdfffffffffffffffffffdffdfffffffdfdfffff 16000
fdfffffffffffffffffffffffffffffffffffffdfffffffffffffffdffffffff 16064
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 16128
ffffffffffffffffffffffffffffdffffffffffffdffdfffffffffffffffffff 16192
ffffffffffffffffffffffffffffffffffffffffffffdffffffffdffffffffff 16256
ffffffffffffffffdfffdffffffffdffffddfdffffffffffffffffffffffffff 16320
fffffffdddddfdfdfdfdfdffffffffddfffffffffffffffffffffffddffffdff 16384
dfffffdffffffdffffffff 16406

2013-12-31 20:03:08: burp[50461] Phase 1 end (file system scan)
2013-12-31 20:03:08: burp[50461] Phase 2 begin (send file data)

ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 64
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 128
ffffffffffffffffffffffSSL write problem2013-12-31 20:12:48: burp[50461] Got SSL_ERROR_SYSCALL in write, errno=1 (Operation not permitted)
2013-12-31 20:12:48: burp[50461] write returned: -1
2013-12-31 20:12:48: burp[50461] error in do_write
 150

---

Start time: 2013-12-31 20:03:00
  End time: 2013-12-31 20:12:48
Time taken: 09:48
                         New   Changed Unchanged   Deleted     Total |  Scanned
                   ------------------------------------------------------------
            Files:       150         0         0         0       150 |    14999
      Directories:         0         0         0         0         0 |     1406
       Soft links:         0         0         0         0         0 |        1
      Grand total:       150         0         0         0       150 |    16406
                   ------------------------------------------------------------

```
         Warnings:             0

  Bytes estimated:   80393227131 (74.87 GB)
  Bytes in backup:     630807075 (601.58 MB)
   Bytes received:             0
       Bytes sent:     630807075 (601.58 MB)
```

---

2013-12-31 20:12:48: burp[50461] Error in phase 2
2013-12-31 20:12:48: burp[50461] Phase 2 end (send file data)
2013-12-31 20:12:48: burp[50461] error in backup
2013-12-31 20:12:48: burp[50461] after client

Burp Failure Mail:
0000001 2013-12-31 20:03:02

/mnt/backup/Backup/Burp/*redacted*/working/log:

2013-12-31 20:03:02: burp[86467] Client version: 1.4.10
2013-12-31 20:03:02: burp[86467] Begin phase1 (file system scan)
2013-12-31 20:03:08: burp[86467] End phase1 (file system scan)
2013-12-31 20:03:08: burp[86467] Begin phase2 (receive file data)
2013-12-31 20:12:49: burp[86467] Got SSL_ERROR_SYSCALL in read, errno=54 (Connection reset by peer)
2013-12-31 20:12:49: burp[86467] SSL read problem
2013-12-31 20:12:49: burp[86467] error in async_rw
2013-12-31 20:12:49: burp[86467] End phase2 (receive file data)
2013-12-31 20:12:49: burp[86467] error in backup phase 2

**Comment by BobRyanConsulting** [comment]
FreeBSD has the coreutils port which includes /usr/local/bin/gdate which we're using with this script successfully. It may be simpler to add that as a dependency and check for its presence in the script.

**Comment by grke** [comment]
Thanks for your idea, I will add your comment to the issue that I mentioned in my comment above, which is still open:
https://github.com/grke/burp/issues/209
