### ISSUE TITLE
Internalise the timer_script

### ISSUE THREAD

**Issue by grke** [grke/burp#209]
/etc/burp/timer_script has trouble on systems with strange 'date' commands. See:
https://github.com/grke/burp/issues/184
Maybe write a custom 'date' command in C that outputs what timer_script expects.

**Comment by grke** [comment]
Comment from BobRyanConsulting:
"FreeBSD has the coreutils port which includes /usr/local/bin/gdate which we're using with this script successfully. It may be simpler to add that as a dependency and check for its presence in the script."

**Comment by grke** [comment]
I think the best solution is still for burp to do it internally, and keep the external script as an option.

**Comment by computerfr33k** [comment]
I just recently installed on FreeBSD and had to change all of the date commands to use gdate because otherwise the date command would fail and would then think it has to do a backup everytime it checks. The current FreeBSD checks in the script did not work out of the box for me. (version 1.4.40)

**Comment by zeroidle** [comment]
```
8c8
< #current="$1" ; shift --- > current=”$1″ ; shift
80c81
< if ! secs=$(LANG=C date -j -f "%Y-%m-%d %H:%M:%S" "$ts" +%s) --- > if ! secs=$(LANG=C date +%s -d “$ts”)
82c83
< || ! nowsecs=$(LANG=C date +%s) --- > || ! nowsecs=$(LANG=C date +%s -d “$now”)
89c90
< if ! min_time=$(LANG=C date -j -f "%s" "$min_timesecs" +"%Y-%m-%d %H:%M:%S") --- > if ! min_time=$(LANG=C date -d @$min_timesecs +”%Y-%m-%d %H:%M:%S”)
```

**Comment by grke** [comment]
In master, there is now an internalised version of the timer script.
You get it by not defining the timer_script option.
