### ISSUE TITLE
Choose case sensitivity on list/verify/restore.

### ISSUE THREAD

**Issue by grke** [grke/burp#211]
There is currently no way to choose case sensitivity on list/verify/restore.
It should probably be automatically insensitive if the client is Windows, but there should
probably be a way to force it.

Should be able to choose for the 'regex' option in server initiated restores too.

Possibly, the same should apply to regexes in includes/excludes.

**Comment by spmetas** [comment]
Hello,

yes, I hit exactly the same problem. Users name files like CAPITAL, small, Mixed and likeCamel. Its impossible to guess, and regular expression like /.*camel.*/i does not work.

**Comment by grke** [comment]
Switching to pcre would probably solve this.

**Comment by grke** [comment]
I mean, me making changes to burp so that it requires pcre would solve this.

**Comment by spmetas** [comment]
Probably case sensitivity is quite simple task for switching to completely new way of doing this. 
One simple solution is to parse "/regex/i" syntax, another is just to add cmdline switch.

**Comment by grke** [comment]
No, it makes more sense just to switch to pcre and let pcre take care of it.

**Comment by grke** [comment]
I don't know what I was talking about with my last comment.
I've now implemented case-insensitive regex searches for list/backup/verify, in git master ready for the next release.
Use '-R' instead of '-r'.
