### ISSUE TITLE
Add localisation/gettext specifically to work around the Polish Windows XP   "schtasks.exe Co_minutÄ" problem.

### ISSUE THREAD

**Issue by basd82** [grke/burp#23]
Add localisation/gettext specifically to work around the Polish Windows XP  "schtasks.exe Co_minutÄ" problem.

**Comment by marcin-github** [comment]
It should be:
`burp-installer.exe /minutetext=Co_minutę`

**Comment by grke** [comment]
Don't think I am ever going to do this. The work around should be enough.
