### ISSUE TITLE
Backup options in server vs backup options in client

### ISSUE THREAD

**Issue by deajan** [grke/burp#230]
Hello,

I've freshly installed a new burp server v1.4.22.
I've made the following config file /etc/burp/clientconfdir/std_settings

```
exclude_regex=/\.cache/
exclude_regex = "[A-Z]:/Users/[^/]+/AppData/Local/Temp"
exclude_regex = "[A-Z]:/Documents and Settings/[^/]+/Cookies"
exclude_regex = "[A-Z]:/Documents and Settings/[^/]+/Recent"
exclude_regex = "[A-Z]:/Documents and Settings/[^/]+/Local Settings/Temp"
exclude_regex = "[A-Z]:/RECYCLER"
# swap file (Windows XP, 7, 8)
exclude_regex = "[A-Z]:/pagefile.sys"
# swap file?? (Windows 8)
exclude_regex = "[A-Z]:/swapfile.sys"
split_vss=1
# strip_vss=0
```

and have the clients conf file as follows:

```
password = password

# More configuration files can be read, using syntax like the following
# (without the leading '# ').
. std_settings
```

On my clients, i have the following in burp.conf (windows environment).

```
split_vss = 0
```

When i make a backup, VSS information is not splitted from file.
My server is configured to split_vss = 1, my client is configured to split_vss = 0.
The client wins. Is this the expected behavior ?

Regards,
Ozy.

**Comment by deajan** [comment]
Sorry to bother you again on this, but i definitly think there is some space for improvement on how client configuration options could get overrided by server configs.

On my actual setup, every client has include lines in its config file, and the server doesn't have an include line in the clients server config file because i want to allow my clients to backup whatever they need, and being able to change this.

Now my problem comes from the fact that having no include statement in the server config file, all other options from the server aren't enforced.
I have some clients that just drop some 4.7gb films on folders are included in burp backup, and i'd like to use "max_file_size=100Mb" on server side to enforce this rule for every client. Enforcing "split_vss=1" would also be great.
Now as my server config doesn't have an include directive in the client config files, these options are overriden by client config.

Would it be possible to make global config file for the server with options overriding all client options ?

Regards,
Ozy.

**Comment by grke** [comment]
Hello,
This is tricky, because you need to be clear on who's rules win.
At the moment, it is clear and simple - either the server sets all the rules, or the client sets all the rules, and the server decides which.

In burp-1.4.28, there is a soft/hard quota feature that might help you a bit for now with the sizes problem.

Otherwise, I need to think more about how what you would like to achieve can be possible.
I can't see me implementing anything any time soon, because I have a lot of other stuff to
implement/fix first.

**Comment by deajan** [comment]
There's no hurry, maybe this might make it into a burp 2.x release :)
I'm just thinking of a way the client and the server both can setup rules, and the server wins when both sides set the same rule differently.
