### ISSUE TITLE
Bad restore regexes on the server don't give a suitable message on the client side.

### ISSUE THREAD

**Issue by deajan** [grke/burp#231]
Hello,

I've tried playing a bit with burp restore from server with the following "restore" file
```
backup=5
regex=*
```

I'm getting this error message on the client.
Error when reading counters from server.

I'm pretty sure my regex is bad, i just want to restore all files without having to specify a full path via an include statement, but i think burp could give a better error message as i've seen this in some thread where burp gets a SEGFAULT because of this.

Just wanted to let you know :)

**Comment by grke** [comment]
There is now a change in master that lets bad restore regexes get logged on the client side.
