### ISSUE TITLE
Timestamps of symbolic links are not restored

### ISSUE THREAD

**Issue by t-brink** [grke/burp#254]
When restoring a backup on Linux, the modification time of symlinks is the date of the restore, not the original modification time.

Looking at the source code (src/attribs.c, I hope this is the correct file), it seems that burp correctly uses lchown() to set the owner/group of symlinks. It doesn't set the permissions but I guess that is impossible and useless. What it doesn't do, is to use the correct system call to change the time. It seems to use utime() also for symlinks which acts on the symlink target. It should instead use either lutimes(), which is a non-standard system call available on Linux and (some?) BSDs; or utimensat() with the AT_SYMLINK_NOFOLLOW flag. The latter syscall is POSIX 2008 but I don't know if it is implemented on non-Linux systems.

The best solution would be to test if the syscall is available when compiling. If it is available, use it, else do not change the time on symlinks.

**Comment by grke** [comment]
OK, thanks for your analysis, I will try to fix it in burp-1.4.x soon.

**Comment by grke** [comment]
Have now added lutimes in burp-1.4.29. Will leave this open until I have also done it in burp-2.

**Comment by grke** [comment]
Done in burp-2.
I will hopefully do a release of the next burp-1.4.x in a few hours.
