### ISSUE TITLE
Stop during Phase 2 = Restart all the backup

### ISSUE THREAD

**Issue by iagit** [grke/burp#255]
Hello,

I try to make the first backup of my windows server to my burp server through my WAN Connection. 
My windows server stopped in the phase 2 then i launch a new backup which start at the beginning.

If i connect to the burp server, in /var/spool/burp/ all the data which were copied are delete.

Is there a solution if server crash during the phase 2 to resume the backup at the point where she has stopped?

Is there a command to end the backup? For stop backup properly (phase3, phase4).
(or to stop the runing backup at a time)

Best regards ,

Etienne

**Comment by grke** [comment]
Hello,

Look at the option 'working_dir_recovery_method' option.

If you want to interrupt a backup, you need to either kill the client process or the relevant server child process.

**Comment by iagit** [comment]
Ok thank you. I did not see this option ! Sorry :)
