### ISSUE TITLE
Make should install into /usr/local

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#266]
I have noticed that 1.4.32 by default installs to "/usr/sbin" and would therefore overwrite binaries that have been installed by a distribution´s package.

Other programs I have seen, install to "/usr/local" by default and make it possible to specify other locations via the configure script.

**Comment by grke** [comment]
Yes, I agree that this is a problem that should be fixed.

**Comment by grke** [comment]
From tokudan in https://github.com/grke/burp/issues/336:

While working on a package for NixOS I noticed that burp partially ignores a prefix setting:
Makefile.in contains
./Makefile.in: $(MKDIR) $(DESTDIR)/var/run
./Makefile.in: $(MKDIR) $(DESTDIR)/var/spool/burp

This ignores a possible prefix set through configure:
--localstatedir=DIR modifiable single-machine data [PREFIX/var]

**Comment by tokudan** [comment]
These lines should fix the usage of /var:
       $(MKDIR) $(DESTDIR)$(localstatedir)/run
       $(MKDIR) $(DESTDIR)$(localstatedir)/spool/burp

**Comment by rubenk** [comment]
I'll look into this!

**Comment by grke** [comment]
Thanks, this looks done now.
