### ISSUE TITLE
Config: Source wildcarded files from a directory

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#267]
It would be nice to be able to source a bunch of files with ". /etc/burp/conf.d/*.conf" in burp.conf instead of specifying a single file.

This would make it easier using Puppet (or other management tools) for multiple servers as you could just drop server-specific files into "conf.d" without the need to additionally adapting burp.conf on each server to include a file specific for that server.

**Comment by grke** [comment]
Done for the next 2.0.x release.

**Comment by larsen0815** [comment]
Thx!

**Comment by grke** [comment]
No probem. If you want to try it in advance, to make sure it works, you can checkout branch 2.0.15.

**Comment by larsen0815** [comment]
Works as expected. I included "/etc/burp/conf.d/*.conf".

**Comment by grke** [comment]
Cool, thanks for testing.
