### ISSUE TITLE
Directory in source archive should contain version number

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#268]
At the moment, the archive "burp-2.0.14.tar.bz2" extracts to a directory "burp".

Most open-source projects I know provide a source file that contains a directory with the version number in it´s name (e.g. ProFTPd, Apache httpd) instead of just the name.

This has the benefit of being able to extract multiple versions into the same parent directory (useful if you want to test different versions at the same time). Also, checkinstall doesn´t like it when you run it from within a directory that has no version number in it´s name.

Of course, it is possible to manually rename the extracted directory afterwards but if it doesn´t break anything else, this could be made more user-friendly.

**Comment by grke** [comment]
OK, I will change my release procedure to do this. I will close this once I have done so.

**Comment by larsen0815** [comment]
thx!

**Comment by grke** [comment]
Done. The next release will use a versioned directory name.
