### ISSUE TITLE
List latest backup without having to specify the backup number

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#269]
It would be useful if you could "latest" as a literal when showing the contents of a backup:

    "burp -a l -b latest"

see http://sourceforge.net/p/burp/mailman/burp-users/thread/81741bcd695c7241f4710858fa087885.squirrel%40grke.net/#msg33590763

**Comment by grke** [comment]
OK. But, I think "burp -a l -b current" would be more consistent within burp.

**Comment by larsen0815** [comment]
Sure, you´re the author =)

**Comment by grke** [comment]
Done for the next release of burp2, It only checks the first character, so you can do:
burp -a l -b current
or
burp -a l -b c
or
burp -a L -b c

**Comment by larsen0815** [comment]
Tested, works fine. Thx!
