### ISSUE TITLE
Distinguish between empty and missing directories

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#270]
I want to know whether a directory is empty or isn't contained in a backup, but the output for both kinds is the same:

    # burp -a l -b 3 -d /var/lib/psa/dumps/backup/archives
    Backup: 0000003 2015-03-16 16:10:28
    Listing directory: /var/lib/psa/dumps/backup/archives
     
    2015-03-16 17:20:46: burp[6164] List finished ok
 
 
    # burp -a l -b 3 -d /var/lib/psa/dumps/backup/thisdoesnotexist
    Backup: 0000003 2015-03-16 16:10:28
    Listing directory: /var/lib/psa/dumps/backup/thisdoesnotexist
     
    2015-03-16 17:22:02: burp[6292] List finished ok

I think it should report if the path could not be found.

**Comment by grke** [comment]
Done for next 2.0.x.

**Comment by larsen0815** [comment]
Tested, works fine. Thx.
