### ISSUE TITLE
Burp downloads from sourceforge regularly fail

### ISSUE THREAD

**Issue by dev-arch** [grke/burp#271]
Burp downloads from sourceforge regularly fail for both Windows and Linux. Selecting another mirror worked.

**Comment by grke** [comment]
Hello,
I can't do anything about the infrastructure of sourceforge, or its transient issues, other than using a different service than sourceforge.

**Comment by dev-arch** [comment]
I understand. I just wanted to let you know that I had recurring issues over a longer period of time. Maybe opening an issue wasn't the most suitable way to do that. Thanks anyway!
