### ISSUE TITLE
Burp 1.3.48 doesn't work with librsync-1.0.0

### ISSUE THREAD

**Issue by dev-arch** [grke/burp#272]
Got librsync-1.0.0-1 on Arch this morning and with that library burp doesn't work:
burp: error while loading shared libraries: librsync.so.1: cannot open shared object file: No such file or directory
Downgrading does the trick for now.

**Comment by grke** [comment]
Hello,

If you upgrade the major version of any C library, you will need to relink any software that depends upon that library. So, in your case, anything that is linked to librsync.so.0 would have been broken, not just burp. Recompiling the burp package whilst librsync.so.1 was installed would have fixed it.

This is an issue with package management on your distribution, not a burp issue.

**Comment by dev-arch** [comment]
I had no idea. :-) Thanks.

**Comment by grke** [comment]
No problem, and good luck.
