### ISSUE TITLE
Warnings logged when running automysqlbackup through burp

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#281]
As reported on the mailing list: When I run automysqlbackup as a pre-script, burp shows the output of it with a lot of "WARNING", see http://pastebin.com/LpJ0CKBq

burp 2.0.17

**Comment by larsen0815** [comment]
Still happens with 2.0.18

To reproduce configure burp with:
backup_script_pre=/usr/local/bin/automysqlbackup
backup_script_reserved_args=0

In /etc/automysqlbackup/automysqlbackup.conf configure your MySQL user and password and set:
CONFIG_db_names="mysql"

Then run "burp -a b".

**Comment by grke** [comment]
For the next burp-2 release, I have made it possible for peers to send information messages separately to warning messages to each other. This means that I can log stdout as a message and stderr as a warning, instead of everything as a warning.
