### ISSUE TITLE
Make the monitor server answering in all cases

### ISSUE THREAD

**Issue by ziirish** [grke/burp#284]
When using burp2 in monitor mode, when you enter something wrong, the server just ignores you.

It would be nice to have an output in all cases like a warning or something so that we know the server got our query.

A wrong query is for instance something like:

```
c:client_that_does_not_exist
```

**Comment by grke** [comment]
Done in 2.0.19.
The response will look like this:
{
"warn": "some message"
}

**Comment by ziirish** [comment]
Thanks, works like a charm. I implemented it Burp-UI side too.
