### ISSUE TITLE
include vs. cross_filesystem

### ISSUE THREAD

**Issue by C-Otto** [grke/burp#290]
I used the following configuration with the intention to backup the contents of everything reachable through one of the directories listed, without crossing file system borders

```
include = /
include = /mnt/something
```

However, `/mnt/something` and its contents are not backed up. Adding `cross_filesystem = /mnt/something` gives the desired backup set.

I expect all includes to be respected as starting points, irregardless of file system borders.
If this is not possible, I need to be pointed to this (strange) configuration issue, with bold letters and blinking warnings.

I'm running Debian Jessie on all my machines.

**Comment by grke** [comment]
Hello,

There would have been a warning in the log from your first example's backup, which would have come through to your email if you have notifications configured.

I agree that you would probably expect the filesystem to be crossed in that example.
So, I have just committed a change for the next burp-2 release that will make that happen.

Thanks for the report.

**Comment by C-Otto** [comment]
I understood the warning along the lines of "I will not back that up now, but don't worry, you included an extra 'include' line, so that will be done later".

Thank you.
