### ISSUE TITLE
Windows background backup fails

### ISSUE THREAD

**Issue by petrw** [grke/burp#291]
Hello,

i've set up BURP on few Windows XP SP3 pcs but background scheduled backup in scheduled tasks keeps bugging me.  When are backups run from shell manually, everything works as excepted but in log appears message "Failed to set thread_mode_background_begin"  which may be culprit. 

Windows XP is pretty obsolete OS but i haven found anyone having this issue so maybe it could be fixed somehow easily. Server is linux, ver 1.3.48, client 1.4.38. Thanks.

**Comment by grke** [comment]
Hello,

The burp server version should always be the same as, or newer than, the clients.
In your case, I would try 1.4.38 on the server.

You haven't said what the actual problem is. How does the backup fail? What does it say in the server side log for the failed backup?

**Comment by petrw** [comment]
Sorry, my bad. When run manually in shell from windows client, backups are alright. Problem is that when is client run by periodic rule in sheduled tasks, simply crashes and no backup takes place. Server logs look like usual so that led me to idea that it has something to do with "Failed to set thread_mode_background_begin" which can be seen in clients stdout when is backup done via shell command. Strange enough, one of affected clients now managed to do background backup like nothing and even mentioned log line doesnt show up anymore.

**Comment by grke** [comment]
I don't know what 'simply crashes' means. Do you mean that Windows doesn't even start the timed process, or do you mean something else?

Does the client get as far as contacting the server?

**Comment by petrw** [comment]
Unfortunately, i cant reproduce it right now. By crash i mean informational window like this:
http://www.nirsoft.net/utils/wincrashreport_windows_xp.png

Server log was like this:
forked child pid 2439
Jun  1 09:36:43 backup burp[2439]: WARNING: Client 'CLIENT' version '1.4.34' does not match server version '1.3.48'. An upgrade is recommended.
Jun  1 09:36:43 backup burp[2439]: WARNING: Client 'CLIENT' version '1.4.34' does not match server version '1.3.48'. An upgrade is recommended.
Jun  1 09:36:43 backup burp[2439]: auth ok for: CLIENT
Jun  1 09:36:43 backup burp[2439]: Client CLIENT does not want a certificate signed
Jun  1 09:36:43 backup burp[2439]: Client uses TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384
Jun  1 09:36:43 backup burp[2439]: Client supports being sent counters.
Jun  1 09:36:43 backup burp[2439]: Logging to /var/spool/burp/CLIENT/0000001 2015-06-01 09:31:05/log
Jun  1 09:36:43 backup burp[2439]: exit child

**Comment by grke** [comment]
First thing I would do is upgrade the server so it is on a version greater than or the same as the clients.

**Comment by grke** [comment]
If nothing else is said about this in the next few days, I will close this issue.

**Comment by petrw** [comment]
Seems that upgrading both client and server to 1.4.38 solved these issues. Thank you.

**Comment by grke** [comment]
OK, thanks for reporting back.
