### ISSUE TITLE
In 2.0.20 starting `burp -a s` doesnt work

### ISSUE THREAD

**Issue by laapsaap** [grke/burp#298]
I would imagine in 2.0.20 I can also start `burp -a s` on the server to see status of all the clients like in burp 1.

But I am getting this error;
```
2015-06-19 12:34:18: burp[22888] Could not get lockfile.              
2015-06-19 12:34:18: burp[22888] Another process is probably running, 
```

It wants to run as a daemon but I just want it to connect to the status port.

**Comment by grke** [comment]
Hello,
The status monitor works very differently in burp-2.0.20 than it did in burp-1.x.x.
Have you read the following page?
http://burp.grke.org/docs/monitor.html

**Comment by laapsaap** [comment]
Yes I did, but it was a bit confusing.
I mean I understand that from a client, its a nice feature to be able to see his own backup status.  But from the server I cant imagine not being able to burp -a s to see status for all my clients.

```
Once the burp server is running, the ncurses status monitor client can be run
with a command like this:

burp -a s
```

Its not clear whether this is possible on server and/or on the client.

**Comment by grke** [comment]
It is always via a client. The burp binary on the server is also a client that can be configured with burp.conf.
Have you tried running 'burp -a m'?

**Comment by laapsaap** [comment]
yeah, I got it working after I configured the client on the server too and added restore_client in each client config. Not sure if this is the correct way of doing this.
```
restore_client = backupserver
```

**Comment by grke** [comment]
Yes it is. If you want all clients to be visible to the monitor, you can just put your restore_client line in /etc/burp/burp-server.conf instead of the individual configs.

**Comment by laapsaap** [comment]
Good point, thanks!! Very happy with the solution.
