### ISSUE TITLE
Could not find wrap up index (burp 2.0.22)

### ISSUE THREAD

**Issue by laapsaap** [grke/burp#299]
When I run a backup and the backup process is running, I see this message "Could not find wrap up index"  every ~30 lines.  What does this mean?

**Comment by grke** [comment]
2.0.22 doesn't exist yet.
You appear to be using 2.0.21 in protocol2 mode. Protocol 2 mode is under heavy development, so don't try to use it for real backups. You can set 'protocol = 1' in any of the config files to use protocol 1 instead, which should be OK.

The message about the wrap up index is debug, and relates to streams of data being passed between components of the server.
