### ISSUE TITLE
Add option to take a list of paths for restore.

### ISSUE THREAD

**Issue by basd82** [grke/burp#30]
Add option to take a list of paths for restore.

**Comment by grke** [comment]
Would like to make it possible to specify a single path and restore precisely that path.

For example, it ought be possible to do a 'burp -a l -b 5 > files', and then feed 'files' back into a 'burp -a r -b 5' command.

**Comment by grke** [comment]
Changes now in master, ready for the next release.

Basically, this kind of thing works:
```
burp -a p -b 6 | burp -a R -b 7
```
ie, (parsable) list backup 6, feeding into restore from backup 7
See the new manpage for more details.
