### ISSUE TITLE
clock_gettime() not supported on Mac.

### ISSUE THREAD

**Issue by laapsaap** [grke/burp#300]
On a mac prog.c fails to compile because of clock_gettime. Its not supported on Mac.
```
clock_gettime(CLOCK_REALTIME, &ts);
```

I solved it using solution here
http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

```

struct timespec ts;

#ifdef __MACH__ // OS X does not have clock_gettime, use clock_get_time
clock_serv_t cclock;
mach_timespec_t mts;
host_get_clock_service(mach_host_self(), CALENDAR_CLOCK, &cclock);
clock_get_time(cclock, &mts);
mach_port_deallocate(mach_task_self(), cclock);
ts.tv_sec = mts.tv_sec;
ts.tv_nsec = mts.tv_nsec;

#else
clock_gettime(CLOCK_REALTIME, &ts);
#endif
```

And I removed -lrt from the Makefile

**Comment by grke** [comment]
Thanks for this. Did you have to add something like this anywhere:


#ifdef __MACH__
#include <mach/clock.h>
#include <mach/mach.h>
#endif

**Comment by grke** [comment]
Thanks for this. Did you have to add something like this anywhere:

{code}

#ifdef __MACH__
#include <mach/clock.h>
#include <mach/mach.h>
#endif
{code}

**Comment by grke** [comment]
Thanks for this - did you have to add headers like this anywhere:
mach/clock.h
mach/mach.h

**Comment by laapsaap** [comment]
I added these as includes in prog.c

```
#include <time.h>
#include <sys/time.h>

#ifdef __MACH__
#include <mach/clock.h>
#include <mach/mach.h>
#endif
```

**Comment by grke** [comment]
I have put the code in for the latest burp-2.0.x release.
But I haven't removed -lrt from the Makefile. The -lrt needs to be substituted in from autoconf/configure - I don't have time to mess with that right now.

**Comment by grke** [comment]
Got rid of the problem by using getpid() for the delay random seed.
