### ISSUE TITLE
ACL/xattr support for OpenBSD 5.7

### ISSUE THREAD

**Issue by Keithsc** [grke/burp#312]
Hi, I am trying to build Burp on OpenBSD but am having issues with rsync. I've installed the package librsync onto the server but ./config is still exiting with what looks like a librsync error. Do you have any suggestions on what I could try next ?

checking whether closedir returns void... no
checking for gettext in -lintl... no
checking for getpwnam in -lsun... no
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for deflate in -lz... yes
checking crypt.h usability... no
checking crypt.h presence... no
checking for crypt.h... no
checking for crypt in -lcrypt... no
checking uthash.h usability... yes
checking uthash.h presence... yes
checking for uthash.h... yes
checking librsync.h usability... yes
checking librsync.h presence... yes
checking for librsync.h... yes
checking for rs_delta_begin in -lrsync... no
Please install librsync
# 

Thanks
Keith

**Comment by Leryan** [comment]
"checking for rs_delta_begin in -lrsync... no" what is librsync's version?

**Comment by Keithsc** [comment]
Wow.. quick reply :>)

It's librsync-0.9.7p1.tgz<http://mirror.bytemark.co.uk/pub/OpenBSD/5.7/packages/amd64/librsync-0.9.7p1.tgz>



On 30/07/15 10:12, Florent Peterschmitt wrote:

"checking for rs_delta_begin in -lrsync... no" what is librsync's version?

—
Reply to this email directly or view it on GitHub<https://github.com/grke/burp/issues/312#issuecomment-126235538>.


********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by Leryan** [comment]
Forgot to ask: what burp version are you trying to build? Depending of that, librsync may be in a higher version like 1.x.

I haven't any OpenBSD box to try, but you could first try different versions of burp, like 1.3.x for example.

**Comment by grke** [comment]
What arguments did you give to configure?
Do the configure options mentioned at the bottom of the following link help?

https://github.com/grke/burp/issues/181

**Comment by Keithsc** [comment]
I was using the master branch and have now switched to v1.3. I tried to compile librsync and was very happy to see the post from gkre as changing the ./configure line seems to have got passed librsync issue although it has raised another.

LDFLAGS="-L/usr/local/lib" ./configure

and

./configure --prefix=/usr/local --sbindir=/usr/local/sbin LDFLAGS="-L/usr/local/lib"

both result in the following..

configure: creating ./config.status
config.status: creating autoconf/Make.common
config.status: creating Makefile
config.status: creating manpages/Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: executing default commands
Doing make of dependencies
==>Entering directory /root/burp-1.3-master/src
xattr.c:263:25: error: sys/extattr.h: No such file or directory
xattr.c:264:21: error: libutil.h: No such file or directory
*** Error 1 in src (Makefile:334 'depend': @g++ -S -M -I/usr/local/include -fno-strict-aliasing -fno-exceptions -fno-rtti   -I. -I..  *.c >>...)
*** Error 1 in /root/burp-1.3-master (Makefile:160 'depend')

Configuration on Thu Jul 30 11:02:11 BST 2015:

   Host:                        x86_64-unknown-openbsd5.7 -- openbsd
   Burp version:                Burp 1.3.49
   Source code location:        .
   Install binaries:            /usr/local/sbin
   Install config files:        /usr/local/etc
   Man directory:               ${datarootdir}/man
   C Compiler:                  gcc
   C++ Compiler:                g++
   Compiler flags:               -g -O2 -fno-strict-aliasing -fno-exceptions -fno-rtti
   Linker flags:                 -L/usr/local/lib
   Libraries:                    -lintl
   Static:

   ncurses:                     yes
   openssl:                     yes
   zlib:                        yes
   librsync:                    yes
   acl:                         no
   xattr:                       yes
   ipv6:                        yes


Cheers
Keith


On 30/07/15 10:16, Florent Peterschmitt wrote:

Forgot to ask: what burp version are you trying to build? Depending of that, librsync may be in a higher version like 1.x.

I haven't any OpenBSD box to try, but you could first try different versions of burp, like 1.3.x for example.

—
Reply to this email directly or view it on GitHub<https://github.com/grke/burp/issues/312#issuecomment-126236732>.


********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by grke** [comment]
1.3.49 is not a version that I have released.
I don't recommend that.
You should try 1.4.40.

Looks like you are missing sys/extatrr.h and libutil.h. I don't know where you can find them.

**Comment by Keithsc** [comment]
I've managed to build it but only after adding in "--disable-xattr".

You were right about the missing sys/extattr.h and libutil.h.  I downloaded the src and sys tar files for OpenBSD but couldn't find the extattr.h file then found the link below that says it was removed years ago. I tried just copying the file to the srv/sys folder but I couldn't get make to work.  The libutil.h it's just called util.h in openbsd.

http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/sys/Attic/extattr.h

./configure --disable-xattr --prefix=/usr/local --sbindir=/usr/local/sbin LDFLAGS="-L/usr/local/lib"

   ncurses:                 yes
   openssl:                 yes
   zlib:                        yes
   librsync:                 yes
   acl:                         no
   xattr:                      no
   ipv6:                       yes


I have 6 OpenBSD servers that I need to backup, all our other servers are either windows or linux so there's already burp clients that I belive we can use (the context for all of this is that we're trying to move our whole infrastructure off bacula enterprise). So for the 6 openbsd servers I realy just need to backup the /etc and /var/log folder so assuming that this might be sufficient?

Is my assumption right or would there be any implications of acl & xattr being disabled ?

Regards
Keith







On 30/07/15 12:29, grke wrote:

1.3.49 is not a version that I have released.
I don't recommend that.
You should try 1.4.40.

Looks like you are missing sys/extatrr.h and libutil.h. I don't know where you can find them.

—
Reply to this email directly or view it on GitHub<https://github.com/grke/burp/issues/312#issuecomment-126278725>.


********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by Leryan** [comment]
It shouldn't be a problem for xattr if you don't use some extra security programs like SELinux (under Linux of course…). For ACLs, hum, I read here and there that OpenBSD doesn't have ACLs.

**Comment by grke** [comment]
Since you only want to back up /etc and /var/log, you may want to figure out the openbsd command that tells you about acls and xattrs and see if you actually have any set.
If your files don't have acls or xattrs, then this is OK.

If your files have acls or xattrs, but you don't care about them, then this is also OK.

If your files have acls or xattrs, and you care about them, then this is not OK.

**Comment by rubenk** [comment]
Indeed, OpenBSD doesn't have acls and xattrs, but the configure check for that is broken somehow.
I'm looking into this now.
