### ISSUE TITLE
Files seem corrupt when using cat on the server

### ISSUE THREAD

**Issue by TheNotary** [grke/burp#314]
I setup burp a while back and thought everything was configured properly when I started seeing files appearing in say 

    burp_backups/epd-pc/current/data/t/C\:/Users/Desktop

For instance, shopping_list.txt contains a garbelled mess of binary data instead of textual information.  Does this indicate I've mis-configured things or is there a processing step that needs to be applied in order to peruse the backup data?  

I'm pretty sure I set no encryption password, unless the windows install defaulted a password.

**Comment by tokudan** [comment]
Accessing these files directly is not a supported way. There can be VSS headers at the beginning and the file is usually compressed. Restoring the file takes care of that.
If you want to do it manually, have a look at vss_strip and gunzip.

**Comment by TheNotary** [comment]
Thanks Tokudan, it's good to hear that my implementation is correct.  At the moment I'm looking into burp_ui which suggests an 'on-the-fly' backup perusing feature, though it's been slow going this past hour (https://git.ziirish.me/ziirish/burp-ui).  

Could you elaborate on vss_strip.  That's this I take it http://manned.org/vss_strip/081fb40b  How exactly do I invoke it's functionality?  I can't seem to find a binary named vss_strip on my Debian box.

**Comment by tokudan** [comment]
vss_strip is part of burp. If you're using the burp package from jessie, it should be in /usr/sbin/vss_strip:
```
# dpkg -L burp | grep vss
/usr/sbin/vss_strip
/usr/share/man/man8/vss_strip.8.gz
```

**Comment by TheNotary** [comment]
Hmm, vss isn't showing up from dpkg or /usr/sbin... can't remember how I installed it but I must have done something unique.  Anyway, vss_strip must be *somewhere* because on my windows client, the below command succeeded allowing me to check things over.  

    >  burp -a r -r Desktop -d C:/tmp

This allows a newcomer to burp to safely take a peak at the data.  I can't thank you enough Tokudan, it was a disconcerting moment I had while viewing the files on the server.
