### ISSUE TITLE
SSL3_GET_CLIENT_CERTIFICATE:no certificate returned:s3_srvr.c:3288:

### ISSUE THREAD

**Issue by laapsaap** [grke/burp#320]
```
error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned:s3_srvr.c:3288:
```

I am getting this message sometimes, but I cant identify which client is causing it. Because in the log it doesnt show anything except this. Would be nice to see some more info to be able to track down the client.

**Comment by grke** [comment]
Closing this because the work that you want me to do is the same as in #313.
