### ISSUE TITLE
Feature request, automatically resolve "finishing state"

### ISSUE THREAD

**Issue by laapsaap** [grke/burp#324]
I am not exactly sure, but from my understanding when a backup is finished; the client has to connect to burp server again to trigger the finishing. Isnt it better to resolve finishing state automatically without the client having to trigger it? 

Please correct me if I am wrong about this.

**Comment by grke** [comment]
Hello,

You are wrong about this. There are four phases to the backup, and they are described here:
http://burp.grke.org/docs/shuffling.html
The client disconnects after phase 2, but the server child process continues and keeps any
other server child process locked out until the server child exits.

The client only needs to connect again to trigger a resolve of phase 3 or 4 if the initial attempt at phase 3 or 4 failed or was interrupted for some reason.
