### ISSUE TITLE
Win xp,32bit, burp-2: The procedure entry point sprintf_s could not be located in the dynamic link library msvcrt.dll.

### ISSUE THREAD

**Issue by marcin-github** [grke/burp#325]
Hi!
I installed burp-2.0.24 for windows. When I try to run burp.exe it I'm getting:
`The procedure entry point sprintf_s could not be located in the dynamic link library msvcrt.dll.`
With 1.4.40 I didn't have such issue.

**Comment by grke** [comment]
Hello,

This is probably because burp-2 uses the yajl library, where burp-1 didn't.
Hopefully, you just need to change line 29 in src/yajl/yajl_tree.c to the following and recompile:

#if ( (defined(_WIN32) || defined(WIN32) ) && ( defined(_MSC_VER) ) )

**Comment by marcin-github** [comment]
I don't have enviroment to compile burp.exe by self :(

**Comment by grke** [comment]
Yes, it's quite tricky.

Here are some options for you:
*) Make the environment to compile it yourself. I have written instructions that start in src/win32/README, and I put a lot of effort to making it as simple as I reasonably could. However, I know it is still hard.
*) Wait for the next burp-2 release, which will be at the end of October. I will put in the change I mention before then.
*) Pay me to do a one-off build for you.
*) Go back to burp-1.4.40.
*) Don't use Windows XP.

I don't mean to be rude with these suggestions. I hope one of them works for you.

**Comment by marcin-github** [comment]
I don't get it as rude comment. It looks that I'll wait for next release. Thanks for quick reply!

**Comment by grke** [comment]
Argh, sorry, it seems that I didn't commit this fix in 2.0.26.
If you like, I can make a special build on top of 2.0.26 for you to test.

**Comment by marcin-github** [comment]
Thanks but I can wait with testing burp-2.x. I'll wait for next release.

**Comment by grke** [comment]
This should now be fixed in the 2.0.28 release, so I am closing the issue.
If you find that there is still a problem, you can reopen it.

**Comment by marcin-github** [comment]
I have bad news. I've installed burp-2.0.28 and this problem still exists.

**Comment by grke** [comment]
Reopening...

OK, maybe the define needs to say 'HAVE_WIN32' instead of 'WIN32'.
The choice of options for you is the same again. There will be another release at the end of December, which may or may not fix it.

**Comment by marcin-github** [comment]
2.0.30 - bug still exists. Are you going to make another attempt to fix it or you are going to give up?:)

**Comment by grke** [comment]
As you probably guessed, I have almost zero motivation to fix this. I also have no Windows XP machine to test on.

**Comment by grke** [comment]
I got a Windows XP machine and spent all day fixing this.
The next release will work.
Closing the issue.

**Comment by marcin-github** [comment]
Thanks a lot for spending nice day with XP:) It works also for me.
