### ISSUE TITLE
restoring during backup does not work in 2.0.24

### ISSUE THREAD

**Issue by nfp007** [grke/burp#327]
During the backup on the large server i tried rostore few files, but it does not work. I read somewhere that it should be possible. As a workaround i killed backup task, run restore and then resumed backup again.

**Comment by grke** [comment]
What exactly happens?
How many files are in the backup?
How many files are you trying to restore?
Are other clients also backing up at the same time?

Is it just that your file system is still slow?

**Comment by grke** [comment]
You are right, restoring during backup does not work. This is intentional.
I don't believe that I have ever written anything to the contrary. If I did, it would be helpful if you linked to it.
