### ISSUE TITLE
Make test failed on ubuntu Debian7

### ISSUE THREAD

**Issue by benlo06** [grke/burp#328]
Hello,
I would like make deb package of burp2. I compile on debian7 64b.
But I have a link error when debuild launch make test, the compile return undefined reference,
<code>
 make test
cd utest && make && cd -
make[1]: Entering directory `/opt/fabrik/burp2/utest'
Linking test ...
g++   -o test \
	  builders/build_attribs.o builders/protocol2/build_blist.o builders/server/build_manifest.o builders/server/build_storage_dirs.o builders/server/protocol2/champ_chooser/build_dindex.o builders/build_paths.o main.o mock.o prng.o test_alloc.o test_attribs.o test_base64.o test_cmd.o test_conf.o test_conffile.o test_fzp.o test_hexmap.o test_lock.o test_pathcmp.o protocol2/test_blist.o protocol2/rabin/test_rconf.o protocol2/rabin/test_win.o client/test_find.o server/protocol1/test_dpth.o server/protocol1/test_fdirs.o server/protocol2/champ_chooser/test_candidate.o server/protocol2/champ_chooser/test_dindex.o server/protocol2/champ_chooser/test_scores.o server/protocol2/champ_chooser/test_sparse.o server/protocol2/test_backup_phase4.o server/protocol2/test_dpth.o server/test_bu_get.o server/test_delete.o server/test_manio.o server/test_resume.o server/test_sdirs.o ../src/alloc.o ../src/attribs.o ../src/base64.o ../src/bfile.o ../src/bu.o ../src/cmd.o ../src/cntr.o ../src/conf.o ../src/conffile.o ../src/fsops.o ../src/fzp.o ../src/handy.o ../src/hexmap.o ../src/iobuf.o ../src/linkhash.o ../src/lock.o ../src/msg.o ../src/pathcmp.o ../src/prepend.o ../src/regexp.o ../src/sbuf.o ../src/slist.o ../src/strlist.o ../src/protocol1/handy.o ../src/protocol1/rs_buf.o ../src/protocol1/sbuf_protocol1.o ../src/protocol2/blk.o ../src/protocol2/blist.o ../src/protocol2/rabin/rabin.o ../src/protocol2/rabin/rconf.o ../src/protocol2/rabin/win.o ../src/protocol2/sbuf_protocol2.o ../src/client/find.o ../src/server/bu_get.o ../src/server/compress.o ../src/server/dpth.o ../src/server/delete.o ../src/server/manio.o ../src/server/sdirs.o ../src/server/protocol1/dpth.o ../src/server/protocol1/fdirs.o ../src/server/protocol1/link.o ../src/server/protocol1/zlibio.o ../src/server/protocol2/dpth.o ../src/server/protocol2/backup_phase4.o ../src/server/protocol2/champ_chooser/candidate.o ../src/server/protocol2/champ_chooser/champ_chooser.o ../src/server/protocol2/champ_chooser/dindex.o ../src/server/protocol2/champ_chooser/hash.o ../src/server/protocol2/champ_chooser/incoming.o ../src/server/protocol2/champ_chooser/scores.o ../src/server/protocol2/champ_chooser/sparse.o ../src/server/resume.o ../src/server/timestamp.o   -lm -lcheck -lpthread -lm -lssl -lcrypto -lrt \
	   -lz -lrsync -lgcov
builders/server/protocol2/champ_chooser/build_dindex.o: In function `dindex_to_fzp':
/opt/fabrik/burp2/utest/builders/server/protocol2/champ_chooser/build_dindex.c:10: undefined reference to `gzprintf_dindex(fzp*, unsigned long*)'
test_alloc.o: In function `test_alloc':
/opt/fabrik/burp2/utest/test_alloc.c:17: undefined reference to `alloc_counters_reset()'
/opt/fabrik/burp2/utest/test_alloc.c:23: undefined reference to `alloc_count'
test_alloc.o: In function `alloc_check()':
/opt/fabrik/burp2/utest/test_alloc.c:8: undefined reference to `alloc_count'
/opt/fabrik/burp2/utest/test_alloc.c:8: undefined reference to `free_count'
test_conffile.o: In function `setup':
/opt/fabrik/burp2/utest/test_conffile.c:19: undefined reference to `alloc_counters_reset()'
test_conffile.o: In function `clientconfdir_setup':
/opt/fabrik/burp2/utest/test_conffile.c:396: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
/opt/fabrik/burp2/utest/test_conffile.c:398: undefined reference to `conf_load_overrides_buf(conf**, conf**, char const*)'
test_conffile.o: In function `test_conf_switch_to_orig_client_ok':
/opt/fabrik/burp2/utest/test_conffile.c:604: undefined reference to `conf_switch_to_orig_client_buf(conf**, conf**, char const*, char const*)'
test_conffile.o: In function `test_conf_switch_to_orig_client_fail':
/opt/fabrik/burp2/utest/test_conffile.c:587: undefined reference to `conf_switch_to_orig_client_buf(conf**, conf**, char const*, char const*)'
test_conffile.o: In function `test_client_include_failures':
/opt/fabrik/burp2/utest/test_conffile.c:179: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `test_client_includes_excludes':
/opt/fabrik/burp2/utest/test_conffile.c:133: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `pre_post_checks':
/opt/fabrik/burp2/utest/test_conffile.c:245: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `test_server_conf':
/opt/fabrik/burp2/utest/test_conffile.c:191: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `test_client_conf':
/opt/fabrik/burp2/utest/test_conffile.c:81: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
client/test_find.o:/opt/fabrik/burp2/utest/client/test_find.c:182: more undefined references to `conf_load_global_only_buf(char const*, conf**)' follow
server/protocol2/champ_chooser/test_dindex.o: In function `common_di':
/opt/fabrik/burp2/utest/server/protocol2/champ_chooser/test_dindex.c:94: undefined reference to `compare_dindexes_and_unlink_datafiles(char const*, char const*, char const*)'
server/protocol2/test_backup_phase4.o: In function `sp_to_fzp':
/opt/fabrik/burp2/utest/server/protocol2/test_backup_phase4.c:42: undefined reference to `write_hook_header(fzp*, char const*, char const*)'
server/protocol2/test_backup_phase4.o: In function `common':
/opt/fabrik/burp2/utest/server/protocol2/test_backup_phase4.c:121: undefined reference to `merge_sparse_indexes(char const*, char const*, char const*)'
server/test_manio.o: In function `test_man_find_boundary':
/opt/fabrik/burp2/utest/server/test_manio.c:426: undefined reference to `manio_find_boundary(unsigned char*)'
server/test_resume.o: In function `go_before_entry':
/opt/fabrik/burp2/utest/server/test_resume.c:666: undefined reference to `forward_before_entry(manio*, iobuf*, cntr*, dpth*, protocol, man_off**)'
server/test_resume.o: In function `go_past_entry':
/opt/fabrik/burp2/utest/server/test_resume.c:459: undefined reference to `forward_past_entry(manio*, iobuf*, protocol, man_off**)'
server/test_resume.o: In function `last_good_entry':
/opt/fabrik/burp2/utest/server/test_resume.c:234: undefined reference to `get_last_good_entry(manio*, iobuf*, cntr*, dpth*, protocol, man_off**)'
/opt/fabrik/burp2/utest/server/test_resume.c:245: undefined reference to `get_last_good_entry(manio*, iobuf*, cntr*, dpth*, protocol, man_off**)'
../src/cntr.o: In function `cntr_stats_to_file(cntr*, char const*, action, conf**)':
/opt/fabrik/burp2/src/cntr.c:543: undefined reference to `async_alloc()'
/opt/fabrik/burp2/src/cntr.c:569: undefined reference to `async_free(async**)'
/opt/fabrik/burp2/src/cntr.c:570: undefined reference to `asfd_free(asfd**)'
/opt/fabrik/burp2/src/cntr.c:545: undefined reference to `asfd_alloc()'
/opt/fabrik/burp2/src/cntr.c:551: undefined reference to `json_cntr_to_file(asfd*, cntr*)'
collect2: error: ld returned 1 exit status
make[1]: *** [test] Error 1
make[1]: Leaving directory `/opt/fabrik/burp2/utest'
make: *** [test] Error 2
</code>

Do you have any idea for resolve this problems ?

Regards,
Ben

**Comment by grke** [comment]
Hello,
I think you have probably built in the src directory before trying to build in the utest directory.
You need to do both steps separately, with cleanup between them, because the object files that
get built for each task will conflict with one another.

Try this by hand:
cd burp (so you are in the root of the burp source)
make clean
git status
If there are any unexpected files, do: git clean -f -d
./configure
cd utest
make test

**Comment by benlo06** [comment]
Hello,
Thanks for your answer, but I launch debuild for build debian package and I dont choose any directory.
I try to build package with pduilder but It's fails too. If I compile Burp with make and make test, it's good.
Do you have idea for solve this problem ?

Regards,
Ben

<pre>
[...]
debuild -S -sa
sudo pbuilder --create --extrapackages check
cd burp-2.0.21
pdebuild
[...]
</pre>

And compilation failed with staus:
<pre>g++   -c  -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -fno-exceptions -fno-rtti -Wall  -I -I  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -Wall -g -fprofile-arcs -ftest-coverage -DUTEST server/test_sdirs.c -o server/test_sdirs.o
Linking test ...
g++  -Wl,-z,relro -o test \
  builders/build_attribs.o builders/protocol2/build_blist.o builders/server/build_manifest.o builders/build_paths.o main.o mock.o prng.o test_alloc.o test_attribs.o test_base64.o test_cmd.o test_conf.o test_conffile.o test_fzp.o test_hexmap.o test_lock.o test_pathcmp.o protocol2/test_blist.o server/protocol1/test_dpth.o server/protocol1/test_fdirs.o server/protocol2/test_dpth.o server/test_manio.o server/test_sdirs.o ../src/alloc.o ../src/attribs.o ../src/base64.o ../src/bfile.o ../src/bu.o ../src/cmd.o ../src/cntr.o ../src/conf.o ../src/conffile.o ../src/fsops.o ../src/fzp.o ../src/handy.o ../src/hexmap.o ../src/iobuf.o ../src/lock.o ../src/msg.o ../src/pathcmp.o ../src/prepend.o ../src/sbuf.o ../src/slist.o ../src/strlist.o ../src/protocol1/handy.o ../src/protocol1/rs_buf.o ../src/protocol1/sbuf_protocol1.o ../src/protocol2/blk.o ../src/protocol2/blist.o ../src/protocol2/sbuf_protocol2.o ../src/server/bu_get.o ../src/server/compress.o ../src/server/dpth.o ../src/server/manio.o ../src/server/sdirs.o ../src/server/protocol1/dpth.o ../src/server/protocol1/fdirs.o ../src/server/protocol1/zlibio.o ../src/server/protocol2/dpth.o ../src/server/resume2.o ../src/server/timestamp.o   -lm -lcheck -lpthread -lm -lrt -lssl -lcrypto \
   -lz -lrsync -lgcov
test_alloc.o: In function `test_alloc(int)':
/tmp/buildd/burp-2.0.21/utest/test_alloc.c:16: undefined reference to `alloc_counters_reset()'
/tmp/buildd/burp-2.0.21/utest/test_alloc.c:22: undefined reference to `alloc_count'
test_alloc.o: In function `alloc_check()':
/tmp/buildd/burp-2.0.21/utest/test_alloc.c:7: undefined reference to `alloc_count'
/tmp/buildd/burp-2.0.21/utest/test_alloc.c:7: undefined reference to `free_count'
test_conffile.o: In function `test_client_include_failures(int)':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:19: undefined reference to `alloc_counters_reset()'
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:191: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `test_client_includes_excludes(int)':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:19: undefined reference to `alloc_counters_reset()'
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:145: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `pre_post_checks(char const*, char const*, char const*, char const*, char const*, char const*, char const*, conf_opt, conf_opt, conf_opt, conf_opt, conf_opt, conf_opt, conf_opt)':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:19: undefined reference to `alloc_counters_reset()'
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:257: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `test_server_conf(int)':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:19: undefined reference to `alloc_counters_reset()'
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:203: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `test_client_conf(int)':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:19: undefined reference to `alloc_counters_reset()'
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:93: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
test_conffile.o: In function `clientconfdir_setup(conf***, conf***, char const*, char const*) [clone .constprop.0]':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:19: undefined reference to `alloc_counters_reset()'
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:408: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:410: undefined reference to `conf_load_overrides_buf(conf**, conf**, char const*)'
test_conffile.o: In function `test_conf_switch_to_orig_client_fail(int)':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:599: undefined reference to `conf_switch_to_orig_client_buf(conf**, conf**, char const*, char const*)'
test_conffile.o: In function `test_conf_switch_to_orig_client_ok(int)':
/tmp/buildd/burp-2.0.21/utest/test_conffile.c:616: undefined reference to `conf_switch_to_orig_client_buf(conf**, conf**, char const*, char const*)'
server/protocol1/test_dpth.o: In function `tear_down(dpth**)':
/tmp/buildd/burp-2.0.21/utest/server/protocol1/test_dpth.c:41: undefined reference to `alloc_count'
/tmp/buildd/burp-2.0.21/utest/server/protocol1/test_dpth.c:41: undefined reference to `free_count'
server/protocol1/test_fdirs.o: In function `test_fdirs(int)':
/tmp/buildd/burp-2.0.21/utest/server/protocol1/test_fdirs.c:15: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
/tmp/buildd/burp-2.0.21/utest/server/protocol1/test_fdirs.c:42: undefined reference to `alloc_count'
/tmp/buildd/burp-2.0.21/utest/server/protocol1/test_fdirs.c:42: undefined reference to `free_count'
server/protocol2/test_dpth.o: In function `tear_down(dpth**)':
/tmp/buildd/burp-2.0.21/utest/server/protocol2/test_dpth.c:46: undefined reference to `alloc_count'
/tmp/buildd/burp-2.0.21/utest/server/protocol2/test_dpth.c:46: undefined reference to `free_count'
server/test_sdirs.o: In function `setup_confs(char const*)':
/tmp/buildd/burp-2.0.21/utest/server/test_sdirs.c:19: undefined reference to `conf_load_global_only_buf(char const*, conf**)'
server/test_sdirs.o: In function `tear_down(sdirs**, conf***)':
/tmp/buildd/burp-2.0.21/utest/server/test_sdirs.c:39: undefined reference to `alloc_count'
/tmp/buildd/burp-2.0.21/utest/server/test_sdirs.c:39: undefined reference to `free_count'
../src/cntr.o: In function `cntr_stats_to_file(cntr*, char const*, action, conf**)':
/tmp/buildd/burp-2.0.21/src/cntr.c:543: undefined reference to `async_alloc()'
/tmp/buildd/burp-2.0.21/src/cntr.c:569: undefined reference to `async_free(async**)'
/tmp/buildd/burp-2.0.21/src/cntr.c:570: undefined reference to `asfd_free(asfd**)'
/tmp/buildd/burp-2.0.21/src/cntr.c:545: undefined reference to `asfd_alloc()'
/tmp/buildd/burp-2.0.21/src/cntr.c:551: undefined reference to `json_cntr_to_file(asfd*, cntr*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x584): undefined reference to `subunit_test_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x63f): undefined reference to `subunit_test_fail'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x654): undefined reference to `subunit_test_pass'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x66f): undefined reference to `subunit_test_error'
collect2: error: ld returned 1 exit status
Makefile:80: recipe for target 'test' failed
make[2]: *** [test] Error 1
make[2]: Leaving directory '/tmp/buildd/burp-2.0.21/utest'
Makefile:263: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/tmp/buildd/burp-2.0.21'
dh_auto_test: make -j1 test returned exit code 2
debian/rules:8: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Failed autobuilding of package
I: unmounting dev/pts filesystem
I: unmounting proc filesystem
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build//4836 and its subdirectories
build@infra:~/burp-2.0.21$ 

</pre>

**Comment by benlo06** [comment]
Ok,
I'had remove from Makefile Test sections and build works fine,

Regards,
Ben
