### ISSUE TITLE
Improve documentation in manpage for "-f"

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#330]
See http://burp.grke.org/docs/manpage.html

````
-f [path]
	      Short for 'force overwrite'. Without this option set, a  restore
	      will not overwrite existing files.
````
Is the "path" left over from some copy&paste operation? It doesn't sound like "force overwrite" should need a path.
If not, what should be specified as a path?
Docs should be updated in both cases.

**Comment by grke** [comment]
Fixed in latest release.

**Comment by larsen0815** [comment]
Thx!
