### ISSUE TITLE
--prefix=/x ignored for /var/spool/burp and /var/run

### ISSUE THREAD

**Issue by tokudan** [grke/burp#336]
While working on a package for NixOS I noticed that burp partially ignores a prefix setting:
Makefile.in contains
  ./Makefile.in:  $(MKDIR) $(DESTDIR)/var/run
  ./Makefile.in:  $(MKDIR) $(DESTDIR)/var/spool/burp

This ignores a possible prefix set through configure:
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]

**Comment by grke** [comment]
Hello,
This is the same problem as in https://github.com/grke/burp/issues/266
I will copy your message there, and close this one.
Thanks.
