### ISSUE TITLE
vss_strip.c: warning: no return statement in function returning non-void

### ISSUE THREAD

**Issue by stefjakobs** [grke/burp#338]
Compiling burp-1.4.40 results in the following warning:
vss_strip.c: In function 'const char* get_progname(const char*)':
vss_strip.c:158:1: warning: no return statement in function returning non-void [-Wreturn-type]

The following patch will fix that issue:

    diff -ur burp-1.4.40/src/vss_strip.c burp-1.4.40.new/src/vss_strip.c
    --- burp-1.4.40/src/vss_strip.c  2015-07-01 13:45:08.000000000 +0200
    +++ burp-1.4.40.new/src/vss_strip.c 2015-11-10 23:01:28.587823808 +0100
    @@ -151,7 +151,7 @@
       fprintf(stderr, " -h|-?       Print this message\n");
     }

    -static const char *get_progname(const char *arg)
    +static void get_progname(const char *arg)
     {
       if((prog=strrchr(arg, '/'))) prog++;
       else prog=arg;

Thank you for working on burp.

**Comment by grke** [comment]
Hello,
Thanks a lot for that, but it is already fixed in master.
