### ISSUE TITLE
osx client does not exit after backup

### ISSUE THREAD

**Issue by saaby** [grke/burp#339]
Hi,

My 1.4.28 osx burp client, installed via homebrew, will not exit after a backup, not even after hours of being seemingly idle.

dtruss -p <pid> just waits here:
SYSCALL(args) 		 = return

lsof <pid> says:
burp      53889            root  cwd       DIR                1,4        374 18516478 /private/var/root
burp      53889            root  txt       REG                1,4     271696 33044185 /usr/local/Cellar/burp/1.4.28/bin/burp
burp      53889            root  txt       REG                1,4     368240 33044041 /usr/local/Cellar/openssl/1.0.2d_1/lib/libssl.1.0.0.dylib
burp      53889            root  txt       REG                1,4    1865900 33044038 /usr/local/Cellar/openssl/1.0.2d_1/lib/libcrypto.1.0.0.dylib
burp      53889            root  txt       REG                1,4      54320 33042462 /usr/local/Cellar/librsync/0.9.7/lib/librsync.1.0.2.dylib
burp      53889            root  txt       REG                1,4      43640 33042425 /usr/local/Cellar/popt/1.16/lib/libpopt.0.dylib
burp      53889            root  txt       REG                1,4     638336 32210271 /usr/lib/dyld
burp      53889            root  txt       REG                1,4  489322734 32212047 /private/var/db/dyld/dyld_shared_cache_x86_64
burp      53889            root    0      PIPE 0xde94cc74cbfc1dd9      16384
burp      53889            root    1w      CHR                3,2   0t911677      303 /dev/null
burp      53889            root    2      PIPE 0xde94cc74c7751299      16384          ->0xde94cc74c7750459
burp      53889            root    3w      REG                1,4         11 33652977 /usr/local/var/run/burp.client.pid
burp      53889            root    4u     IPv4 0xde94cc74caae83f9        0t0      TCP 10.111.10.67:59817->burp-server-ip:4971 (FIN_WAIT_2)
burp      53889            root    5u     unix 0xde94cc74b1aec9c9        0t0          ->0xde94cc74c1d9c131

As far as I can see the client still thinks it has a connection to the server (in FIN_WAIT_2 state), i.e. still waiting for the final FIN packet from the server. - However the server doesn't have any connections established to the client at this point.

It might be something completely unrelated though. Any clues on how to proceed debugging?

**Comment by grke** [comment]
Hello,
1.4.28 is quite old. I would recommend upgrading to 1.4.40 or 2.0.26 (protocol=1 in burp-server.conf) to see if the problem goes away.

**Comment by saaby** [comment]
ah ok, 1.4.28 is the latest stable version available in homebrew. - I just tried building/installing HEAD on my osx, however that ended up being pretty painful, as the homebrew patchset won't apply (i fixed that), and uthash not being available through homebrew (that I didn't fix).

I will give it a better try when I have more time on my hands. - Am I missing an easier route btw.?

**Comment by grke** [comment]
I have no idea, as I don't get involved with packaging and I don't use Macs.

It is worth joining the burp-users mailing list to ask about the best way to install 2.0.x on a Mac, as somebody there will probably have more of a clue than me.

**Comment by saaby** [comment]
All right, I'll hit the mailing list instead. Thanks.

**Comment by grke** [comment]
This may well be to do with mac xattrs. There are many fixes for mac xattrs in 2.0.x.
I will close this issue because I think 2.0.x is OK.

**Comment by grke** [comment]
Please reopen if you test 2.0.x and you still have a problem.
