### ISSUE TITLE
When people suspend their pc, burp clients doesnt exit.

### ISSUE THREAD

**Issue by laapsaap** [grke/burp#340]
Hi,

I am running burp for 500 laptops and its working great. But some of my users never reboots their laptop and only suspend it every day. What happens is burp keeps running without exiting and the cronjob that starts burp every X hour never starts because burp is running.

Is there a way to make burp exit if its stalled?  Right now I am thinking to use the cronjob script to make a check, but I think its better if burp can handle this itself.

**Comment by grke** [comment]
Hello,
What do you mean by 'burp keeps running without exiting'? Do you mean the server process?
Have you tried the 'network_timeout' option?

**Comment by grke** [comment]
The option defaults to 7200 seconds. Try setting it to something like 5 minutes (300). You will need to do this in the client burp.conf, so it will be difficult for 500 laptops.

**Comment by laapsaap** [comment]
Hmm I mean the burp client. It never exits on the laptops even after 7200secs. But let me do some more research what is exactly happening.

**Comment by laapsaap** [comment]
'''
root            62703   0.0  0.0  2463616      4   ??  S     9Nov15   0:34.70 /usr/sbin/burp -a t
'''

This started on 9nov, it never resumed or exit.

**Comment by laapsaap** [comment]
Its burp-2.0.22, but seriously no idea which commit. But its a commit around Aug 31.

**Comment by grke** [comment]
This is probably a genuine bug that exists in master, but it's crazy of you to have put some random commit on 500 laptops rather than a proper release.

**Comment by laapsaap** [comment]
Your commits in master fixed a lot of problems we had with 2.0.21 :)   

Let me know if you want me to do some test to replicate the problem.

**Comment by ziirish** [comment]
What OS/distrib are your laptops running?

As a workaround you could maybe add a pre-suspend hook that kills running burp instances?

**Comment by grke** [comment]
No reply to ziirish. Closing.
