### ISSUE TITLE
Make path to CRL configurable

### ISSUE THREAD

**Issue by tobru** [grke/burp#341]
Setting `ca_crl_check` to 1 invokes some "magic" (see https://github.com/grke/burp/blob/master/src/server/ca.c#L46) to find the path to the CRL. If we use an external CA with a CRL file named and located differently it would help if there is an option `ssl_crl` to define the exact path to the CRL file.

**Comment by grke** [comment]
Hello,

You are welcome to submit a patch because I don't have any incentive to do this any time soon.

Would a new option be easier than you just creating a symlink from CA_(name).crl to your external file?

**Comment by tobru** [comment]
I would really like to contribute code to BURP, but I'm not a C programmer =( Too bad! Of course I could create a symlink, but I thought a configuration directive would be much cleaner, because all other SSL parameters are also configurable. So if it's ok we can keep this request open and hope that a C coder implements this... It is of no hurry, of course =)

**Comment by grke** [comment]
Done for the next release.
