### ISSUE TITLE
Override Backup path on server from client

### ISSUE THREAD

**Issue by Yamakasi** [grke/burp#349]
It would be nice if we can overwrite the backup folder @ the server from a client.

Like you set on the server:
backup_path_1= /home/backup_folder_1
backup_path_2= /home/backup_folder_2

And in the client you set the backuppath if not default like:

backup_to: backup_path_2

In this case it saves us to run a new burp server for a new environment, if you want to split backups per environment on disks

I hope this can be done.

Thanks for the great project!

**Comment by grke** [comment]
Hello.
Why don't you just set the directory per client in the /etc/burp/clientconfdir/clientname files?

**Comment by Yamakasi** [comment]
Hi,

Could do I guess :) Need to check how. But that is the common way to overwrite it ?

**Comment by grke** [comment]
Look in the man page for the 'directory=[path]' option and the 'SERVER CLIENTCONFDIR FILE' section.

**Comment by Yamakasi** [comment]
I need to come back to this.

I know the server needs to be in control but per clientside set this would be nicer than in the client configfile on the server. The reason why is that if you provision servers you want to set settings per node, not on the central server for this matter.

**Comment by grke** [comment]
I am confused. Ae you talking about directories on the client to back up, or are you talking about the directory on the burp server where backups are saved?
