### ISSUE TITLE
Another build failure on OpenIndiana

### ISSUE THREAD

**Issue by rubenk** [grke/burp#352]
```
$ make V=1
Making all in src
make[1]: Entering directory '/home/ruben/src/burp/src'
make  all-am
make[2]: Entering directory '/home/ruben/src/burp/src'
g++ -DHAVE_CONFIG_H -I.   -DSYSCONFDIR=\"/usr/local/etc\"    -g -O2 -MT server/protocol1/burp-blocklen.o -MD -MP -MF server/protocol1/.deps/burp-blocklen.Tpo -c -o server/protocol1/burp-blocklen.o `test -f 'server/protocol1/blocklen.c' || echo './'`server/protocol1/blocklen.c
server/protocol1/blocklen.c: In function ‘size_t get_librsync_block_len(const char*)’:
server/protocol1/blocklen.c:17:31: error: call of overloaded ‘sqrt(uint64_t&)’ is ambiguous
  ret=(size_t)(ceil(sqrt(oldlen)/16)*16); // round to a multiple of 16.
                               ^
server/protocol1/blocklen.c:17:31: note: candidates are:
In file included from /usr/include/math.h:32:0,
                 from server/protocol1/blocklen.c:4:
/usr/include/iso/math_iso.h:218:21: note: long double std::sqrt(long double)
  inline long double sqrt(long double __X) { return __sqrtl(__X); }
                     ^
/usr/include/iso/math_iso.h:186:15: note: float std::sqrt(float)
  inline float sqrt(float __X) { return __sqrtf(__X); }
               ^
/usr/include/iso/math_iso.h:85:15: note: double std::sqrt(double)
 extern double sqrt __P((double));
               ^
Makefile:2602: recipe for target 'server/protocol1/burp-blocklen.o' failed
make[2]: *** [server/protocol1/burp-blocklen.o] Error 1
make[2]: Leaving directory '/home/ruben/src/burp/src'
Makefile:583: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ruben/src/burp/src'
Makefile:431: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by rubenk** [comment]
This seems to fix it.

**Comment by grke** [comment]
This patch changes behaviour - it makes test_blocklen fail.

Is the output above complaining that sqrt(oldlen)/16 is ambiguous because it doesn't know whether to sqrt before dividing by 16?
 
Does the following make it go away?
ret=(size_t)(ceil((sqrt(oldlen))/16)*16);

**Comment by rubenk** [comment]
No, sorry, still the same error.
I think since oldlen is unsigned long long, the compiler doesn't know which version of sqrt to call.

**Comment by rubenk** [comment]
Thanks for merging, but this looks wrong. Did you merge the previous commit?

**Comment by grke** [comment]
I only merged the massive chain that you worked on, plus some small pieces that I have been fiddling with to get my automatic builds working again. I am still fiddling with getting the code coverage stuff working correctly. When I have done that, I will come back here and check this.

**Comment by rubenk** [comment]
That's the thing, I thought that you already did that 4 days ago in commit 42d1f77d71b157613ec7333971f67da70743e76e
Perhaps you had an older version of this PR in your working dir?

No hurries :) If there's anything I can do to help, let me know. I'll keep filing issues in the meantime ;)

**Comment by grke** [comment]
All good at the moment, I just need time to work through all of the recent changes...

**Comment by grke** [comment]
I am aiming to merge all the currently outstanding pull requests and do a release today, since it is the beginning of a new month.

**Comment by grke** [comment]
I think it is now OK in git master.

**Comment by rubenk** [comment]
It is, thank you.
