### ISSUE TITLE
But cannot exec su commands ?

### ISSUE THREAD

**Issue by Yamakasi** [grke/burp#366]
Hi,

My pre-scripts fail on this:

su - username -c "/path/command -c /tmp/path"

I also tried it with /bin/su 

In a bash script it fails and as direct script burp says it cannot find the command.

What am I doing wrong ?

/me is happy burping :)

**Comment by grke** [comment]
Try putting the path to su, like /sbin/su or whatever it is. If that doesn't work, post more detail here. Paste the actual error verbatim.

**Comment by Yamakasi** [comment]
Yes I did that but it didn't work out in the first place.
I just echoed something in my script which I call now as it also happened in there.
Does but expect some sort of exit; ?

**Comment by grke** [comment]
Please post the config that you are setting, the script that you are trying to run, and the actual error mesaage.

**Comment by grke** [comment]
I will close this issue in a few days if there are no more details provided.

**Comment by Yamakasi** [comment]
Hi,

Sorry, I just saw my message was on concepts and not send. I will do some
new tests today/tomorrow and will report it.

Thanks for the heads up!

2016-01-14 14:58 GMT+01:00 grke <notifications@github.com>:

**Comment by grke** [comment]
OK.

**Comment by grke** [comment]
Now closing.
You can join the burp-users mailing list and ask your questions there if you need more help. More people will answer a post on the mailing list than here.

**Comment by Yamakasi** [comment]
Hi, I got some delay in my time to test because I need mutliple commands to test here, I will close back and update you when I see things going wrong. Sorry :) !
