### ISSUE TITLE
Setsockopt errors

### ISSUE THREAD

**Issue by rubenk** [grke/burp#371]
I see this on FreeBSD and OSX:
```
main socket: error: setsockopt IPTOS_THROUGHPUT: Invalid argument
```

I think you're only allowed to set this on IPv4 sockets, and this shows up if the socket is IPv6.
IPv6 uses traffic classes if I'm not mistaken (IPV6_TCLASS)

**Comment by grke** [comment]
Apparently, IPTOS_THROUGHPUT is deprecated and it should use DSCP and CS definitions instead.
This stuff is hard to figure out, but I will get there.

See /usr/include/netinet/ip.h

**Comment by grke** [comment]
Should be fixed in latest master.
