### ISSUE TITLE
Various test failures on different operating systems

### ISSUE THREAD

**Issue by rubenk** [grke/burp#379]
Hi Graham,

I've run the test suites on a few different platforms and gathered the results at
https://gist.github.com/rubenk/a81c01c73ec3b02a1863

Not sure when I can get to them, but perhaps you can take a look?

**Comment by grke** [comment]
I will comment on that thread directly.

**Comment by grke** [comment]
All now passing.

**Comment by rubenk** [comment]
Great, thanks a lot Graham!
