### ISSUE TITLE
Debian initscript needs to be adapted to new default installation path

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#380]
The file "burp/debian/init" has not yet been adapted to use "DAEMON=/usr/local/sbin/burp" instead of "DAEMON=/usr/sbin/burp".

Also, the path "/usr/local/var/run/" needs to be created, so the initscrip can create "burp.server.pid".

**Comment by grke** [comment]
Is it normal for debian packages to install into /usr/local?

Is it better to just do this
./configure --prefix=/usr --sysconfdir=/etc/burp --localstatedir=/var
?

**Comment by larsen0815** [comment]
Well, I thought of the script as "you can use this on your Debian server" instead of "this is for package maintainers". For the latter case, you are correct. So I guess this depends on how you see the purpose of this script.

As this isn't something big, I wouldn't mind if you wanted to just close it.

**Comment by grke** [comment]
OK, thanks.
I have always thought of it as "this is for package maintainers".
