### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by KeinNerd** [grke/burp#405]
Hey, i want to compile from source but: 

root@marsi:/usr/src# cd burp/
root@marsi:/usr/src/burp# ./configure --prefix=/usr --sysconfdir=/etc/burp --localstatedir=/var
-bash: ./configure: No such file or directory
root@marsi:/usr/src/burp#

What's happen?

**Comment by grke** [comment]
Hello,
Did you read the README file in the top level of the source?

**Comment by KeinNerd** [comment]
Yes I installed all the needed packages. The rights set. But the problem persists .. :(

**Comment by KeinNerd** [comment]
Okay. -.- i have forget to "autoreconf -vif" all is fine. THX!
