### ISSUE TITLE
bsigs: what is it ?

### ISSUE THREAD

**Issue by yopito** [grke/burp#407]
Hello,
`bsigs` utility (symlink to `/usr/bin/burp`) is not documented in burp-2.0.32. Could you write its man page ?

**Comment by grke** [comment]
It is a tool that helps me to examine protocol2 signature and manifest files.
They contain signatures and checksums in binary - bsigs reads the files and outputs the signature/checksum parts in hex.
Yes, I will make a man page when I get the opportunity.

**Comment by grke** [comment]
There is a bsigs manpage in master now.

**Comment by yopito** [comment]
nice, thank you !

**Comment by yopito** [comment]
from a packaging perspective (rpm): does `bsigs` should be provided or not to "end-users" ? what's your feeling about it ?

**Comment by grke** [comment]
From my point of view, yes.

**Comment by yopito** [comment]
ok, thanks.
