### ISSUE TITLE
Feature request: add server_can_override_includes

### ISSUE THREAD

**Issue by juodumas** [grke/burp#413]
I have started backing up a handful of computers which are perfectly fine with the server overriding include/exclude directives in clientconfdirs. But one computer has more sensitive data and I don't like the idea that the burp server can access the whole filesystem. Would it be possible to add an option for the client which prevents the server from overriding includes/excludes?

**Comment by grke** [comment]
Well spotted, this sounds like a sensible feature to add.

**Comment by grke** [comment]
Now in master.

**Comment by juodumas** [comment]
Great. Thank you and @ziirish.

Are you going to backport this to 1.4.x? If not, is the burp 2 client ready to use?

**Comment by grke** [comment]
Nothing will be backported to 1.4.x.

Burp 2 is very good. But you should test it yourself to make sure it works for you. New clients probably will not work with old servers, so you should have a burp 2 server too.
