### ISSUE TITLE
Feature request: include/exclude blocks in config

### ISSUE THREAD

**Issue by juodumas** [grke/burp#414]
It would be nice to have the possibility to apply different include/exclude rules to different hierarchies:

```
# Hierarchy 1
include = c:/users/me
include_ext = doc
include_ext = xls

# Hierarchy 2 (we don't want the above include_ext to apply to this hierarchy)
include = c:/app/app.exe
include = c:/app/data
exclude_regex = /bak/$
```

One way would be to use ini style categories:
```ini
[include group 1]
include = c:/users/me
include_ext = doc
include_ext = xls

[include group 2]
include = c:/app
include = c:/app/data
exclude_regex = /bak/$
```

Another way would be to implement `include_regex`. It could work on files found by `include/include_glob` directives, i.e. `include = ...` or `include_glob = ...` would be required to use `include_regex`:
```
include = c:/users/me
include = c:/app
include_regex = ^c:/users/me/.+\.(xls|doc)$|^c:/app
exclude_regex = ^c:/app/.+/bak/$
```

**Comment by grke** [comment]
It seems like you are asking for something similar to existing feature request https://github.com/grke/burp/issues/253

Are you happy to add your post as a comment on that one, and close this one?

**Comment by juodumas** [comment]
Thanks for the pointer. Moving to #253.
