### ISSUE TITLE
[BURP 2.0.36] Compile errors centos 5.x x64 

### ISSUE THREAD

**Issue by buzzzo** [grke/burp#418]
CC     src/burp-hexmap.o
src/hexmap.c: In function ‘char* bytes_to_md5str(uint8_t*)’:
src/hexmap.c:60: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘uint64_t savepathstr_with_sig_to_uint64(const char*)’:
src/hexmap.c:68: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘char* uint64_to_savepathstr(uint64_t)’:
src/hexmap.c:82: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘char* uint64_to_savepathstr_with_sig(uint64_t)’:
src/hexmap.c:89: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘char* uint64_to_savepathstr_with_sig_uint(uint64_t, uint16_t*)’:
src/hexmap.c:99: error: ‘htobe64’ was not declared in this scope
make: *** [src/burp-hexmap.o] Error 1

**Comment by grke** [comment]
Does adding this to src/burp.h help?

> #include <byteswap.h>

Put it before the last 'endif'.

**Comment by buzzzo** [comment]
Seems to NOT help:

              	#error byte order not supported
        #endif
       	#define __BYTE_ORDER    BYTE_ORDER
        #define __BIG_ENDIAN    BIG_ENDIAN
       	#define __LITTLE_ENDIAN LITTLE_ENDIAN
       	#define __PDP_ENDIAN    PDP_ENDIAN
#endif
#include <byteswap.h>
#endif

**Comment by grke** [comment]
"Ok with the help of the link provied e some sort of "hacks" (other errors in protocol2/blk.c I was able to pass all the compile phase."

What were the hacks?

**Comment by buzzzo** [comment]
Nothing special...there are some other macros not defined that cause errors
in other source file (blk.c afaik).
Simply implementing them in the patch given before do the tricks.

I've not yet tested at runtime the build.

On Tue, Apr 5, 2016 at 11:29 PM, grke <notifications@github.com> wrote:

> "Ok with the help of the link provied e some sort of "hacks" (other errors
> in protocol2/blk.c I was able to pass all the compile phase."
>
> What were the hacks?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grke/burp/issues/418#issuecomment-205991155>
>



-- 
Got problems with Windows? - ReBooT
Got problems with Linux? - Be RooT

**Comment by grke** [comment]
What was the patch?

**Comment by buzzzo** [comment]
https://answers.launchpad.net/downtimed/+question/141115

Mainly:

+ #include <sys/param.h>
+ #ifdef _BSD
+ #include <sys/endian.h>
+ #elif defined(__linux__)
+ #include <byteswap.h>
+ # if __BYTE_ORDER == __LITTLE_ENDIAN
+ # ifndef htobe64
+ # define htobe64(x) bswap_64 (x)
+ # endif
+ # ifndef be64toh
+ # define be64toh(x) bswap_64 (x)
+ # endif
+ # else
+ # ifndef htobe64
+ # define htobe64(x) (x)
+ # endif
+ # ifndef be64toh
+ # define be64toh(x) (x)
+ # endif
+ # endif
+ #endif


On Wed, Apr 6, 2016 at 10:17 AM, grke <notifications@github.com> wrote:

> What was the patch?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grke/burp/issues/418#issuecomment-206211004>
>



-- 
Got problems with Windows? - ReBooT
Got problems with Linux? - Be RooT

**Comment by grke** [comment]
You could try running the tests that come with burp:

Change to the 'test' directory of the source, then run 'make test'.

If that passes everything OK, run 'make clean'.
Then go back to the top of the source, and run this:

./configure && make runner && ./runner

If everything passes OK, then you should be fine.
Otherwise, there are things to fix.

**Comment by buzzzo** [comment]
Naturally running test will give the usual errors:

src/hexmap.c: In function ‘char* bytes_to_md5str(uint8_t*)’:
src/hexmap.c:60: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘uint64_t savepathstr_with_sig_to_uint64(const
char*)’:
src/hexmap.c:68: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘char* uint64_to_savepathstr(uint64_t)’:
src/hexmap.c:82: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘char* uint64_to_savepathstr_with_sig(uint64_t)’:
src/hexmap.c:89: error: ‘htobe64’ was not declared in this scope
src/hexmap.c: In function ‘char*
uint64_to_savepathstr_with_sig_uint(uint64_t, uint16_t*)’:
src/hexmap.c:99: error: ‘htobe64’ was not declared in this scope
make[1]: *** [src/burp-hexmap.o] Error 1
make[1]: Leaving directory `/usr/src/burp/burp-2.0.36/test/build'

On Wed, Apr 6, 2016 at 3:03 PM, grke <notifications@github.com> wrote:

> You could try running the tests that come with burp:
>
> Change to the 'test' directory of the source, then run 'make test'.
>
> If that passes everything OK, run 'make clean'.
> Then go back to the top of the source, and run this:
>
> ./configure && make runner && ./runner
>
> If everything passes OK, then you should be fine.
> Otherwise, there are things to fix.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grke/burp/issues/418#issuecomment-206360050>
>



-- 
Got problems with Windows? - ReBooT
Got problems with Linux? - Be RooT

**Comment by grke** [comment]
Naturally, I meant for you to try after applying all the patches that you figured out.

**Comment by buzzzo** [comment]
Sorry then... I don't understand what do you mean.

On Wed, Apr 6, 2016 at 10:16 PM, grke <notifications@github.com> wrote:

> Naturally, I meant for you to try after applying all the patches that you
> figured out.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grke/burp/issues/418#issuecomment-206541027>
>



-- 
Got problems with Windows? - ReBooT
Got problems with Linux? - Be RooT

**Comment by grke** [comment]
You said you were able to compile burp by applying some changes.

You said that you have not tested this build at runtime.

If you are able to build burp, you can also run the burp tests that exist in the "test" and "utest" directories to find out if there any obvious problems with your build.

**Comment by buzzzo** [comment]
I will do it

Thx
Il 07/apr/2016 11:13, "grke" <notifications@github.com> ha scritto:

**Comment by grke** [comment]
Did it work?
I will close this issue soon, as it has been more than a month.

**Comment by yopito** [comment]
found how to get fix for RHEL5 and CentOS5. see #431
