### ISSUE TITLE
burp 2 build on old RHEL5 platform : integrate patchs ?

### ISSUE THREAD

**Issue by yopito** [grke/burp#431]
Hello, I was able to build and package burp 2.0.38 on RHEL5 platforms, both i386 and x86_64 architectures (see my email on burp-users ML).

I had to patch burp 2.0.38 sources in order to support the old glibc 2.5 and gcc 4.2.1 / 32bit.

If your interrested about it and perhaps merge these patch into burp source code repo, please see these patchs:
* https://github.com/yopito/fedora-epel-pkg/blob/el5/burp2/SOURCES/define-htobe64.glibc.prior.2.9.patch
* https://github.com/yopito/fedora-epel-pkg/blob/el5/burp2/SOURCES/gcc.el5-i386-unsigned-long-long.patch

regards - Pierre

**Comment by grke** [comment]
Thanks a lot, I will try these. :)

**Comment by grke** [comment]
Now merged to master.
