### ISSUE TITLE
burp monitor does not use localtime

### ISSUE THREAD

**Issue by yopito** [grke/burp#435]
hello,
I'm UTC+2 on my CentOS  7 server, but burp monitor does not use localtime on its display:
```
# date
Sun Jun  5 12:08:46 CEST 2016

# burp -a S
 burp status                                                2016-06-05 10:08:47

   client1          idle  last backup: 0000143 2016-06-04 21:09:57
   client2          idle  last backup: 0000164 2016-06-05 07:01:02
   client3          idle  last backup: 0000062 2016-05-23 18:58:02
   client4          idle  last backup: 0000005 2015-04-30 10:09:27
   client5          idle  last backup: 0000053 2016-06-04 19:17:03

```

**Comment by yopito** [comment]
happened for a while with burp 2.x. Output above is with 2.0.40

**Comment by grke** [comment]
Are you talking about the top right hand corner?
Are the backup times OK?

**Comment by yopito** [comment]
yes, datetime at top right is wrong ("burp status"). 
backup times of clients are correct (folder names).

**Comment by grke** [comment]
src/client/monitor/status_client_ncurses.c::screen_header()

**Comment by grke** [comment]
There is a patch for this in master now.
