### ISSUE TITLE
Burp cannot rename finishing to current because current is not empty in second backup.

### ISSUE THREAD

**Issue by kdar** [grke/burp#436]
On the client side, I get this error:

```2016-06-05 11:54:49: burp[79576] main socket: unexpected command in asfd_simple_loop(), called from maybe_check_timer(): e:Now finalising previous backup of client. Please try again later.```

On the server side, I get this error:

```
2016-06-05 12:00:36: burp[4174] End phase4 (sparse generation)
2016-06-05 12:00:36: burp[4174] Prior backup completed OK.
2016-06-05 12:00:36: burp[4174] could not rename '/mnt/pool/backup/global/clients/kdar/finishing' to '/mnt/pool/backup/global/clients/kdar/current': Directory not empty
2016-06-05 12:00:36: burp[4174] exit child
```

Here is the directory structure:
~~~ sh
ls -l /mnt/pool/backup/global/clients/kdar/
total 28
drwxr-xr-x 3 root root  4096 Jun  1 10:24 0000001 2016-06-01 04:23:20
drwxr-xr-x 3 root root  4096 Jun  2 01:37 0000002 2016-06-02 00:41:03
lrwxrwxrwx 1 root root    27 Jun  1 04:23 current -> 0000001 2016-06-01 04:23:20
-rw-r--r-- 1 root root 19927 Jun  1 10:24 dfiles
lrwxrwxrwx 1 root root    27 Jun  2 00:41 finishing -> 0000002 2016-06-02 00:41:03
~~~

The server is running on Debian 8 x64 using the EXT4 FS.

**Comment by grke** [comment]
It is supposed to overwrite the 'current' symlink.
You can probably fix it by removing 'current' by hand, and moving 'finishing':

rm current
mv finishing current

I don't have any unit tests for this step, so I will leave this issue open until I do.

**Comment by grke** [comment]
I can't see any problem in the code.

When I write a test program to overwrite a symlink in the same manner, all is fine.

This step happens at the end of every backup.
Nobody else has reported this issue.

I do not know what the problem is.

Here is my test program:
{code}
#include <stdio.h>
#include <errno.h>
#include <string.h>

int main(int argc, char *argv[])
{
        if(argc!=3)
        {
                printf("not enough args\n");
                return 1;
        }
        if(rename(argv[1], argv[2]))
        {
                printf("error: %s\n", strerror(errno));
                return 1;
        }
        printf("ok\n");
        return 0;
}
{code}

Put in a file called test.c, compile it like this: 'gcc -o test test.c'.
Make two symlinks:
ln -s a x
ln -s b y
Run the test code:
./test x y
It should say 'ok'.
Have a look at what you have:
ls -l
You should have a symlink called 'y', pointing at 'a'.

**Comment by kdar** [comment]
That test case works fine, the issue is there is something special in burp's backup directories that won't allow me to move or rename them. This is probably not an issue with burp and more with my OS/FS or something. If I use your test case to rename symlinks to burp backup directories, I get the "Directory not empty" error.

I'll have to investigate further to figure out what's going on.

**Comment by kdar** [comment]
I failed to mention that this is on fuse mhddfs. There is something about this that is disallowing me to call rename() when the destination is a directory (or symlink to a directory) that is not empty.

I'll close this for now but if you have any suggestions then let me know. Still researching to figure out a solution. Thank you for your help!

**Comment by kdar** [comment]
Adding "hard_remove" as an option to the fuse file system fixes this issue. Though, I couldn't find any .fuse_hidden* files that were being kept in the burp folders to make this an issue. Not sure if burp is holding files open in the directories of the symlinks before it tries to rename them, so it fails. But, this solution works for now.

**Comment by grke** [comment]
Hello,
Both the directories that 'finishing' and 'current' point to will have a bunch of stuff in them at the time that the symlink is moved, by design.
