### ISSUE TITLE
narrowing conversion in conf.c:567 when building from src on armv5

### ISSUE THREAD

**Issue by hrehfeld** [grke/burp#439]
I'm installing on archlinux armv5 from AUR:

    g++   -c  -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -fno-exceptions -fno-rtti  -I. -I..  -march=armv5te -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fno-strict-aliasing -fno-exceptions -fno-rtti  conf.c
    conf.c:567:1: error: narrowing conversion of '2240043254u' from 'unsigned int' to 'long int' inside { } [-Wnarrowing]
     };
     ^
    make[1]: *** [Makefile:207: conf.o] Error 1
    make[1]: Leaving directory '/tmp/packerbuild-1001/burp-backup/burp-backup/src/burp-1.4.40/src'
    
    
      ====== Error in /tmp/packerbuild-1001/burp-backup/burp-backup/src/burp-1.4.40/src ======
    
    
    ==>Entering directory /tmp/packerbuild-1001/burp-backup/burp-backup/src/burp-1.4.40/manpages
    make[1]: Entering directory '/tmp/packerbuild-1001/burp-backup/burp-backup/src/burp-1.4.40/manpages'
    make[1]: Nothing to be done for 'all'.
    make[1]: Leaving directory '/tmp/packerbuild-1001/burp-backup/burp-backup/src/burp-1.4.40/manpages'
    ==> Entering fakeroot environment...
    ==> Starting package()...
    ./autoconf/mkinstalldirs /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//usr/bin
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//usr/bin
    ./autoconf/mkinstalldirs /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp
    ./autoconf/mkinstalldirs /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/CA-client
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/CA-client
    ./autoconf/mkinstalldirs /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//run
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//run
    ./autoconf/mkinstalldirs /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//var/spool/burp
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//var/spool/burp
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/clientconfdir
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/clientconfdir/incexc
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/autoupgrade/client
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/autoupgrade/server
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/autoupgrade/server/win32
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/autoupgrade/server/win32/1.4.40
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/autoupgrade/server/win64
    mkdir -p -- /tmp/packerbuild-1001/burp-backup/burp-backup/pkg/burp-backup//etc/burp/autoupgrade/server/win64/1.4.40
    make[1]: Entering directory '/tmp/packerbuild-1001/burp-backup/burp-backup/src/burp-1.4.40/src'
    g++   -c  -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -fno-exceptions -fno-rtti  -I. -I..  -march=armv5te -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fno-strict-aliasing -fno-exceptions -fno-rtti  conf.c
    conf.c:567:1: error: narrowing conversion of '2240043254u' from 'unsigned int' to 'long int' inside { } [-Wnarrowing]
     };
     ^
    make[1]: *** [Makefile:207: conf.o] Error 1
    make[1]: Leaving directory '/tmp/packerbuild-1001/burp-backup/burp-backup/src/burp-1.4.40/src'

**Comment by hrehfeld** [comment]
2240043254 = 0x858458F6

so it should be here: https://github.com/grke/burp/blob/1.4-master/src/conf.c#L563

Why is it interpreting it as unsigned though? In C++ a hex literal can be unsigned: http://en.cppreference.com/w/cpp/language/integer_literal

Putting 

    int(0x000000)

around all hex literals enables to compile the file

**Comment by grke** [comment]
Hello,

Thanks for your report, I appreciate it.
I am not making any changes to 1.4.x any more.
Do you know if the problem still exists in master?

**Comment by hrehfeld** [comment]
master (AUR: burp-backup-git) seems to build correctly, however there are a bunch of warnings like this:

    src/hexmap.c:59:36: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         snprintf(str, sizeof(str), "%016"PRIx64"%016"PRIx64,

**Comment by hrehfeld** [comment]
Can you reflect in the documentation/website that 1.4 is unmaintained? Also, I assume, that 2.0 is stable? I was specifically not trying 2.0 because the website said it was early in dev.

**Comment by ziirish** [comment]
Hello,

I won't say 1.4.x is unmaintained. The fact is most efforts are now on the 2.0.x branch.
So I am pretty sure that if this is a critical problem for you, one may submit a patch against the 1.4.x branch and Graham would accept it.

But I may be wrong here ;-)

**Comment by grke** [comment]
The reason that I don't want to add anything to 1.4-master is that there are very few automatic tests for it, so I cannot be sure that I am not breaking anything.

Yes, I need to update the website to be less alarmist about burp-2.
It is actually protocol 2, rather than protocol 1, that is very new.
Protocol 1 is very good in burp 2.
This needs to be made clearer on the website.

If you are using burp-2, make sure you put 'protocol=1' in your burp-server.conf, to force it to protocol 1.
I have not labelled 'burp-2.0.x' as 'stable', because I release a new version every month.
However, the reality is that it is much better than 1.4.x, and has much more automatic testing.

**Comment by grke** [comment]
I have now updated the website with information on protocol 1 and 2 that I hope makes things clearer.

**Comment by grke** [comment]
I use arch, but I do not see any C++11 warnings.
What do I need to do to see them?

**Comment by grke** [comment]
Ah, I spoke too soon. I updated arch recently, and now I get the warnings.

**Comment by grke** [comment]
The C++11 warnings are now fixed in master.

**Comment by hrehfeld** [comment]
Awesome, thanks a bunch!

**Comment by bsdfox** [comment]
For anyone else who might encounter this but isn't ready to step up to burp-2, I was able to get 1.4.40 to build on arch armv5 with gcc 6.1.1 by editing src/Makefile and appending -Wno-narrowing to the CPPFLAGS variable. I also added it to CFLAGS but I don't believe this is required.
-Wno-narrowing

**Comment by hrehfeld** [comment]
(I think my suggestion above to fix the type in the code should be preferred to disabling the warning)

**Comment by grke** [comment]
The proper fix is in the code in 2.0.x.
