### ISSUE TITLE
Fractional Retention Settings?

### ISSUE THREAD

**Issue by Panaetius** [grke/burp#442]
As far as I understand the Retention documentation, the following is not really possible with the current Retention/keep settings:

Keep an hourly backup for 3 days
Keep a daily backup for 4 weeks
Keep a monthly backup for 6 months

Since the second line, "daily" is not a multiple of the first line, 3 days.

or with keep Settings, it'd have to be:
keep = 72
keep = 0.33333
keep = 28
keep = 6

and as far as I understand it, keep has to be an integer. Or did I read the docs wrong?

How could this use-case be done with burp?

**Comment by grke** [comment]
Hello,
No, you can't do that

**Comment by grke** [comment]
No, you can't do that with burp. Yes, the keep setting has to be an integer.

**Comment by Panaetius** [comment]
Is there some other way I could go about this? 

What about backing up twice (with different client names), once hourly with keep = 72, once daily with keep = 1 / 30 / 6. I'm not sure if this is currently possible though.

And would deduplication help deal with the increased disk-space usage?
