### ISSUE TITLE
2 remote servers on 2 sites

### ISSUE THREAD

**Issue by phoorms** [grke/burp#447]
Is it possible to configure a client with two different backup servers (on 2 remote sites)?
if one server fails, there is a valid back up
I don't know if is already possible ?

**Comment by grke** [comment]
Hello,

Yes it is possible.

For example, you could set up the client with two different /etc/burp directories and burp.conf files, and have independent backups to the two servers.

Or, you could set up something like rsync to copy the backed up files from server1 to server2. The client would then only back up to server1, and then a separate process on server2 (or a post-backup script) would sync the storage directory to server2.

If you need more help, please join the burp-users mailing list and ask your question there. More people will respond to you with different ideas on the mailing list than here.
