### ISSUE TITLE
chuser_and_or_chgrp not working in 2.0.44?

### ISSUE THREAD

**Issue by grke** [grke/burp#452]
pbrideau on the mailing list says chuser_and_or_chgrp is not working in 2.0.44.

Investigate. If it is not working, fix it and think about reverting the recent change to the debian init script, which may not be needed.

**Comment by kronos-pbrideau** [comment]
I've tried to compile every version to find where it was first introduced...
This bug seems present at least from 2.0.30, which is the last I could build with only small modification of yopito spec file.  From 2.0.28, I have problem with

**Comment by grke** [comment]
By the power of code coverage...

http://burp.grke.org/coverage/2.0.28/src/handy.c.gcov.html
http://burp.grke.org/coverage/2.0.30/src/handy.c.gcov.html

You can see that between 2.0.28 and 2.0.30, which is when the automake/autoconf system got rewritten, the chuser/chgrp code is no longer compiled.
This is the problem.

**Comment by grke** [comment]
Should be fixed in master now.
