### ISSUE TITLE
Fuse interface to backup

### ISSUE THREAD

**Issue by marcin-github** [grke/burp#453]
Hi!
This is request for feature.
Access to individual files in backup mae with protocol=1 was easy. I could run e.g. antyvirus over data. With backup made using protocol=2 it's not possible.

**Comment by grke** [comment]
Hello,

Yes, it is not possible with protocol 2, due to the inherent design of protocol 2.

Somebody else made a fuse module a while ago: https://github.com/ZungBang/burpfs

I don't know if anybody uses  it, or if it still works.
