### ISSUE TITLE
readdir_r is deprecated

### ISSUE THREAD

**Issue by rubenk** [grke/burp#458]
I'm seeing this on Fedora with glibc 2.24:
```
src/fsops.c:224:6: warning: 'readdir_r' is deprecated [-Wdeprecated-declarations]
                if(readdir_r(dirp, entry, &result) || !result)
                   ^
/usr/include/dirent.h:183:12: note: 'readdir_r' has been explicitly marked deprecated here
extern int readdir_r (DIR *__restrict __dirp,
           ^
src/fsops.c:366:10: warning: 'readdir_r' is deprecated [-Wdeprecated-declarations]
                status=readdir_r(directory, entry, &result);
                       ^
/usr/include/dirent.h:183:12: note: 'readdir_r' has been explicitly marked deprecated here
extern int readdir_r (DIR *__restrict __dirp,
           ^
2 warnings generated.
```

It seems as though we should switch to readdir, at least on Linux.

**Comment by grke** [comment]
I'll get around to this at some point, thanks.

**Comment by grke** [comment]
Since I sort the results of readdir_r, just replacing it with readdir is going to be inefficient.
I would have to malloc another dirent and copy the dirent from readdir to it, rather than just use the original.
I think replacing it with scandir would be better, but I would also have to implement scandir myself in src/win32/compat/compat.cpp.

**Comment by grke** [comment]
Argh, but if I use scandir, I cannot use O_NOATIME.

**Comment by rubenk** [comment]
There's also scandirat, but that's GNU-specific.

**Comment by rubenk** [comment]
For some background, see http://austingroupbugs.net/view.php?id=696

**Comment by grke** [comment]
It's OK, I have nearly sorted it out.
Linux is all working. I just have to do some magic in Windows.

**Comment by grke** [comment]
Done.
