### ISSUE TITLE
HUP from logrotate doesn't reopen the log file

### ISSUE THREAD

**Issue by kilobyte** [grke/burp#486]
Per [Debian bug #753557](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753557): when logrotate renames a log file, it sends burp a SIGHUP to have it reopen the log; this doesn't appear to work.

I have for now kludged 1.4 to use restart rather than reload.

Sorry for noise if this has already been fixed in 2.0 -- I've browsed the git log and didn't notice anything talking about the issue, it's possible I missed a fix.

**Comment by grke** [comment]
Hello,

Restart isn't good because it will interrupt all the backups.

What do you mean by 'the log'?
If you are redirecting stdout to a log, you should stop doing that.
If you are using the '-l' option, that is deprecated.
You should set 'stdout = 0' and 'syslog = 1' in the burp-server.conf.

**Comment by kilobyte** [comment]
I'm afraid I don't know much about the issue -- I don't even use burp myself, I'm just doing drive-by cleanups of unmaintained packages needing QA, and this one looked obvious.

I guess it's best to revert that change then?

**Comment by grke** [comment]
Yes please.
Thanks a lot!
I will close this issue now.
