### ISSUE TITLE
timestamp is not UTC

### ISSUE THREAD

**Issue by kronos-pbrideau** [grke/burp#493]
The monitor in burp2 (burp -a m) currently send a date in epoch format but is not set to UTC as it should be, but in the current server timezone.

```
$ ls -1 /srv/backup/testclient
0000099 2016-10-11 16:49:22
0000103 2016-10-11 19:29:06
0000106 2016-10-11 22:30:21
0000109 2016-10-12 01:31:09
0000110 2016-10-12 02:31:20
0000111 2016-10-12 03:32:07
0000112 2016-10-12 04:32:30
0000113 2016-10-12 05:33:29
0000114 2016-10-12 06:34:04
0000115 2016-10-12 07:35:04
0000116 2016-10-12 08:35:15
0000117 2016-10-12 09:35:23
0000118 2016-10-12 10:35:29
current
```

```
$ burp -a m 
[...]
c:testclient:b:118
{
    "clients": [
        {
            "name": "testclient",
            "run_status": "idle",
            "protocol": 1,
            "backups": [
                {
                    "number": 118,
                    "timestamp": 1476268529,
                    "flags": [
                        "hardlinked",
                        "deletable",
                        "current",
                        "manifest"
                    ],
                    "logs": {
                        "list": [
                            "backup",
                            "backup_stats"
                        ]
                    }
                }
            ]
        }
    ]
}
```

With this timestamp in any date command, it does not return the right date:

```
$ date -d '@1476268529'
Wed Oct 12 06:35:29 EDT 2016
```

But the backup was actually run at 10:35:29 as the filename indicate.

**Comment by ziirish** [comment]
Hello,

@grke please let me know if you apply any change since I worked-around this little issue burp-ui side (see [here](https://github.com/ziirish/burp-ui/blob/28b016ee34eebc25cd5db30a6ebfad17f6fc4180/burpui/misc/backend/burp2.py#L572-L577))

**Comment by grke** [comment]
@ziirish 
OK.

**Comment by HelterBelter** [comment]
Hello,
I assume the following is related to this bug, maybe this helps in debugging.
If it isn't let me know and I'll open another issue.

Using burp v2.0.52 compiled from the sourceforge tarball and running on a 32-bit Xubuntu 16.04. - Central time

The times shown in the monitor are 'mixed' local and UTC.

This is the 'Backup log' view for this ongoing backup (all of them correct local time):

    burp monitor 2.0.52                                     2016-11-12 14:50:37

   Client: AC-XUBU-2
   Status: running
   Backup: 0000227 2016-11-12 14:33:09
   Browse: Backup log
 * 2016-11-12 14:33:09: burp[20215] Client version: 2.0.52
   2016-11-12 14:33:09: burp[20215] Protocol: 1
   2016-11-12 14:33:09: burp[20215] Begin phase1 (file system scan)
   2016-11-12 14:34:58: burp[20215] End phase1 (file system scan)
   2016-11-12 14:34:58: burp[20215] Begin phase2 (receive file data)

And this is the 'Backup stats' view of the same:

    _burp monitor 2.0.52                                     2016-11-12 14:54:00

   Client: AC-XUBU-2
   Status: running
   Backup: 0000227 2016-11-12 14:33:09
   Browse: Backup stats

   Start time: 2016-11-12 20:33:07
     End time: 2016-11-12 20:54:00
   Time taken: 20:53
                         New   Changed Unchanged   Deleted     Total   Scanned
             Files     12603     80170      4837     19426     97610    529302
         Meta data         0        33         0         0        33        34
       Directories      2264      8047         0      3801     10311     93819
        Hard links         0        12         0         0        12      1538
        Soft links        93      2556         0        12      2649     70265
     Special files         5         0         0         4         5       227
       Grand total     14965     90818      4837     23243    110620    695185

   Percentage complete: 15%

       Bytes estimated:  44418651366  (41.37 GB)
                 Bytes:  19027105912  (17.72 GB)_
______________________________

Start time: 2016-11-12 20:33:07     &      End time: 2016-11-12 20:54:00         are in UTC.

**Comment by grke** [comment]
Should now be fixed in master, for new backups, by adding timezones to server backup timestamps.
I cannot fix old backups though.
