### ISSUE TITLE
make a single configuration file and Install /etc/init.d script from makefile

### ISSUE THREAD

**Issue by kellogs** [grke/burp#497]
I am a new user, so pardon me if this was discussed previously.

The idea of having one single executable for backup and server is brilliant. But it tool me some time understanding why there are two configuration files with duplicate entries for a single executable.

 A single executable and two configuration files is very rare in the Unix community. Most of the time, several files are nested by inclusion (think of Apache and included files or files in /etc/ subdirectories) resulting in one single file. But it is ***rare*** to have two files with duplicate entries for a single executable.

Thefore, it would be nice to make a single configuration file. 

Also, I had difficulties to understand how to start burp automatically. A script is provided in debian directory.

The configuration script should start with type = server or type = client or type = none. 

If type is none, then startup script should not run automatically on startup. The startup script provided for Debian should be installed by default by makefile. Maybe a /etc/default/burp file could present very simple default settings in case of automatic launch, like type, backup server address ...

I know this is quite hard, because with normal /etc/init.d and now system.d and various distributions this makes it complicated.

Kind regards,
Kellogs

**Comment by grke** [comment]
Hello,

Addressing question 1:
There are more options that are server-only, or client-only, than there are options common to both.
Does your idea of a single configuration file work well if your computer only acts as a burp server?
How about if your computer only acts as a burp client?

Addressing question 2:
I do not want to install init scripts automatically, as that gives me a lot of work to do in order to keep
up with all the various distributions. In my opinion, init scripts are a distribution-packaging-specific
problem.

**Comment by kellogs** [comment]
issue 1: OK
Think of OpenSSH. There is server and client executables and two seperate files. You are right.

issue 2:
Debian allows packagers to make their own startup script. But most software provide startup scripts and configuration files and this is the recommended this way to spread easily across distributions. Maybe we should have a look at how OpenSSH handle startup from makefile. I agree it could be a very tedious issue.

**Comment by grke** [comment]
There are some init scripts in the burp source.
However, I don't update them myself, and 'make install' doesn't try to install them. So, if you want them, you need to copy them into the right place by yourself.
I think this is best left to distribution packagers.
