### ISSUE TITLE
burp --fetch-certificates

### ISSUE THREAD

**Issue by kellogs** [grke/burp#499]
From the doc status text:
"If you have not connected from this client before, burp will attempt to set
up SSL certificates in the usual way first.
You may need to configure the 'server' and 'status_port' options in your
client burp.conf before it will connect."

During a backup, it is impossible to query status. So it makes sense to log on the server and query locally. But you need to install client keys on server. Is there a way to receive keys without initial backup (of backup)? Of course, you can run a first backp on server locally, for example /etc. But it is a hack.

Would it be possible to have a burp --fetch-keys command which would only fetch certificates without initial backup? It would also IMHO server large installations of burp as an admin could configure remotely clients and then decide how and when to launch backups.

Kind regards,
Kellogs

**Comment by grke** [comment]
Any query from the client to the server with a client that hasn't connected before will result in the certificate exchange.
I normally use 'burp -a l' to trigger it, which requests a list of backups.
