### ISSUE TITLE
burp interaction with OpenSSH: libssh and the like

### ISSUE THREAD

**Issue by kellogs** [grke/burp#500]
Don't get me wrong, this is a long-term feature request. Sorry if this was discussed before.

Projects like OpenSSH have a long history of security leaks and finding security leaks. This is the usual way to proceed in free software and this makes reliable and secure projects.

I am concerned that burp authentication mechanism relies on burp executable itself. If there is a leak or a security breach in burp authentication mechanism, the attacker would have access to the whole backup (unless encrypted client side). I am NOT pretending that burp has security problems, but only guessing what could happen in case of security breach.

A possible way would be to link burp to a free SSH library to provide SSH tunneling capabilities. I am thinking of libssh but there could be others projects.

It could provide SSH tunneling launched directly by burp using a configuration in burp.conf without any other software and working on all systems. First: establish an SSH tunnel. Second: connect using certificates. Therefore an attacker would need to break both.

Backupninja offers this kind of feature and relies only on ssh authentication (no libssh imho= and this is very powerful.

Kind regards,
Kellogs

**Comment by grke** [comment]
Burp already uses the free openssl library ('libssl'), which is also what openssh uses, and probably what libssh uses too.
I don't follow what the advantage is of libssh over openssl?
In both cases, you have to manage certificates/keys.
In both cases, I have to write C code to interact with the library, except with libssh I would have to
install an extra library (and cross-compile it to Windows), as it would still require openssl.

If you have established an ssh tunnel, aren't you already connected with certificates?

**Comment by grke** [comment]
If there is no response to my questions, I will close this issue within a few days.
