### ISSUE TITLE
burp server is logging to pidfile

### ISSUE THREAD

**Issue by pschiffe** [grke/burp#502]
Hello,

I'm seeing this strange issue on burp-server-1.4.40-3.fc24.x86_64, it's Fedora rpm installed in Docker image running under systemd (systemd is running inside of Docker container).

Basically, in this environment I just want from burp-server to log to stdout, so the systemd can pick up the logs. In burp-server.conf I have:
```
syslog = 0
stdout = 1
```
and there is no other log related option (no logfile, etc).

Burp server is started without any log related option as well, it's just `/usr/sbin/burp -c /etc/burp/burp-server.conf`. But unfortunately, I don't see any logs in systemd journal.

And I found out:
```
# cat /run/burp.server.pid | head -n 20
467
burp
2016-10-27 23:36:40: burp[471] exit status server
2016-10-27 23:36:40: burp[467] forked status server child pid 471
2016-10-27 23:36:40: burp[472] exit status server
2016-10-27 23:36:40: burp[467] forked status server child pid 471
2016-10-27 23:36:40: burp[467] forked status server child pid 472
list backup 10 of client 'burp-client'
basedir: /var/spool/burp/burp-client
2016-10-27 23:36:40: burp[473] exit status server
2016-10-27 23:36:40: burp[467] forked status server child pid 471
2016-10-27 23:36:40: burp[467] forked status server child pid 472
2016-10-27 23:36:40: burp[467] forked status server child pid 473
list file backup_stats of backup 10 of client 'burp-client'
found: /var/spool/burp/burp-client/0000010 2016-10-27 23:25:59
2016-10-27 23:36:40: burp[474] exit status server
2016-10-27 23:36:40: burp[467] forked status server child pid 471
2016-10-27 23:36:40: burp[467] forked status server child pid 472
2016-10-27 23:36:40: burp[467] forked status server child pid 473
2016-10-27 23:36:40: burp[467] forked status server child pid 474
```
Huh? In pidfile? Interesting. And there's way too much lines with `forked status server...`

When I configure:
```
syslog = 1
stdout = 0
```
I can see in systemd journal:
```
Oct 28 00:01:37 01d196bb379a burp[842]: forked status server child pid 897
Oct 28 00:01:37 01d196bb379a burp[897]: exit status server
Oct 28 00:01:37 01d196bb379a burp[842]: forked status server child pid 898
Oct 28 00:01:37 01d196bb379a burp[898]: exit status server
Oct 28 00:01:37 01d196bb379a burp[842]: forked status server child pid 899
Oct 28 00:01:37 01d196bb379a burp[842]: forked status server child pid 900
Oct 28 00:01:37 01d196bb379a burp[900]: exit status server
Oct 28 00:01:37 01d196bb379a burp[842]: forked status server child pid 901
Oct 28 00:01:37 01d196bb379a burp[901]: exit status server
Oct 28 00:01:37 01d196bb379a burp[842]: forked status server child pid 902
Oct 28 00:01:37 01d196bb379a burp[902]: exit status server
```
Again, way too much lines.

And in pidfile:
```
842
burp
list backup 10 of client 'burp-client'
basedir: /var/spool/burp/burp-client
list file backup_stats of backup 10 of client 'burp-client'
found: /var/spool/burp/burp-client/0000010 2016-10-27 23:25:59
list backup 9 of client 'burp-client'
basedir: /var/spool/burp/burp-client
list file backup_stats of backup 9 of client 'burp-client'
found: /var/spool/burp/burp-client/0000009 2016-10-23 21:34:17
list backup 8 of client 'burp-client'
basedir: /var/spool/burp/burp-client
list file backup_stats of backup 8 of client 'burp-client'
found: /var/spool/burp/burp-client/0000008 2016-10-23 21:30:46
```

In both cases I was listing existing backups with burp-ui.

Please, help.

**Comment by grke** [comment]
I think this already fixed by burp-2.0.48.

**Comment by pschiffe** [comment]
But 2.0.48 is only stable candidate right? I would like to use it in production..

**Comment by grke** [comment]
It is 'only' stable candidate, but it is much better than burp-1.4.40, in my opinion.
Only you can choose whether or not to use it in production.

**Comment by pschiffe** [comment]
Well, I only know what's in the documentation. When do you plan to mark burp 2.x as stable? And what about the protocol? Should I use burp 2 with protocol version 1 or is it safe enough to use burp 2 with protocol version 2? Thank you for your answers.

**Comment by grke** [comment]
I shall mark burp 2 as stable when I think it is stable.
As it is, there are a couple of bug reports that I haven't had time to investigate yet. You can see them in the issues list.
Protocol 2 is not ready yet.
Protocol 1 is good.

**Comment by pschiffe** [comment]
Great, thank you very much.
