### ISSUE TITLE
Autoupgrade broken

### ISSUE THREAD

**Issue by moenoel** [grke/burp#506]
The `else`-clause [this line](https://github.com/grke/burp/blob/1c546d8a6a6e3ae5a4be61b8f90a77abf8920f99/src/client/autoupgrade.c#L87) doesn't have a body, which causes the `snprintf` call that sets `script_name` to be skipped, which in turn makes the client use `autoupgrade_dir` as the file name for the skript.

I tested this on Solaris 10 and Debian Jessie, trying to upgrade 2.0.48 to 2.0.50.

**Comment by grke** [comment]
Great spot, thanks.

I need some better automatic testing of that file:
http://burp.grke.org/coverage/2.0.50/src/client/autoupgrade.c.gcov.html

I will try to do a quick new release to fix that (might be a day or so from now, because I have real life stuff to do today).

**Comment by grke** [comment]
Fix now in master. Are you able to test?
If you say it is OK, I will do a 2.0.52 release.

**Comment by moenoel** [comment]
Looks good. Thanks!

**Comment by grke** [comment]
OK, great. 2.0.52 is available now.
