### ISSUE TITLE
Enum name "page" already taken on Solaris 10

### ISSUE THREAD

**Issue by moenoel** [grke/burp#507]
On Solaris 10, the enum `page` is apparently already used somewhere else (didn't dig into where that is):

```
  CC     src/burp-cntr.o
In file included from src/cntr.c:13:0:
src/client/monitor/sel.h:5:1: error: 'page' defined as wrong kind of tag
gmake: *** [src/burp-cntr.o] Error 1
```

Renaming it to e.g. `page_t` fixed the issue for me.

**Comment by grke** [comment]
OK, thanks. I might be able to get this into the next quick release.

**Comment by grke** [comment]
Fix now in master.
