### ISSUE TITLE
burp 2.0.50 build fails with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by yopito** [grke/burp#508]
burp 2.0.50 is building fine under Fedora 25, but fails with Fedora rawhide (bleeding-edge).  
Both are using gcc 6.2, but F25 is using openssl 1.0.2j while Fedora rawhide has openssl 1.1.0b

Relevant lines of Fedora rawhide build log: a warning and a fails
```
[...]
  CC     src/burp-cntr.o
  CC     src/burp-conf.o
  CC     src/burp-conffile.o
src/conffile.c: In function 'extract_cn':
src/conffile.c:545:2: warning: 'ASN1_STRING_data' is deprecated [-Wdeprecated-declarations]
  return (char *)ASN1_STRING_data(d);
  ^~~~~~
In file included from /usr/include/openssl/opensslconf.h:42:0,
                 from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from src/burp.h:70,
                 from src/conffile.c:1:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
  CC     src/burp-cstat.o
```
```
[...]
 CC     src/client/protocol2/burp-rabin_read.o
  CC     src/client/protocol2/burp-restore.o
  CC     src/protocol1/burp-handy.o
src/protocol1/handy.c: In function 'enc_setup':
src/protocol1/handy.c:53:22: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}'
   calloc_w(1, sizeof(EVP_CIPHER_CTX), __func__)))
                      ^~~~~~~~~~~~~~
make: *** [Makefile:3852: src/protocol1/burp-handy.o] Error 1
make: *** Waiting for unfinished jobs....
```

full logs:

* fedora rawhide build log:  
https://copr-be.cloud.fedoraproject.org/results/yopito/burp2/fedora-rawhide-x86_64/00472996-burp2/build.log.gz
* fedora rawhide build env:  
https://copr-be.cloud.fedoraproject.org/results/yopito/burp2/fedora-rawhide-x86_64/00472996-burp2/root.log.gz

* fedora 25 build log:  
https://copr-be.cloud.fedoraproject.org/results/yopito/burp2/fedora-25-x86_64/00472996-burp2/build.log.gz
* fedora 25 build env:  
https://copr-be.cloud.fedoraproject.org/results/yopito/burp2/fedora-25-x86_64/00472996-burp2/root.log.gz

**Comment by grke** [comment]
Possible fixes now in master. Are you able to test master?

**Comment by yopito** [comment]
Just setup a fedora rawhide VM. Found another problem:
```
  CC       src/server/burp-backup_phase3.o
  CC       src/server/burp-bu_get.o
  CC       src/server/burp-ca.o
src/server/ca.c: In function ‘ca_x509_verify_crl’:
src/server/ca.c:570:31: error: dereferencing pointer to incomplete type ‘X509_REVOKED {aka struct x509_revoked_st}’
   if(!ASN1_INTEGER_cmp(revoked->serialNumber, X509_get_serialNumber(peer_cert)))
                               ^~
make: *** [Makefile:4015: src/server/burp-ca.o] Error 1
```
I will attempt to write a patch the same way you did for others.

**Comment by yopito** [comment]
sorry, forgto to mention these ones too:
```
  CC       src/burp-conf.o
  CC       src/burp-conffile.o
src/conffile.c: In function ‘extract_cn’:
src/conffile.c:550:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
   return (char *)ASN1_STRING_data(d);
   ^~~~~~
In file included from /usr/include/openssl/opensslconf.h:42:0,
                 from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from src/burp.h:70,
                 from src/conffile.c:1:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
  CC       src/burp-cstat.o
  CC       src/burp-forkchild.o
```

**Comment by grke** [comment]
My previous patch didn't work for OSX, so I just pushed a different attempt. Currently waiting on Travis.

**Comment by grke** [comment]
The ASN1_STRING_data thing should be OK in the most recent patch I pushed.
I have another one for the X509_REVOKED thing running through my local CI and I'll push it up in about 90 minutes if it passes.

**Comment by grke** [comment]
If you want to try it, get master now, and apply this patch:
```
--- a/src/server/ca.c
+++ b/src/server/ca.c
@@ -567,7 +567,13 @@ int ca_x509_verify_crl(struct conf **confs,
        {
                revoked=(X509_REVOKED *)
                        sk_X509_REVOKED_value(X509_CRL_get_REVOKED(crl), i);
-               if(!ASN1_INTEGER_cmp(revoked->serialNumber, X509_get_serialNumber(peer_cert)))
+               if(!ASN1_INTEGER_cmp(
+#if OPENSSL_VERSION_NUMBER >= 0x1010000fL
+                       X509_REVOKED_get0_serialNumber(revoked),
+#else
+                       revoked->serialNumber,
+#endif
+                       X509_get_serialNumber(peer_cert)))
                {
                        serial=X509_get_serialNumber(peer_cert);
                        bnser=ASN1_INTEGER_to_BN(serial, NULL);
```

**Comment by yopito** [comment]
I've still have build warning on ASN1_STRING_data stuff, but no git updates available yet.

Your above patch for `src/server/ca.c` is fine ! build is now complete under Fedora rawhide / openssl 1.1.0.   
Basic runtime test is fine too: was able to backup my Fedora rawhide system on a 2.0.50 burp server.

**Comment by grke** [comment]
Revoke patch for ca.c now in master.
Do you still have ASN1_STRING_data warnings?

**Comment by yopito** [comment]
git updated to your commit 342fe1c844e17f040de98bbe9cfc45271bf10fbd : no more errors, no more warnings.  
I will try in the next hours to build master branch on older platforms like CentOS 7 and VoidLinux (libressl instead of openssl) to ensure no regression happens.

**Comment by yopito** [comment]
building from master under CentOS7 (openssl 1.0.1e) is fine.  
Some troubles under VoidLinux (libressl), under further investigation.

**Comment by grke** [comment]
OK, I am closing this issue because it seems to me that it is fixed.
I have never tried to get burp to work with libressl, so that is currently not an issue to me.
However, you are welcome to add a feature request if it is important to you.
Thanks for the report and testing!

**Comment by yopito** [comment]
OK. Regarding libressl: VoidLinux packaging was working out of the box until now ;)

**Comment by grke** [comment]
OK, so what is the error?

**Comment by yopito** [comment]
It's odd: at this point, libressl 2.4.3, 2.4.4 and even devel version 2.5.0 do not define "`X509_REVOKED_get0_serialNumber`" nor "`ASN1_STRING_get0_data`".

Looks like libressl does not implement (yet) some new interfaces of OpenSSL 1.1.0, while defining OPENSSL_VERSION_NUMBER as `0x20000000L` ... 

Have to figure out how to deal with it, but it's not a burp problem strictly speaking I guess.

**Comment by grke** [comment]
I think I just have to check for the existence of LIBRESSL_VERSION_NUMBER.
Patch coming up.

**Comment by yopito** [comment]
sorry for late reply.
Thanks for this good patch: burp 2.0.52 is building like a charm against libressl 2.4.4 .
