### ISSUE TITLE
 burp stable (and old-stable) fails to build with OpenSSL 1.1.0 in debian

### ISSUE THREAD

**Issue by kalos** [grke/burp#509]
This issue is similar to https://github.com/grke/burp/issues/508

The new debian stable release (stretch) will use openssl 1.1.0, and this break the build of burp 1.4.40 and 1.3.38.
Refer: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828255

I think is important to maintain compatibility with 1.4.40 in debian, until burp2 become new stable.

Do you think to port burp 1.4.40 to openssl 1.1.0?

If you consider burp2 sufficiently stable, another option is to make burp2 debian package.

Currently burp in debian is orphaned, I'm thinking of adopting it and I would appreciate hearing your opinion on this.

Thank you!

**Comment by grke** [comment]
Hello,

Thanks a lot for considering taking over burp in debian, I appreciate it.

Burp-2.0.x is very close to me labelling it 'stable'.
The last thing that I have done is to make it work with openssl-1.1.0.

I don't think you should waste your time on burp-1.4.40.
I think that you should think about putting the upcoming burp-2.0.x release in Debian instead, as
it is vastly improved over burp-1.4.40.

**Comment by kalos** [comment]
Perfect.

I start to package burp-2.0.52 for debian, with openssl 1.1.0.

Thank you so much.

**Comment by christmart** [comment]
I backported the openssl 1.1 patches of burp-2.0 to burp-1.4 and did an NMU upload for debian. It just entered testing.
