### ISSUE TITLE
2.0.52 "burp -c /etc/burp/burp-server.conf -a s" not work

### ISSUE THREAD

**Issue by imweijh** [grke/burp#518]
2.0.52 "burp -c /etc/burp/burp-server.conf -a s" not work

/var/log/messages say:
burp[18539]: Could not get lockfile.
burp[18539]: Another process is probably running,

Installed on centos 6.8 x64 use repo  https://copr.fedorainfracloud.org/coprs/yopito/burp2/repo/epel-6/yopito-burp2-epel-6.repo

**Comment by grke** [comment]
Hello,
The status monitor works differently in burp 2.

http://burp.grke.org/docs/monitor.html

It now connects as a client over ssl, so it uses the client burp.conf.

Try simply:
burp -a s
