### ISSUE TITLE
I can't see all my clients with a "burp -a S"

### ISSUE THREAD

**Issue by Spheerys** [grke/burp#520]
I have a burp server with 3 clients : 
- burp-ui : the local client used for burp-ui on the server
- 2 other distant clients which are made backup successfully on the server

But a `burp -a S` only show me the local client : 
```
~  burp -a S
 burp status                                                2016-12-09 21:20:10
   burp-ui                     idle  last backup: 0000002 2016-12-09 19:17:38

```
Obviously, I can't see my distant clients with burp-ui.
However, on the two other clients, I can see ma several backups with a `burp -a l`

What did I miss ?

**Comment by pablodav** [comment]
You missed to add burp-ui as restore_client on burp-server.conf

**Comment by Spheerys** [comment]
Damned ! It was this !
Thanks again !
