### ISSUE TITLE
Metadata restore wipes security capabilities

### ISSUE THREAD

**Issue by mwbrown** [grke/burp#522]
In both 1.4.40 and 2.0.52, there is an issue on Linux when restoring metadata (only tested on protocol 1):

https://github.com/grke/burp/blob/master/src/client/protocol1/restore.c#L187

Calling attribs_set ends up calling chown() which will clear the security attributes of a file. For instance, on a system where /usr/bin/ping uses security capabilities instead of setuid:

    user@host ~ % getcap /usr/bin/ping
    /usr/bin/ping = cap_net_raw+ep
    user@host ~ %

After backing up and restoring the same file, it reports that metadata was found and written, however getcap returns no capabilities, as chown() has cleared them. Other xattrs are safe because they are not cleared automatically.

I verified that commenting out attribs_set inside restore_metadata keeps the capabilities as expected.

EDIT:
For what it is worth, it seems the extra attribs_set call is done as a precaution. Is it necessary to do this after setting attributes? It would seem as though attributes have no risk of changing the user/group/mode of the file.

**Comment by grke** [comment]
Hello,

Thanks for the report.
attribs_set will also reset atime/ctime/mtime, not just user/group/mode.
Does setting the security attributes change atime/ctime/mtime?

**Comment by mwbrown** [comment]
From my testing on a file system with relatime set, it looks like only the
ctime is updated when running setcap (as expected, since that changes
metadata).

**Comment by grke** [comment]
Probably want to call set_file_times() there instead of attribs_set(). I will try it soon.

**Comment by grke** [comment]
Fixed in master.

**Comment by mwbrown** [comment]
I noticed the attribs_set code in question also exists in protocol2, should that be changed as well?

For reference:
https://github.com/grke/burp/blob/master/src/client/protocol2/restore.c#L144

**Comment by grke** [comment]
Haha, good point. Re-opening.
I left it because I forgot that I had implemented metadata in protocol2.

**Comment by grke** [comment]
Now done. Thanks for pointing it out.
