### ISSUE TITLE
Duplicate files in Backups

### ISSUE THREAD

**Issue by mhutter** [grke/burp#526]
I recently have observed duplicated files in our backups:

    root@server:~# burp -a L -r /path/ -b 0000123
    2016-12-27 15:29:42: burp[29424] auth ok
    2016-12-27 15:29:42: burp[29424] Server version: 2.0.52
    2016-12-27 15:29:42: burp[29424] nocsr ok
    2016-12-27 15:29:42: burp[29424] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

    2016-12-27 15:29:42: burp[29424] extra_comms_begin ok:autoupgrade:incexc:orig_client:uname:counters_json:msg:csetproto:
    2016-12-27 15:29:42: burp[29424] Using protocol=1
    Backup: 0000123 2016-12-26 22:40:46 (deletable)
    With regex: /path/
    drwxr-xr-x  2     0     0    4096 2016-12-23 17:53:12 /path/bak
    -rw-r--r--  1  1005  1006    1309 2016-12-23 17:53:12 /path/bak/lvo-plugin.xml.old
    -rw-r--r--  1  1005  1006   19839 2016-12-23 17:52:54 /path/bak/nexus.xml.bak
    -rw-r--r--  1  1005  1006     456 2016-12-23 17:52:54 /path/bak/security-configuration.xml.bak
    -rw-r--r--  1  1005  1006    1511 2016-12-23 17:53:02 /path/bak/security.xml~
    -rw-r--r--  1  1005  1006    1752 2016-01-17 22:43:54 /path/capabilities.xml
    -rw-r--r--  1  1005  1006    1235 2016-01-17 22:40:30 /path/logback-events.xml
    -rw-r--r--  1  1005  1006     447 2016-01-17 22:40:30 /path/logback-healthcheck.xml
    -rw-r--r--  1  1005  1006    1918 2016-01-17 22:40:30 /path/logback-nexus.xml
    -rw-r--r--  1  1005  1006     142 2016-01-17 22:40:30 /path/logback.properties
    -rw-r--r--  1  1005  1006     337 2016-12-20 15:49:17 /path/logback.xml
    -rw-r--r--  1  1005  1006     498 2016-01-17 22:43:59 /path/lvo-plugin.xml
    -rw-r--r--  1  1005  1006   22993 2016-12-26 17:00:10 /path/nexus.xml
    -rw-r--r--  1  1005  1006    1309 2016-12-23 17:53:12 /path/bak/lvo-plugin.xml.old
    -rw-r--r--  1  1005  1006   19839 2016-12-23 17:52:54 /path/bak/nexus.xml.bak
    -rw-r--r--  1  1005  1006     456 2016-12-23 17:52:54 /path/bak/security-configuration.xml.bak
    -rw-r--r--  1  1005  1006    1511 2016-12-23 17:53:02 /path/bak/security.xml~
    -rw-r--r--  1  1005  1006    1752 2016-01-17 22:43:54 /path/capabilities.xml
    -rw-r--r--  1  1005  1006    1235 2016-01-17 22:40:30 /path/logback-events.xml
    -rw-r--r--  1  1005  1006     447 2016-01-17 22:40:30 /path/logback-healthcheck.xml
    -rw-r--r--  1  1005  1006    1918 2016-01-17 22:40:30 /path/logback-nexus.xml
    -rw-r--r--  1  1005  1006     142 2016-01-17 22:40:30 /path/logback.properties
    -rw-r--r--  1  1005  1006     337 2016-12-20 15:49:17 /path/logback.xml
    -rw-r--r--  1  1005  1006     498 2016-01-17 22:43:59 /path/lvo-plugin.xml
    -rw-r--r--  1  1005  1006   22993 2016-12-26 17:00:10 /path/nexus.xml
    -rw-r--r--  1  1005  1006     456 2016-01-17 22:43:37 /path/security-configuration.xml
    -rw-r--r--  1  1005  1006     456 2016-01-17 22:43:37 /path/security-configuration.xml
    -rw-r--r--  1  1005  1006    4701 2016-01-17 22:40:30 /path/security.xml
    drwxr-xr-x  2     0     0    4096 2016-12-23 17:53:12 /path/bak
    -rw-r--r--  1  1005  1006    4701 2016-01-17 22:40:30 /path/security.xml
    2016-12-27 15:29:55: burp[29424] main socket: Peer closed SSL session
    2016-12-27 15:29:55: burp[29424] List finished ok

As you can see, some files get listed twice. Timestamp and file sizes for the duplicated files are identical.

This also affects restores:

    root@server:~# rm -rf /tmp/restore/
    root@server:~# mkdir -p /tmp/restore
    root@server:~# burp -a r -r /path/security-configuration.xml -b 0000123 -d /tmp/restore/
    2016-12-27 15:39:19: burp[31993] auth ok
    2016-12-27 15:39:19: burp[31993] Server version: 2.0.52
    2016-12-27 15:39:19: burp[31993] nocsr ok
    2016-12-27 15:39:19: burp[31993] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

    2016-12-27 15:39:19: burp[31993] extra_comms_begin ok:autoupgrade:incexc:orig_client:uname:counters_json:msg:csetproto:
    2016-12-27 15:39:19: burp[31993] Using protocol=1
    2016-12-27 15:39:19: burp[31993] doing restore 0000123:/path/security-configuration.xml
    2016-12-27 15:39:19: burp[31993] doing restore confirmed

    y2016-12-27 15:39:31: burp[31993] WARNING: Path exists: /tmp/restore/path/security-configuration.xml

     1

    --------------------------------------------------------------------------------
    Start time: 2016-12-27 15:39:19
      End time: 2016-12-27 15:40:02
    Time taken: 00:43
                                 Attempted | Expected
                       ------------------------------
     Files (encrypted):                  1 |        2
           Grand total:                  1 |        2
                       ------------------------------

                 Messages:             0
                 Warnings:             1

          Bytes estimated:           912
          Bytes attempted:             0
           Bytes received:          3109 (3.04 KB)
               Bytes sent:          1405 (1.37 KB)
    --------------------------------------------------------------------------------
    2016-12-27 15:40:02: burp[31993] restore finished
    root@server:~# echo $?
    2

The file gets restored once, and then twice (and then fails because the target already exists)

In case you were wondering:

    root@server:~# ll -a /path/
    total 76
    drwxr-xr-x  3 nexus nexus  4096 Dec 27 13:53 ./
    drwxr-xr-x 14 nexus nexus  4096 Dec 27 13:52 ../
    drwxr-xr-x  2 root  root   4096 Dec 23 17:53 bak/
    -rw-r--r--  1 nexus nexus  1752 Jan 17  2016 capabilities.xml
    -rw-r--r--  1 nexus nexus  1235 Jan 17  2016 logback-events.xml
    -rw-r--r--  1 nexus nexus   447 Jan 17  2016 logback-healthcheck.xml
    -rw-r--r--  1 nexus nexus  1918 Jan 17  2016 logback-nexus.xml
    -rw-r--r--  1 nexus nexus   142 Jan 17  2016 logback.properties
    -rw-r--r--  1 nexus nexus   337 Dec 27 13:53 logback.xml
    -rw-r--r--  1 nexus nexus   498 Jan 17  2016 lvo-plugin.xml
    -rw-r--r--  1 nexus nexus 23009 Dec 27 13:53 nexus.xml
    -rw-r--r--  1 nexus nexus   456 Jan 17  2016 security-configuration.xml
    -rw-r--r--  1 nexus nexus  4701 Jan 17  2016 security.xml

**Comment by grke** [comment]
Hello,

Thanks for reporting this.
I spotted something similar in older versions of 2.0.x, but I thought I had fixed it.

It would be useful to know about the history of this client and the server.

Is the client now on 2.0.52?
Have the server and client always been on 2.0.52?
Have you upgraded through different versions? Did they start out on 1.x.x?
Have you been using working_dir_recovery_method=resume?

Anything that you can tell me could be useful in tracking down the issue.


If you need to restore all your files, you can try the '-f' option, which will overwrite existing files.

If you want to repair your backup, you can gunzip manifest.gz in the backup, edit the duplicate lines out, and gzip it again.

**Comment by mhutter** [comment]
The client is now on 2.0.52 and has been upgraded (at least one of the affected systems is older than 2.0.52), but I don't know if there ever was a 1.x version installed - I'll try to find that out tomorrow.

What I CAN say is that the backup in question was created with 2.0.52. I also know that this happens on multiple systems, but I could not yet determine what differentiates them from the other servers...

Yup, using `-f` works as a workaround, but I'd rather not have it in my restore tests :D

**Comment by grke** [comment]
The bug that I am thinking of existed in 2.0.x before 2.0.40. It wasn't present in 1.x.x.

**Comment by grke** [comment]
Any more information?

**Comment by grke** [comment]
Closing. If you get more information, you can re-open. I will re-open if I get a report of somebody else having the same problem.
