### ISSUE TITLE
burp test (make check) failed on debian stable

### ISSUE THREAD

**Issue by kalos** [grke/burp#527]
When I run the test suite of Burp I obtain this error:

`make check`
make  runner
make[1]: Entering directory '/vagrant/burp_test'
make[1]: Leaving directory '/vagrant/burp_test'
make  check-TESTS
make[1]: Entering directory '/vagrant/burp_test'
Running suite(s): alloc
 asfd
 attribs
[...]
 server_run_action
 server_sdirs
 slist

> 95%: Checks: 324, Failures: 11, Errors: 2
> utest/test_attribs.c:16:E:Core:test_attribs_protocol1:0: (after this point) Test timeout expired
> utest/test_attribs.c:17:E:Core:test_attribs_protocol2:0: (after this point) Test timeout expired
> utest/client/test_acl.c:108:F:Core:test_acls:0: Assertion '!set_acl( NULL, path, x.write_access, META_ACCESS_ACL, NULL )' failed
> utest/client/test_extrameta.c:111:F:Core:test_extrametas:0: Assertion '!set_extrameta( NULL, path, expected, strlen(expected), NULL )' failed
> utest/client/test_find.c:133:F:Core:test_find:0: Assertion '!do_link(dst, src, NULL, NULL, 0)' failed
> utest/client/protocol2/test_rabin_read.c:87:F:Core:test_rabin_read:0: Assertion '!set_xattr( NULL, sb->path.buf, x.write, strlen(x.write), metasymbol, NULL )' failed
> utest/test_alloc.c:9:F:Core:test_restore_proto1_some_things:0: Assertion 'free_count==alloc_count' failed
> utest/client/test_xattr.c:156:F:Core:test_xattrs:0: Assertion '!set_xattr( NULL, path, x.write, strlen(x.write), metasymbol, NULL )' failed
> utest/server/protocol1/test_backup_phase4.c:141:F:Core:test_atomic_data_jiggle:0: Assertion '!do_link(tmppath, finpath, &statp, confs, 0)' failed
> utest/server/protocol1/test_bedup.c:135:F:Core:test_bedup_non_burp_simple_link:0: Assertion 'stat1.st_ino==stat2.st_ino' failed
> utest/server/protocol2/champ_chooser/test_dindex.c:242:F:Core:test_delete_unused_data_files_in_progress:0: Assertion '!delete_unused_data_files(sdirs, resume)' failed
> utest/server/protocol2/champ_chooser/test_dindex.c:242:F:Core:test_delete_unused_data_files:0: Assertion '!delete_unused_data_files(sdirs, resume)' failed
> utest/server/protocol2/champ_chooser/test_dindex.c:242:F:Core:test_delete_unused_data_files_differ:0: Assertion '!delete_unused_data_files(sdirs, resume)' failed

FAIL: runner
====================================================
1 of 1 test failed

Debian INFO:
##
Debian Release: 8.6
  APT prefers stable
  APT policy: (500, 'stable')
Architecture: amd64 (x86_64)

Kernel: Linux 3.16.0-4-amd64 (SMP w/1 CPU core)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages burp depends on:
ii  libacl1      2.2.52-2
ii  libc6        2.19-18+deb8u6
ii  libncurses5  5.9+20140913-1+b1
ii  librsync1    0.9.7-10
ii  libssl1.0.0  1.0.1t-1+deb8u5
ii  libtinfo5    5.9+20140913-1+b1
ii  zlib1g       1:1.2.8.dfsg-2+b1

Versions of packages burp recommends:
ii  openssl  1.0.1t-1+deb8u5
##

Version of check (libcheck): check-0.11.0

**Comment by grke** [comment]
Hello.

That is actually about 15 different errors.

The timeout ones are because your system is slower than the systems that I run the tests on.
You can edit utest/test_attribs.c to increase the timeout in the line 'tcase_set_timeout(tc_core, 5);'.

The ACL ones are probably because you don't have acls or xattrs enabled on the file system that you are running the tests on. Or that you don't have permission to write them. Or that your file system
doesn't support them.

It is strange that things like do_link() are not working. What file system are you using?

All the tests pass for me on debian 8.6.

**Comment by kalos** [comment]
Ooops! Sorry.

I run test in vbox on a "shared folders" (vboxsf)

I re-run test in a vbox in a standart fs (not vboxsf) and all test pass.

100%: Checks: 324, Failures: 0, Errors: 0
PASS: runner
=============
1 test passed
=============

Thanks!
