### ISSUE TITLE
[Q] Project Releases

### ISSUE THREAD

**Issue by computerfr33k** [grke/burp#528]
Hi, I was wondering if you would be willing to actually create releases for this project using GitHub instead of just creating tags. This would be very beneficial for me as I have made a docker image for this project and I am currently implementing a feature to allow a user to specify the version they want installed to be the latest stable. This could also be helpful for newcomers as they would know easily which version is the latest stable release as well since the release would have a nice green indicator next to it. I was planning on using the Github API to get the latest release and download that tarball and build & install it in the docker container. But that is currently not so easy to do since there is no way for me to determine if a tag is considered stable or not.

My docker project is here if you were interested in taking a look at it: https://github.com/computerfr33k/docker-burp-backup-server

Thanks

**Comment by grke** [comment]
Hello.

I don't understand what the difference is between tags and releases on github.
It looks to me like all the tags that I have made are the same as 'releases' on this page:
https://github.com/grke/burp/releases

What am I missing?

**Comment by computerfr33k** [comment]
Github automatically lists all tags as releases on the web UI. But unfortunately they are not listed as releases on the api since they are actually only tags. Plus, by actually creating a release you would be able to mark a tag as being pre-releases software, adding description, files, etc.

Here's the page for my releases of my docker image as an example of what the difference would look like. https://github.com/computerfr33k/docker-burp-backup-server/releases

And since I have created releases for my project, they are fetchable from the api like so: https://api.github.com/repos/computerfr33k/docker-burp-backup-server/releases

But since yours are actually only tags, the API doesn't list any releases for your project:
https://api.github.com/repos/grke/burp/releases

Hopefully I've kind of explained it in a way that shows some of the differences.

**Comment by grke** [comment]
Thanks, I think I get it now.
I will be doing a new 2.0.54 release soon (today or tomorrow), so I will try to make it work for you.
If it works, I will close this issue.

**Comment by computerfr33k** [comment]
ok, thanks! much appreciated.

**Comment by grke** [comment]
Now done.
