### ISSUE TITLE
Is protocol 2 now considered stable?

### ISSUE THREAD

**Issue by ilovezfs** [grke/burp#529]
I noticed that https://github.com/grke/burp/releases shows "2.0.54 - stable". Does that imply that protocol 2 is now considered stable, or is it still considered "experimental," as described on http://burp.grke.org/ ?

I'm asking because I'm not sure whether it's time to promote the protocol 2 development spec in the Homebrew formula to the stable spec, or if we should still leave the stable spec as 1.4.40.

**Comment by grke** [comment]
No, protocol 2 is not stable, it is still experimental.
But there are many improvements to protocol 1 in burp-2.0.54, so you should use that.
Protocol 1 is the default in burp 2.
