### ISSUE TITLE
could not mkdir .../data/cfiles: File exists

### ISSUE THREAD

**Issue by sberthelot** [grke/burp#535]
It doesn't seem very important and next backup of same server/client couple was successful but I'm reporting it for completeness :)
Maybe a concurrency issue ?

```
0000096 2017-02-13 01:00:02

/var/backup/burp/slackware1401/clients/<CLIENT>/working/log:

2017-02-13 01:00:02: burp[9428] Client version: 2.0.54
2017-02-13 01:00:02: burp[9428] Protocol: 2
2017-02-13 01:00:02: burp[9428] Begin phase1 (file system scan)
2017-02-13 01:00:10: burp[9428] End phase1 (file system scan)
2017-02-13 01:00:10: burp[9428] forked champ chooser pid 9452
2017-02-13 01:00:13: burp[9428] Connected to champ chooser.
2017-02-13 01:00:22: burp[9428] Phase 2 begin (recv backup data)
2017-02-13 01:00:22: burp[9428] could not mkdir /var/backup/burp/slackware1401/data/cfiles: File exists
2017-02-13 01:00:22: burp[9428] End backup
2017-02-13 01:00:22: burp[9428] error in backup phase 2
```

**Comment by grke** [comment]
Hello,
Thanks for reporting it.
/data/cfiles is supposed to be a directory - so if something has created a file there, then there is something wrong.
Is cfiles currently a file or a directory? If it is a file, what is in it?

The purpose of any files inside the cfiles directory is to keep track of created data files, in order to be able to clean up after interrupted backups.

**Comment by sberthelot** [comment]
Hello, thanks for your answer.
On the backup server it's currently an existing directory whose creation date is last backup period (last night, so more recent than when I received the error message)
It currently contains only one file which is another client's name (using the same dedup_group) suffixed by "tmpnam-style" characters. It's binary for 84 bytes (seems to contain 6 "qXXXX" lines with binary data).
I did not receive any notification for this particular client last night ; I checked and it was the last one to use this dedup_group.

Does the server delete then create again this directory ? Then it may explain if 2 clients are doing it at the same time why mkdir didn't succeed (just a guess).

**Comment by grke** [comment]
The information you give above is what I expect.

Yes, looking at the code, it seems possible that two processes might try to create the directory at the same time, but I shouldn't be treating that as an error.
I will make a fix for that.

**Comment by sberthelot** [comment]
OK thanks and sorry to ask again for concurrency issues :)

**Comment by grke** [comment]
There's a fix on master now.
I am glad you are reporting them, it makes burp better every time. :)
