### ISSUE TITLE
burp server thinks client is running when it's not

### ISSUE THREAD

**Issue by halmartin** [grke/burp#536]
I had issues with burp server version 1.3.48-4.1 (Debian Jessie stable) not completing backups of certain clients (all clients are running Debian Jessie). A vast majority of clients completed backups successfully, but several clients would continuously hang the burp server, preventing the backup from completing and causing the burp server to consume large amounts of CPU over several days.

Since this version is ancient, I upgraded the burp server package to version 2.0.54-1~bpo8+1 from the jessie-backports repository. The clients remain on 1.3.48-4.1 from jessie main.

I have restarted the burp server and tried to run the backup again from the clients that were crashing under burp server 1.3.48. Unfortunately, it seems there is still an issue. The burp server is showing the client in question as "running" despite there being no in progress backup from the client (or any burp process running on the client).

Burp server output:
```
 burp status                                                2017-02-15 11:37:20
   dc1-p-db02               running  last backup: 0000020 2017-02-05 18:29:33
```

When I try to invoke burp on the client dc1-p-db02, I get:
```
dc1-p-db02$ sudo burp -a b
2017-02-15 11:31:11: burp[4816] before client
2017-02-15 11:31:11: burp[4816] begin client
2017-02-15 11:31:11: burp[4816] WARNING: Client 'dc1-p-db02' version '1.3.48' does not match server version '2.0.54'. An upgrade is recommended.

2017-02-15 11:31:11: burp[4816] auth ok
2017-02-15 11:31:11: burp[4816] Server version: 2.0.54
2017-02-15 11:31:11: burp[4816] nocsr ok
2017-02-15 11:31:11: burp[4816] Client uses TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384
2017-02-15 11:31:11: burp[4816] unexpected command from server: e:Finalising previous backup of client. Please try again later.
2017-02-15 11:31:11: burp[4816] error in backup
2017-02-15 11:31:11: burp[4816] after client
```

No burp processes running on the client:
```
dc1-p-db02:~$ ps aux | grep -v grep | grep -c burp
0
```

No lingering connections from the client to the burp server:
```
dc1-p-db02:~$ sudo netstat -anp | grep -c 4971
0
```

My apologies if it's improper to open an issue on GitHub regarding this instead of a mailing list.

**Comment by pablodav** [comment]
For clients with burp2, you must have the latest 1.4.40 at least. 

You can use binaries https://github.com/grke/burp/wiki/Binary-packages

Or also use the ansible role that compiles latest stable version 2.x by default (with option to choose the version if you want). 
https://github.com/grke/burp/wiki/Automated-deploy-and-maintenance 

But you can't use 1.3.x version with latest burp 2.x

Kind regards,
Pablo.

**Comment by halmartin** [comment]
@pablodav thanks, I'll upgrade the clients to at least 1.4.40 and re-open the issue if it's still occurring.
