### ISSUE TITLE
Feature request: group quota

### ISSUE THREAD

**Issue by marcin-github** [grke/burp#540]
Hi!
I'd like to ask to add new feature: group quota. It would allow to restrict space usage for a given customer. 
I've got question about how quota works now. Is quota counted (I'm thinking about protocol=2) before or after deduplication?

**Comment by grke** [comment]
Hello,

I think that it would be difficult to implement on the dedup_groups.
You are probably better off using filesystem/user quotas.
Have each client in a dedup_group run as a different user, and set file system user quotas.

The current quota works in both protocols, during backup phase1.
It is a bug that it doesn't operate during phase2.
See https://github.com/grke/burp/issues/245

**Comment by marcin-github** [comment]
Thanks for quick answer.
XFS has quite flexible quota implementation (see project quota, it allows create quota per directory).

About my question about quota, I'll try be more verbose. Let's imagine a situation with two clients A and B.
client A:
- quota 20GB
- makes backup file with size 15GB

client B:
- quota 5GB
- do backup of the same file as client A (e.g. the same iso file downloaded from internet)

WIll client B get quota exceeded or will have backup created without warning?
I'm assuming that both clients are in the same dedup_group:)

**Comment by grke** [comment]
Hello,
Client B will get quota exceeded, for both protocols, because the quota is checked during backup phase1, and both protocols use the same phase1 code.
Phase1 is when the client scans its file system and sends it to the server.

**Comment by grke** [comment]
Hello,
Is your question answered?
Can we close this issue?

**Comment by marcin-github** [comment]
Hello,
yes .Thank you!
