### ISSUE TITLE
Post backup script is never run if backup_script_reserved_args = 0

### ISSUE THREAD

**Issue by vesch** [grke/burp#544]
Hi.

Post backup script is never run if backup_script_reserved_args = 0.
Found this in the Debian package (2.0.54) but I think master is also affected.
Look around the line 174 in client/main.c:
```
if(get_int(confs[OPT_B_SCRIPT_RESERVED_ARGS]))
{
	args[a++]=b_script_post;
	...
}
```
The command to run is set only if backup_script_reserved_args is enabled.

**Comment by grke** [comment]
Well spotted, thank you, I will fix it.

**Comment by grke** [comment]
Same for restore_script_reserved_args.

**Comment by grke** [comment]
Should now be fixed in master.
