### ISSUE TITLE
needless retransmission of hardlinked files

### ISSUE THREAD

**Issue by chrisv5179** [grke/burp#547]
> Changes in burp-2.1.4:
>  Protocol 1: When a file that is deleted on the client side was one that
>  others hardlink to, do not treat the new first entry as a new file - link
>  it in from the previous backup.

Sorry for the delay, I hadn't time to check this before.

There seems to be a tiny mistake in the code. If I take the little example of the mailing list thread "needless retransmission of hardlinked files", the first backup after deleting one of the hardlinked files seems okay. But after deleting a second instance of this file I get again a retransmission. I activated the debug code in client/protocol1/backup_phase2.c to get additional logs.

What happens is this:

Given a file /var/tmp/burp-test/dir_3/file_1 and hardlinks to this as /var/tmp/burp-test/dir_4/file_1 , /var/tmp/burp-test/dir_5/file_1 and so on, you get following manifest after first backup:

t0020t/var/tmp/burp-test/dir_3/file_1
r003DP0D IAH7 IGk G A A A BQAAA BAA KAA BYmyie BYmyu6 BYwtU7 A A J
f001F/var/tmp/burp-test/dir_3/file_1
...
r003DP0D IAH7 IGk G A A A BQAAA BAA KAA BYmyie BYmyu6 BYwtU7 A A J
L001F/var/tmp/burp-test/dir_4/file_1
L001F/var/tmp/burp-test/dir_3/file_1
...
r003DP0D IAH7 IGk G A A A BQAAA BAA KAA BYmyie BYmyu6 BYwtU7 A A J
L001F/var/tmp/burp-test/dir_5/file_1
L001F/var/tmp/burp-test/dir_3/file_1
...
r003DP0D IAH7 IGk G A A A BQAAA BAA KAA BYmyie BYmyu6 BYwtU7 A A J
L001F/var/tmp/burp-test/dir_6/file_1
L001F/var/tmp/burp-test/dir_3/file_1

After deleting /var/tmp/burp-test/dir_3/file_1 burp is correctly adding a hardlink in the current data directory. The manifest shows now:

t0020t/var/tmp/burp-test/dir_3/file_1
r003DP0D IAH7 IGk F A A A BQAAA BAA KAA BYmyie BYmyu6 BY0ROK A A J
f001F/var/tmp/burp-test/dir_4/file_1
...
r003DP0D IAH7 IGk F A A A BQAAA BAA KAA BYmyie BYmyu6 BY0ROK A A J
L001F/var/tmp/burp-test/dir_5/file_1
L001F/var/tmp/burp-test/dir_4/file_1
...
r003DP0D IAH7 IGk F A A A BQAAA BAA KAA BYmyie BYmyu6 BY0ROK A A J
L001F/var/tmp/burp-test/dir_6/file_1
L001F/var/tmp/burp-test/dir_4/file_1

Please note, that burp leaves the server side file location at dir_3, but it should point to dir_4! Both files (hardlinks indeed) are present on the server.

A subsequent backup run seems to be good at first glance, but on the server only one instance is hardlinked again: The one in dir_3, instead the one in dir_4! So, after deleting the file /var/tmp/burp-test/dir_4/file_1 on the client, burp does a retransmission of the file in dir_5:

burp[7486] Phase 1 end (file system scan)
burp[7486] Phase 2 begin (send backup data)

burp[7486] need to send whole file: /var/tmp/burp-test/dir_5/file_1

Manifest on the server shows now:

t0020t/var/tmp/burp-test/dir_5/file_1
r003DP0D IAH7 IGk E A A A BQAAA BAA KAA BYmyie BYmyu6 BY0RXl A A J
f001F/var/tmp/burp-test/dir_5/file_1
...
r003DP0D IAH7 IGk E A A A BQAAA BAA KAA BYmyie BYmyu6 BY0RXl A A J
L001F/var/tmp/burp-test/dir_6/file_1
L001F/var/tmp/burp-test/dir_5/file_1

**Comment by grke** [comment]
Hello,

OK, thanks for the good description.

Hopefully I will be able to fix it before the next release, if I get some spare time.

**Comment by grke** [comment]
Hello,

I had little spare time this month, so I haven't been able to look at this yet, and there won't be a fix in the release that I will be doing later today (2.1.6).

**Comment by grke** [comment]
Hello,

The thing that you describe doesn't actually cause the retransmission.

The actual problem is that it is only doing one pass through the previous manifest to find the previous master file. If it is already half way through the manifest when it starts looking (because it already
looked up a different master file earlier), it misses it because it needs to go back to the beginning.

I am testing a fix for both issues for 2.1.8.

**Comment by grke** [comment]
Fixes now in master.

**Comment by chrisv5179** [comment]
Sorry to reopen this issue, but there's another bug (already there or introduced by last change) that leads to same behaviour. Files are retransmitted because burp server can't find them in its repo. When a file is deleted on client having one or more hardlinks pointing to, the file on burp server is moved to the next still existing path of hardlinks. At this move, the prefix "/t" is missing in the destination path. A file /data/t/var/tmp/burp-test/dir1/file1 is moved to /data/var/tmp/burp-test/dir2/file1 instead of /data/t/var/tmp/burp-test/dir2/file1.

**Comment by grke** [comment]
OK, I will have another look soon.

**Comment by grke** [comment]
Confirmed.

**Comment by grke** [comment]
Another attempt is in master now.
Third time lucky? :)

**Comment by chrisv5179** [comment]
I can confirm that it's finally fixed now. A backup of ~20.000 files worked fine 4 consecutive days. Thank you very much.
