### ISSUE TITLE
Track backup interruptions and resumes in a machine-readable way

### ISSUE THREAD

**Issue by qm2k** [grke/burp#562]
Currently it is possible to determine if backup was interrupted and resumed by reading the log, but not via some standard API. Such API (e.g. file with resume timestamps) is needed to improve backup scheduling, f.i. restart successful but continued backups earlier.

**Comment by grke** [comment]
I think a file called 'resumed' inside the numbered backup, containing a list of timestamps for each incident of resuming for that backup.

**Comment by grke** [comment]
This is now in master.
