### ISSUE TITLE
Write timestamp when client is first acquainted

### ISSUE THREAD

**Issue by qm2k** [grke/burp#563]
E.g. on creation of client directory. It is needed to improve scheduling of initial backup (since time since last backup is unavailable in this case). Proposed mechanism is to create file `created_timestamp` in the same format as backup timestamp, but not in any backup directory and with backup index of zero.

**Comment by grke** [comment]
Sounds good. I will call the file 'created' instead, as it is nice and short.

**Comment by grke** [comment]
Ha, I changed my mind 'timestamp_created' is better, as it doesn't stick itself inside the middle of the backup list when you do an 'ls':

```
root@small:/var/spool/burp/testclient# ls -l
total 16
drwxr-xr-x 2 root root 4096 May 13 05:59 0000001 2017-05-13 05:59:10
drwxr-xr-x 2 root root 4096 May 13 05:59 0000002 2017-05-13 05:59:56
drwxr-xr-x 3 root root 4096 May 13 05:59 0000003 2017-05-13 05:59:57
lrwxrwxrwx 1 root root   27 May 13 05:59 current -> 0000003 2017-05-13 05:59:57
-rw-r--r-- 1 root root   28 May 13 05:59 timestamp_created
root@small:/var/spool/burp/testclient# cat timestamp_created 
0000000 2017-05-13 05:59:10
root@small:/var/spool/burp/testclient# 
```

**Comment by qm2k** [comment]
Another possibility is `.created `

**Comment by grke** [comment]
Good idea, I'm doing .created.

**Comment by grke** [comment]
This is now in master.
