### ISSUE TITLE
[Enhancement] Add timezone to timestamps

### ISSUE THREAD

**Issue by qm2k** [grke/burp#564]
Timestamps written by BURP may persist for a long time, typically up to a year. Currently they are written in server's local timezone, but this timezone may change due to various reasons: sysadmin preferences between UTC and local time, server migrations etc. Last but not least, backup storage volume may be shipped or mirrored to a different part of the world. Timezone information (offset from UTC) on timestamps would simplify analyzing backup data in these situations.

**Comment by trustchk** [comment]
related: #493 (timestamp is not UTC)

**Comment by grke** [comment]
I think this could solve a few problems. :)

**Comment by grke** [comment]
Done in master, ready for next release.
