### ISSUE TITLE
notify_script fails for big logs

### ISSUE THREAD

**Issue by qm2k** [grke/burp#567]
Some BURP operations create logs dozens of megabytes in uncompressed size (particularly resumed backups and restores on top of existing directory). notify_script attempts to include the full log in the email message. Not only this is rude to email service, such messages may get discarded as early as local sendmail without further notifications.

Proposed solution:

Finding out maximum message size is troublesome, as is reliable parsing of sendmail error messages. It's easier to set fixed limit on number of lines sent. In my system I inserted `tail -n 1000` after `$catcmd` and propose to do it upstream too:
```diff
@@ -69,7 +69,8 @@
   echo "$headers" && echo && echo "No log found to send in email" | $sendmail
 else
   # The normal case.
-  (echo "$headers" && echo && echo "$id" && echo && echo "$log:" && echo && ($catcmd "$log" 2>/dev/null || cat "$log")) | $sendmail
+  maximum_line_count=1000
+  (echo "$headers" && echo && echo "$id" && echo && echo "Last $maximum_line_count lines of $log:" && echo && ($catcmd "$log" 2>/dev/null || cat "$log") | tail -n "$maximum_line_count") | $sendmail
 fi
 
 exit 0
```

**Comment by grke** [comment]
Good idea, thank you.

**Comment by grke** [comment]
Now in master.
