### ISSUE TITLE
About: A single daily backup summary email feature. 

### ISSUE THREAD

**Issue by nhanvolac** [grke/burp#574]
Hi, 

I am a newbie with burp backup. And I don't know to use feature above. 

After backup successfully, or change, restore file, I received a notification email. But I don't see the daily backup summary email. 

Do I need more configuration to use this feature? 

Thank you so much.

**Comment by ziirish** [comment]
Hello,

What distribution are you using, and where do the burp packages you are using come from.
The *official* burp packages on debian ships with a *almost* ready to use crontab containing something like:

```
# SERVER
# Send a summary at 6 every morning.
# If your server is using a different config file to /etc/burp/burp-server.conf,
# change the first argument to its path.
#0 6 * * *       root    /etc/burp/send_summary /etc/burp/burp-server.conf youremail@example.com "Daily backup summary"
```

So in this case, you just have to uncomment the last line.

Anyway, you have to look for the *send_summary* file (it may not be in /etc/burp) and the add the crontab manually based on this example.

**Comment by nhanvolac** [comment]
Hi Ziirish,

Thank you for your information. 

I am using the Ubuntu 16.04 and I installed burp packages from source.
`git clone https://github.com/grke/burp.git` with version 2.0.54

Currently, I don't find any file with name "send_summary" on my server. Maybe it misses when I installed Burp. 
So where can I download "send_summary" file?

Thanks again.

**Comment by ziirish** [comment]
Did you have a look at */usr/share/burp/scripts/*?

**Comment by nhanvolac** [comment]
Maybe it is "summary_script" file in /usr/src/burp. :D

**Comment by ziirish** [comment]
yes probably.

**Comment by grke** [comment]
Thanks, ziirish. Closing.
