### ISSUE TITLE
error in readdir: Unknown error

### ISSUE THREAD

**Issue by grke** [grke/burp#585]
From the mailing list:
> The phenomenon is like this. Windows Server 2016 Standard log, running
> BuRP 2.0.54 (obviously only the last lines):
>
> ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 85632
> ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 85696
> ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 85760
> ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 85824
> ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2017-06-28
> 08:58:35: bin\burp[47604] error in readdir: Unknown error*
> ** 85882*

Also happens on recent burp-2.1.x.
Burp should be able to treat this as something to warn about, and carry on.

**Comment by 4001982248998** [comment]
It was me who reported the error in the mailinglist. The problem has since been able to be resolved by removing files with paths longer than allowed (~260 characters).

**Comment by grke** [comment]
Thanks.
Can you give me an example of a path that would cause the problem? Then I can try to reproduce exactly what you had.

**Comment by grke** [comment]
When I have time, I will have a go at reproducing this in a VM.
If I cannot reproduce it, I will close this issue

**Comment by grke** [comment]
I cannot reproduce this.

I cannot get Windows 10 to let me create a file name that is 260 characters long. I tried registry hacks and everything, to no avail.
I will close this now. If somebody is able to tell me the exact steps that I need to do to reproduce the issue, it can be reopened and I will try again.
