### ISSUE TITLE
`client_lockdir` ignored

### ISSUE THREAD

**Issue by C-Otto** [grke/burp#586]
The server setting `client_lockdir` is ignored. After a bit of debugging in version 2.0.54 (Debian Stretch) it seems the global server configuration `confs` is used to store `client_lockdir`. However, in the code only the `cconf` (client configuration?) is forwarded to the code setting up the directories. 

As far as I can see the issue is in `child.c` where both configuration sets are provided, but only `cconf` is forwarded to `run_action_server`. Inside `run_action_server` the actual directories are setup.

(I seriously dislike the choice of names - I still have no idea what `cconfs` and `asfd` are supposed to mean. What's the issue with just picking a readable name? And, while we're at it, why don't you have seperate types for `confs` and `cconfs` so that you notice you're passing on the wrong data?)

**Comment by grke** [comment]
I am usually very polite with users of my software, and am patient with questions.
However, I find your attitude unusually rude.
So much so, that I am disinclined to help you.

I have provided my software for free.
You have the choice to debug it, change it, and maybe even give patches back.
If you dislike it so seriously, just don't use it.

If you actually do want my help, I await your apology.

Thank you.

**Comment by C-Otto** [comment]
Could you please open/close issues based on the actual issue? I fear closing this without a fix (or nofix decision) would harm the project and produce duplicated work.

**Comment by ziirish** [comment]
I believe this is fixed as of c41fa7c830d6e1b970697d50bb7c1910c83b682e

**Comment by C-Otto** [comment]
Thank you, this indeed fixes the issue.
