### ISSUE TITLE
Success notification on failed backup?

### ISSUE THREAD

**Issue by grke** [grke/burp#587]
From the mailing list:

Today I have received backup success notification even though backup itself
failed. On the next client access the server run timer_script which reported
that last backup is still old, but then resumed backup as if it was
interrupted. Never observed this before, so I do not exclude hardware/OS
problems etc. In any case, here's the message:

> Subject:      backup succeeded with warnings: HP24_Full (2 warnings)
> Date:         Mon, 3 Jul 2017 08:21:01 +0000 (UTC)
>
>
> 0000004 2017-07-03 07:20:01
>
> Last 1000 lines of /mnt/burp/HP24_Full/working/log:
>
> 2017-07-03 07:20:01: burp[1453] Client version: 2.1.8
> 2017-07-03 07:20:01: burp[1453] Protocol: 1
> 2017-07-03 07:20:01: burp[1453] Client is Windows
> 2017-07-03 07:20:01: burp[1453] WARNING: Client 'HP24_Full' version '2.1.8'
does not match server version '2.0.54'. An upgrade is recommended.
> 2017-07-03 07:20:01: burp[1453] Begin phase1 (file system scan)
> 2017-07-03 07:31:35: burp[1453] End phase1 (file system scan)
> 2017-07-03 07:31:35: burp[1453] Begin phase2 (receive file data)
> 2017-07-03 07:55:56: burp[1453] WARNING: Path too long for tree - will save in
data structure instead: <redacted>
> 2017-07-03 07:56:13: burp[1453] WARNING: Path too long for tree - will save in
data structure instead: <redacted>
> 2017-07-03 08:21:01: burp[1453] End phase2 (receive file data)
> 2017-07-03 08:21:01: burp[1453] main socket: Got SSL_ERROR_SYSCALL
> 2017-07-03 08:21:01: burp[1453] main socket: SSL write problem in
asfd_do_write_ssl: 5 - 32=Broken pipe
> 2017-07-03 08:21:01: burp[1453] Backup ending - disconnect from client.
> 2017-07-03 08:21:01: burp[1453] main socket: Got SSL_ERROR_SYSCALL
> 2017-07-03 08:21:01: burp[1453] main socket: SSL write problem in
asfd_do_write_ssl: 5 - 32=Broken pipe

And here's how it looked in the log:
> Jul  3 07:20:01 burp2 burp[1453]: WARNING: Client 'HP24_Full' version
> '2.1.8' does not match server version '2.0.54'. An upgrade is recommended.
> Jul  3 07:20:01 burp2 burp[1453]: WARNING: Client 'HP24_Full' version
> '2.1.8' does not match server version '2.0.54'. An upgrade is recommended.
> Jul  3 07:20:01 burp2 burp[1453]: auth ok for: HP24_Full
> Jul  3 07:20:01 burp2 burp[1453]: Client HP24_Full does not want a
> certificate signed
> Jul  3 07:20:01 burp2 burp[1453]: SSL is using cipher:
> DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA Enc=AESGCM(256)
> Mac=AEAD
> Jul  3 07:20:01 burp2 burp[1453]: Server is using protocol=0 (auto)
> Jul  3 07:20:01 burp2 burp[1453]: Client supports being sent json
> counters.
> Jul  3 07:20:01 burp2 burp[1453]: Client has set protocol=1
> <snip unrelated timer_script messages>
> Jul  3 07:20:01 burp2 burp[1453]: Matched: --age-exceeds 31d  --lan
> Jul  3 07:20:01 burp2 burp[1453]: /opt/local/bin/timer_script.py returned:
> 0
> Jul  3 07:20:01 burp2 burp[1453]: Running backup of HP24_Full
> Jul  3 07:20:01 burp2 burp[1453]: in do_backup_server
> Jul  3 07:20:01 burp2 burp[1453]: Using librsync hash md4
> Jul  3 07:20:01 burp2 burp[1453]: Logging to /mnt/burp/HP24_Full/0000004
> 2017-07-03 07:20:01/log
> Jul  3 08:21:01 burp2 burp[1453]: main socket: Got SSL_ERROR_SYSCALL
> Jul  3 08:21:01 burp2 burp[1453]: main socket: SSL write problem in
> asfd_do_write_ssl: 5 - 32=Broken pipe
> Jul  3 08:21:01 burp2 burp[1453]: MESSAGE: Running notify script:
> HP24_Full /mnt/burp/HP24_Full /mnt/burp/HP24_Full/current log backup 2
> sendmail -t To: root Subject: %b succeeded with warnings: %c %w
> Jul  3 08:21:01 burp2 burp[1453]: /usr/share/burp/scripts/notify_script
> returned: 0
> Jul  3 08:21:01 burp2 burp[1453]: main socket: Got SSL_ERROR_SYSCALL
> Jul  3 08:21:01 burp2 burp[1453]: main socket: SSL write problem in
> asfd_do_write_ssl: 5 - 32=Broken pipe
> Jul  3 08:21:01 burp2 burp[1453]: exit child
> Jul  3 09:20:01 burp2 burp[1611]: WARNING: Client 'HP24_Full' version
> '2.1.8' does not match server version '2.0.54'. An upgrade is recommended.
> Jul  3 09:20:01 burp2 burp[1611]: WARNING: Client 'HP24_Full' version
> '2.1.8' does not match server version '2.0.54'. An upgrade is recommended.
> Jul  3 09:20:01 burp2 burp[1611]: auth ok for: HP24_Full
> Jul  3 09:20:01 burp2 burp[1611]: Client HP24_Full does not want a
> certificate signed
> Jul  3 09:20:01 burp2 burp[1611]: SSL is using cipher:
> DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA Enc=AESGCM(256)
> Mac=AEAD
> Jul  3 09:20:01 burp2 burp[1611]: Server is using protocol=0 (auto)
> Jul  3 09:20:01 burp2 burp[1611]: Client supports being sent json
> counters.
> Jul  3 09:20:01 burp2 burp[1611]: Client has set protocol=1
> Jul  3 09:20:01 burp2 burp[1611]: found old working directory:
> /mnt/burp/HP24_Full/0000004 2017-07-03 07:20:01
> Jul  3 09:20:01 burp2 burp[1611]: working_dir_recovery_method: resume
> Jul  3 09:20:01 burp2 burp[1611]: Logging to /mnt/burp/HP24_Full/0000004
> 2017-07-03 07:20:01/log
> <snip unrelated timer_script messages>
> Jul  3 09:20:01 burp2 burp[1611]: Matched: --age-exceeds 31d  --lan
> Jul  3 09:20:01 burp2 burp[1611]: /opt/local/bin/timer_script.py returned:
> 0
> Jul  3 09:20:01 burp2 burp[1611]: Running backup of HP24_Full
> Jul  3 09:20:01 burp2 burp[1611]: in do_backup_server
> Jul  3 09:20:01 burp2 burp[1611]: Using librsync hash md4
> Jul  3 09:20:01 burp2 burp[1611]: Logging to /mnt/burp/HP24_Full/0000004
> 2017-07-03 07:20:01/log
> Jul  3 09:20:47 burp2 burp[1611]: Logging to
> /mnt/burp/HP24_Full/finishing/log
> Jul  3 09:48:49 burp2 burp[1611]: Compressing /mnt/burp/HP24_Full/0000004
> 2017-07-03 07:20:01/log to /mnt/burp/HP24_Full/0000004 2017-07-03
> 07:20:01/log.gz...
> Jul  3 09:48:49 burp2 burp[1611]: exit child

Here's what backup list now show (another backup since completed successfully
because timer_script is configured to re-run interrupted backups):
> root@burp-ui:~# burp -a l -C HP24_Full
> 2017-07-03 12:12:46: burp[1419] auth ok
> 2017-07-03 12:12:46: burp[1419] Server version: 2.0.54
> 2017-07-03 12:12:46: burp[1419] nocsr ok
> 2017-07-03 12:12:46: burp[1419] SSL is using cipher:
> DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA Enc=AESGCM(256)
> Mac=AEAD
>
> 2017-07-03 12:12:46: burp[1419] extra_comms_begin
> ok:autoupgrade:incexc:orig_client:uname:counters_json:msg:csetproto:
> 2017-07-03 12:12:46: burp[1419] Switched to client HP24_Full
> 2017-07-03 12:12:46: burp[1419] Server has protocol=0 (auto)
> 2017-07-03 12:12:46: burp[1419] Using protocol=1
> Backup: 0000001 2017-04-21 10:20:04 (deletable)
> Backup: 0000002 2017-04-21 22:20:55 (deletable)
> Backup: 0000003 2017-05-31 07:20:01
> Backup: 0000004 2017-07-03 07:20:01
> Backup: 0000005 2017-07-03 11:20:01
> 2017-07-03 12:12:46: burp[1419] main socket: Peer closed SSL session
> 2017-07-03 12:12:46: burp[1419] List finished ok

Just to be sure that notifications subjects are configured correctly:
> root@burp2:~# grep '^notify' /etc/burp/burp-server.conf
> notify_success_script = /usr/share/burp/scripts/notify_script
> notify_success_arg = sendmail -t
> notify_success_arg = To: root
> notify_success_arg = Subject: %b succeeded with warnings: %c %w
> notify_success_warnings_only = 1
> notify_failure_script = /usr/share/burp/scripts/notify_script
> notify_failure_arg = sendmail -t
> notify_failure_arg = To: root
> notify_failure_arg = Subject: %b failed: %c %w

**Comment by grke** [comment]
My reply:

Hello,

For some reason, you have a new client and an old server. I never try to
make this combination work. I try to keep new servers and old clients working.

Also, you have time_script.py, which I don't know anything about so I cannot
comment on what it thinks is the last backup.

However, if you have 'working_dir_recovery_method = resume', and the timer
script is happy for the next backup request to continue, it will indeed resume
your backup.


...but I cannot currently explain about why you had a success notification.
I will add it to the github issues list so that I get around to investigating.
Thanks for all the clear details, and the config grep.
https://github.com/grke/burp/issues/587

There are some options in burp to get it to tell you what the config items
are. Maybe try running them to be 100% sure:

The first one gives global settings:
burp -c /etc/burp/burp-server.conf -t | grep notify
The second one gives child process settings for a particular client:
burp -c /etc/burp/burp-server.conf -t -C HP24_Full | grep notify

**Comment by qm2k** [comment]
Additional info:
```
root@burp2:~# burp -c /etc/burp/burp-server.conf -t | grep notify
        server_script_pre_notify: 0
       server_script_post_notify: 0
            server_script_notify: 0
           notify_success_script: /usr/share/burp/scripts/notify_script
              notify_success_arg: sendmail -t
              notify_success_arg: To: root
              notify_success_arg: Subject: %b succeeded with warnings: %c %w
    notify_success_warnings_only: 1
     notify_success_changes_only: 0
           notify_failure_script: /usr/share/burp/scripts/notify_script
              notify_failure_arg: sendmail -t
              notify_failure_arg: To: root
              notify_failure_arg: Subject: %b failed: %c %w
root@burp2:~# burp -c /etc/burp/burp-server.conf -t -C HP24_Full | grep notify
        server_script_pre_notify: 0
       server_script_post_notify: 0
            server_script_notify: 0
           notify_success_script: /usr/share/burp/scripts/notify_script
              notify_success_arg: sendmail -t
              notify_success_arg: To: root
              notify_success_arg: Subject: %b succeeded with warnings: %c %w
    notify_success_warnings_only: 1
     notify_success_changes_only: 0
           notify_failure_script: /usr/share/burp/scripts/notify_script
              notify_failure_arg: sendmail -t
              notify_failure_arg: To: root
              notify_failure_arg: Subject: %b failed: %c %w
```

**Comment by grke** [comment]
I see the bug, it is here...
src/server/backup.c:

        // Close the connection with the client, the rest of the job we can do
        // by ourselves.
        logp("Backup ending - disconnect from client.\n");
        if(asfd_flush_asio(asfd)) goto end;

I think the 'goto end' should be 'goto error'. I will fix this in master.

**Comment by grke** [comment]
The fix is now in master, closing this issue.
