### ISSUE TITLE
Encryption: Blowfish IV hard-coded and password used directly as key

### ISSUE THREAD

**Issue by Xaltonon** [grke/burp#588]
The relevant code is [here](https://github.com/grke/burp/blob/a6dd308cced31bc1bdfa79795bed9ca60a2f32a4/src/protocol1/handy.c#L38-L81).  The IV for Blowfish is hardcoded to 
`uint8_t enc_iv[]={'[', 'l', 'k', 'd', '.', '$', 'G', 0xa3, '\0'};`
rather than unique for each message.  This leaks information by making identical plaintexts produce identical ciphertexts.

The user password specified in the config file is fed directly into Blowfish as the key, rather than processed with a key-derivation function first.  This is a potential security hole.

**Comment by grke** [comment]
Hello,
Thanks for that. Do you have a suggested patch to fix it?
