### ISSUE TITLE
Create PID file before dropping privileges

### ISSUE THREAD

**Issue by melak** [grke/burp#593]
It would seem to make sense to create the PID file before dropping privileges. I don't think there's any cleanup done upon burp exiting, so there should be no hinderance there, but not having to have a burp-user-writable run directory before burp startup appears to be a good convenience.

Arguably, this could be done in the init script, though.

**Comment by grke** [comment]
Hello,
Which pid file are you talking about?

**Comment by melak** [comment]
The one created by the server, to `pidfile`

```
27248 setgroups(1, [117])               = 0
27248 getgid()                          = 0
27248 setgid(117)                       = 0
27248 getuid()                          = 0
27248 setuid(110)                       = 0
27248 mkdir("/opt/burp/var/run", 0777)  = -1 EEXIST (File exists)
27248 open("/opt/burp/var/run/burp.server.pid", O_WRONLY|O_CREAT, 0666) = 3
27248 fcntl(3, F_SETLK, {type=F_WRLCK, whence=SEEK_CUR, start=0, len=0}) = 0
27248 getpid()                          = 27248
27248 write(3, "27248\nburp\n", 11)     = 11
27248 fsync(3)                          = 0
```

**Comment by grke** [comment]
Hello,

It does try to remove the pid file on exit, but it won't log an error if it can't. And starting up again will overwrite it, so it should be OK.

**Comment by melak** [comment]
I don't question the correctness of your statement *g*, but what does this have to do with anything?

**Comment by grke** [comment]
I was confirming that your idea should work.

The change is now in master.

**Comment by grke** [comment]
Specifically, my comment was responding to what you wrote:
"I don't think there's any cleanup done upon burp exiting".
You were wrong, there is cleanup, but it doesn't matter if it fails, so I made the change anyway.
Thanks for a good idea!
