### ISSUE TITLE
Protocol2: Prune the sparse.index 

### ISSUE THREAD

**Issue by grke** [grke/burp#597]
Currently, the sparse.index file has no limit to it.
It could possibly get very big, and possibly cause the champ_chooser process to eat a lot of memory.
It also gets rewritten at the end of every backup. If it is very big, it could possibly cause backups to slow down.

This task is to make the rewrite prune older entries in the sparse.index, in order to limit its size.

Make sure that regenerating the sparse.index from scratch follows the same rules.

**Comment by grke** [comment]
Probably want to add a timestamp field to the manifest/hook chunks in the sparse index so that preference can be given to the newer one when there are two identical manifest/hook chunks.

**Comment by deajan** [comment]
As far as I understand, the pruning the sparse.index would remove old dedup blocks from the index.
It would be really cool if the prune process would be configurable (to a max sparse index size or even a max age) in order to tune the deduplication performance depending on the hardware.

**Comment by grke** [comment]
Finally got round to doing this.
It is done in master, ready for 2.3.20 release.

**Comment by deajan** [comment]
Sounds great.
I can test this on a 2TB protocol 2 backup.

Just to be sure, this does only prune the spare.index file, meaning dedup blocks from earlier backups remain even when not used anymore , right ?

**Comment by grke** [comment]
Hello,

All the backed up data still exists.

The sparse.index contains the fingerprints of special blocks that future backups use to try to select data files with which to deduplicate against.
So, pruning means that future backups may not be able to select the most accurate data files to deduplicate against. Since the sparse.index isn't aiming for 100% deduplication anyway, this shouldn't be a problem.

By the way, it is also possible to regenerate the sparse.index file by setting a big sparse_index_max and running the 'bsparse' program.

**Comment by grke** [comment]
Yes, only the sparse.index is pruned.
