### ISSUE TITLE
Per client bandwidth limit

### ISSUE THREAD

**Issue by deajan** [grke/burp#601]
A really nice feature to have:
Per client bandwidth limit, setup in clientconfdir or burp.conf on client :)

**Comment by grke** [comment]
Hello,
Have you tried the 'ratelimit' option? It is available server side and client side.

       ratelimit=[Mb/s]
              Set the network send rate limit, in Mb/s. If  this
              option  is  not given, burp will send data as fast
              as it can.

**Comment by pablodav** [comment]
I use `ratelimit` per client with sucess. 

Actually most of my clients are windows for those with per client ratelimit. and all those with ratelimit are laptops that the limit vary depending on the location they are siting. 
I use my own powershell script that sets the `ratelimit` and then executes `burp -a t` (so task scheduler executes the powershell script instead the burp process). 

I think it could be usefull to have a python script that does same thing, to dynamically change `ratelimit` so it could be multiplatform script, as there is no hurry on my side and I haven't heard the need coming from other person before I didn't work on it yet. 

If it is needed for you, maybe I can start working on it before. 

The script also could do more things if required.

**Comment by deajan** [comment]
Didn't read the entire doc... Guess you may say RTFM then :)
