### ISSUE TITLE
'burp -a m' does not work on Windows

### ISSUE THREAD

**Issue by grke** [grke/burp#607]
I am pretty sure this worked at one time.

> C:\Program Files\Burp\bin>burp -a m
> { "logline": "WARNING: Client 'winclient' version '2.0.54' does not match
> server version '2.1.18'. An upgrade is recommended." }
> { "logline": "auth ok" }
> { "logline": "Server version: 2.1.18" }
> { "logline": "nocsr ok" }
> { "logline": "SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2
> Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD" }
> { "logline": "extra_comms_begin
> ok:autoupgrade:incexc:orig_client:uname:counters_json:msg:forceproto=1:" }
> { "logline": "Server is forcing protocol 1" }
> { "logline": "in monitor" }
> { "logline": "select error in async_io: No error" }
> { "logline": "Exiting main loop" }

**Comment by vo-jo** [comment]
Just an update:
I tested with following client versions

2.0.8: option not known
2.0.10: error occurs
2.0.26: error occurs
2.0.54: error occurs
2.1.0: error occurs
2.1.18: error occurs

Tested all these client versions with server version 2.0.54 and 2.1.18. I couldn't find a working combination.

**Comment by grke** [comment]
Hello,
I guess it never worked. I must have been thinking of something else.

Meanwhile, the issue is probably something to do with this:
https://stackoverflow.com/questions/8773838/winsock2s-select-on-fd-0-stdin-fails

I don't know how to get Windows to work with this yet.

**Comment by grke** [comment]
Looks like select() on Windows treats file descriptors differently to streams, which means that I would have to special case the monitor stdin/stdout stuff for Windows all over the place.

**Comment by grke** [comment]
In master, this is fixed for Windows command prompts.
