### ISSUE TITLE
Burp 2.0.54 work on CentOS 5? 

### ISSUE THREAD

**Issue by nhanvolac** [grke/burp#608]
Hi ,

I installed burp-client 2.0.54 on CentOS (5.3 32bit).

When running the command "burp -a m" --> It not working.

![image](https://user-images.githubusercontent.com/20902182/30156283-6e1387d6-93e9-11e7-8fdf-3f809acda74d.png)

Does burp support CentOS 5?

Information:

CentOS 5.3 (32bit) - burp client: 2.0.54 (burp2-client-2.0.54-1.el5.centos)

Burp Sever: 
Version: 2.0.54

Log:

Sep  7 16:17:29 burp burp[26421]: Client **_l***_client does not want a certificate signed
Sep  7 16:17:29 burp burp[26421]: SSL is using cipher: DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
Sep  7 16:17:29 burp burp[26421]: main socket: Peer closed SSL session
Sep  7 16:17:29 burp burp[26421]: problem reading in extra_comms
Sep  7 16:17:29 burp burp[26421]: running extra comms failed on server
Sep  7 16:17:29 burp burp[26421]: main socket: SSL write problem in asfd_do_write_ssl: 1 - 0=Success
Sep  7 16:17:29 burp burp[26421]: main socket: Peer closed SSL session
Sep  7 16:17:29 burp burp[26421]: exit child

Thanks all. 

Regards,

**Comment by grke** [comment]
Hello,

Burp should work OK on centos5.
Do you have centos5 on both server and client? I cannot tell from your message.

You have a certificate/ssl problem.
Maybe have a look at the 'troubleshooting' section in the github wiki above for hints to fix certificate issues.


If you run your burp server with the 'stdout = 1' option in burp-server.conf, and run it in the foreground, like so...
burp -c /etc/burp/burp-server.conf -F
...then try your 'burp -a m' command, the server side may give you a useful message.

**Comment by nhanvolac** [comment]
Sorry for late response.

My Burp Server is Ubuntu 16.04 (64bit).

I try to install burp2-client to other OS (Ubuntu 14, 16, CenOS 6, 7..) and it works smoothy.

But on CentOS 5 (5.3 32bit) it failed.

On the client:

`[root@localhost burp]# burp -a m
{ "logline": "auth ok" }
{ "logline": "Server version: 2.0.54" }
{ "logline": "nocsr ok" }
{ "logline": "SSL is using cipher: DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
" }
{ "logline": "Certificate doesn't verify." }
{ "logline": "check cert failed" }
[root@localhost burp]# burp -a m
{ "logline": "auth ok" }
{ "logline": "Server version: 2.0.54" }
{ "logline": "nocsr ok" }
{ "logline": "SSL is using cipher: DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
" }
{ "logline": "Certificate doesn't verify." }
{ "logline": "check cert failed" }`

On the burp Server .

`Sep 12 23:30:21 burpqt burp[1681]: Connect from peer: 192.168.100.253:55751
Sep 12 23:30:21 burpqt burp[1681]: forked status server child: 16660
Sep 12 23:30:21 burpqt burp[16660]: auth ok for: 100.253_client
Sep 12 23:30:21 burpqt burp[16660]: Client 100.253_client does not want a certificate signed
Sep 12 23:30:21 burpqt burp[16660]: SSL is using cipher: DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
Sep 12 23:30:21 burpqt burp[16660]: main socket: Peer closed SSL session
Sep 12 23:30:21 burpqt burp[16660]: problem reading in extra_comms
Sep 12 23:30:21 burpqt burp[16660]: running extra comms failed on server
Sep 12 23:30:21 burpqt burp[16660]: main socket: SSL write problem in asfd_do_write_ssl: 1 - 0=Success
Sep 12 23:30:21 burpqt burp[16660]: main socket: Peer closed SSL session
Sep 12 23:30:21 burpqt burp[16660]: exit child
`
I've upgrade openssl to "OpenSSL 1.0.2e 3 Dec 2015" on client but nothing. 

When I show the result of command "burp -a m" on Centos 6 - 7, Ubuntu and Debian, I found the SSL cipher is difference with CentOS 5.

Centos 6: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH Au=RSA Enc=AESGCM(256) Mac=AEAD
Centos 5: DHE-RSA-AES256-SHA SSLv3 Kx=DH Au=RSA Enc=AES(256) Mac=SHA1

Is that a problem?

Can anybody shed some light on what this error means?

(I've opened a new topic about my issue to Ziirish for help but that also failed )

Thank you.

**Comment by grke** [comment]
Hello

Maybe your server's ubuntu openssl doesn't like your client's centos 5 openssl.
Is your client able to do TLSv1.2?

**Comment by grke** [comment]
Since version 1.4.26, burp sets the openssl SSL_OP_NO_SSLv2 and SSL_OP_NO_SSLv3 options to avoid the 'poodle' vulnerability.
This is done in burp's src/ssl.c. You could try commenting out the relevant line in src/ssl.c and recompiling on the server side, then if the centos 5 client works, you will know that this is the problem.

What version is openssl on the client?

**Comment by nhanvolac** [comment]
Hello

The version open SSL on my client is: OpenSSL 1.0.2e 

> [root@localhost burp]# openssl version
OpenSSL 1.0.2e 3 Dec 2015

> [root@localhost burp]# openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1.2

I have deleted line 154 in burp's src/ssl.c (SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2|SSL_OP_NO_SSLv3); ) and try to recompiling burp on the server side (make clean, ./config .. , make , make install and make install-configs) but the issue is still there.

Can you explain more your mean about there steps to fix my issue? I think I don't understand much what you mean. Sorry if my question is silly.

Thank you for your support.

**Comment by grke** [comment]
Hello,
It looks like you tried what I was suggesting and it didn't work.
Maybe it is just a certificate issue.

Did you have a look at the 'troubleshooting' section in the github wiki above for hints to fix certificate issues?

**Comment by nhanvolac** [comment]
Thank you,

Thanks for your suggestion, but I think I will look for another way to back up with this client (Centos 5.3).

Besides, I have a windows client run backup. And now, I want to restore.

I configured restore on Burp-UI and run command "burp -a t" on Burp Server (with testclient permission - restore all clients).

But when I running the command, It shows a lot of messages related to:

> WARNING: Could not open for writing  ... Is a directory.

I still received  the file after restoring but cannot open it smoothly (failed to open file word, excel..)

I tried to restore with Windows client (running "burp -a t" to restore). It runs smoothly. Can open file without error, the timestamp of the folder is correct...

How to restore file Windows on Linux Server to not fail when open. 

Burp Backup System: Ubuntu 16.04 (64bit).

Thanks you.

**Comment by nhanvolac** [comment]
I've referred:
https://github.com/grke/burp/issues/515
https://github.com/grke/burp/issues/504
and
https://sourceforge.net/p/burp/mailman/burp-users/thread/77e7ea26-79ee-d814-510e-6c1d4ee15113%40mejor.pl/#msg35438125
But it does not solve my issue.

**Comment by ziirish** [comment]
Hi,

I don't really understand your statement about Burp-UI.
Anyway, by default, the files backed-up on a Windows machine will contain extra headers (VSS headers). In order to restore files originating from WIndows on Linux, you need to run `vss_strip yourfile.docx`

**Comment by grke** [comment]
The subject seems to have changed away from your original certificate problem, which you have given up on (I don't know if you looked at the 'troubleshooting' wiki for certificates like I suggested).

So I will now close this issue.
If you have a different burp problem, please open a separate issue, or ask on the burp-users mailing list. I think more people read the mailing list than the github issues, so you might get more responses there too.

**Comment by nhanvolac** [comment]
Thanks Ziirish and Graham so much.
