### ISSUE TITLE
Re: [Burp-users] Problems with lockfile when running forked From: Graham Keeling <grke@gr...> - 2017-09-06 06:11:16

### ISSUE THREAD

**Issue by rmast** [grke/burp#609]
I tried to start burp stable 2.0.54 as a daemon ( burp -c /etc/burp/burp-server.conf ) with
user=burp
group=burp.
I got the same message in /var/log/syslog that the  pidfile could not be opened.

Sep 10 13:36:28 ubuntu burp[26545]: Could not open lock file /var/run/burp.server.pid: Permission denied
Sep 10 13:36:28 ubuntu burp[26545]: Could not get lockfile.
Sep 10 13:36:28 ubuntu burp[26545]: Maybe you do not have permissions to write to /var/run/burp.server.pid.

I tried to start 2.1.12 as daemon. Still the same message.

I made that file, empty, /var/run/burp.server.pid
I altered the owner and group to burp:burp. The same for the keys

sudo chown burp:burp /home/burp
sudo chown burp:burp /var/run/burp.server.pid
sudo chown burp:burp /etc/burp/CA/burpserver.key
sudo chown burp:burp /etc/burp/dhfile.pem

At last the daemon is now waiting under user burp.
burp     33257     1  0 13:48 ?        00:00:00 burp -c /etc/burp/burp-server.conf

Since I created this pid file for user burp version 2.1.18 is now also starting as daemon.

I'm not familiar with the rules around pid-files, but hope this is contributing to the issue.

**Comment by grke** [comment]
Hello,

Thank you for your report.

I am closing this as I think I have now fixed it in master.
If you test master, and find that it is still broken, then we can reopen this.

**Comment by rmast** [comment]
I just ran master and for some reason the /var/run/burp.server.pid gets created for root with 644-privilege.

Then burp tries to reopen it for user burp/burp.

That ends up with:

Could not open lock file /var/run/burp.server.pid: Permission denied
Could not get lockfile.
Maybe you do not have permissions to write to /var/run/burp.server.pid.
Could not open lock file /var/run/burp.server.pid: Permission denied
Error when trying to re-get lockfile after forking.

If I chmod the file to 777 the burp-server starts. 

The initial open-statement for the creation of the lock contains mode 666, but there's also an umask 022 active.
Should we want to open this file for writing for more process owners or just give each process owner it's own file? Even then the file would first have to be written in /var/run, which only has write permissions for root. Should we make some group that unifies users root and burp? Is that possible?

**Comment by grke** [comment]
Hello,
I think that you are not testing master because the 'Error when trying to re-get lockfile after forking' message no longer exists in the source code.

**Comment by rmast** [comment]
Yes, you are right. Apparently I need to get even more familiar with git.
