### ISSUE TITLE
When protocol 2 will become production ready?

### ISSUE THREAD

**Issue by do11** [grke/burp#619]
http://burp.grke.org/protocol2.html states that "Use protocol 2 with extreme caution, it is not yet production ready." Is is still valid statement?

How much years should pass for protocol 2 to become production ready?

ps. Why I ask. I remember story when OpenVZ developers asked, why almost no one is using ploop feature which they developed several years ago. Answer is, they forgot to remove similar warning that it's 'not production ready' on their wiki page.

**Comment by deajan** [comment]
Graham said that protocol 2 should be fairly stable by now.
I'm testing it by actually backing up via protocol 1 and 2 the same computers and comparing restored backups on a daily basis.
As of today, I don't see any trouble.

burp-ui doesn't fully support protocol 2 AFAIK.

**Comment by do11** [comment]
@deajan Thanks! How long you are doing this test?

If it's stable, probably, web page should be updated.

**Comment by deajan** [comment]
@do11 Begun like a week ago, but there are still a lot of cases to test for me before I can say 'ok' for myself. Anyway, Graham is way more qualified to answer this question :)

**Comment by grke** [comment]
Yes, it is still a valid statement.
I would like to fix this before I would consider it "production ready":
https://github.com/grke/burp/issues/597
And at least look into this:
https://github.com/grke/burp/issues/467

**Comment by deajan** [comment]
Since both #597 and #467 are done, is protocol 2 now more close to production status ? ;)

**Comment by grke** [comment]
Closer, but not yet production status.
