### ISSUE TITLE
Configuration file is rewritten even when no change is introduced

### ISSUE THREAD

**Issue by unode** [grke/burp#620]
https://github.com/grke/burp/blob/ef97ddc4f60529efafdd0ca142d542923babff9d/src/client/ca.c#L67

This was first noticed while working on configuring burp services on NixOS (https://github.com/NixOS/nixpkgs/pull/30553). The configuration location is by design read-only and burp fails to start due to being unable to write the config file.

Later it turned out that the final config file was identical to the initial one. No change was introduced.
Yet burp still tried to rewrite the file leading to an early error and failure.

**Comment by grke** [comment]
Thanks for the report, I will take a proper look when I find some time.

**Comment by grke** [comment]
Hello,
This is now fixed in master.
