### ISSUE TITLE
dedup_group unset when only user and group is defined

### ISSUE THREAD

**Issue by landryb** [grke/burp#624]
Using the default config with 2.0.54, i only specified user and group, there's no mention of dedup_group in the example server config, but the process fails to start complaining about `dedup_group unset` - either it should be specified in the commented out section of the example config file, or it should silently default to the value of `group` ?

**Comment by grke** [comment]
Hello,

The 'dedup_group' option is present in the default config in 2.0.54.
It is not related to the 'group' option.

You have probably upgraded from burp-1.x.x and have the configs left over from that, which don't contain 'dedup_group'.

"make install-configs" will overwrite your existing configs with the burp-2.0.54 defaults, but you may not want to do that.

Closing.
