### ISSUE TITLE
ncurses monitor client broken when not on linux & sbindir != usr/sbin

### ISSUE THREAD

**Issue by landryb** [grke/burp#626]
In 048e6dca code was added to check for `/proc/<pid>/exe` to get the path to the running binary when forking a monitor - this wont work on systems where `/proc` isnt available (ie OpenBSD at least)

So it fallbacks to `/usr/sbin/burp` (code added in 7e49ed02) and then to /usr/sbin/PACKAGE_TARNAME (code added in 2cbfba95) - that will also fail when sbindir isnt `usr/sbin` (ie on BSDs, usually packages are under /usr/local or /usr/pkg for NetBSD for example)

There's surely a way to pass the actual value of sbindir via a #define..

**Comment by grke** [comment]
Hello,

Trying to pass through sbindir from configure also won't work if you copy the binary somewhere else after compilation.

Here is the code as it is now:
```
        snprintf(procpath, sizeof(procpath), "/proc/%d/exe", getpid());
        if(!readlink_w(procpath, buf, sizeof(buf)))
                args[a++]=(char *)buf;
        else if(is_reg_lstat(prog_long)>0)
                args[a++]=(char *)prog_long;
        else
        {
                static char p[64]="";
                snprintf(p, sizeof(p), "/usr/sbin/%s", PACKAGE_TARNAME);
                args[a++]=p;
        }
```

I would have thought that the 'is_reg_lstat' section would work for you.
That should be grabbing the path that burp was invoked with.
Why doesn't that section work for you?

**Comment by landryb** [comment]
I'll have to add some debug printfs to see what prog_long is, but afaik on OpenBSD you have no way to know the full path of a running binary.

**Comment by grke** [comment]
Maybe a solution could be to let you set the path in burp-server.conf.

**Comment by grke** [comment]
That can be achieved pretty easily with the config file templating stuff that already exists - it already knows $sbindir.

**Comment by grke** [comment]
There is now a change in master that lets you set 'monitor_exe=[path]' in the client burp.conf (not the burp-server.conf, I was wrong about that, it is a client option).

**Comment by landryb** [comment]
You mean 2f8caac60d ? Thanks for this !

Also, i see that now most development happens on 2.1/master, while the website advertises 2.0 branch - should users/packagers start moving to 2.1 ?

**Comment by grke** [comment]
It is up to you which version you wish to use.
I recommend 2.0.54 for most people as it is stable in that I don't change it.
If you want the latest updates, you need 2.1.x, but there is a danger that things get broken there.
