### ISSUE TITLE
default timer_script broken on BSDs because of wrong date command arguments

### ISSUE THREAD

**Issue by landryb** [grke/burp#627]
`date -d` doesnt do what you expect on FreeBSD and OpenBSD:
```
     -d dst  Set the system's value for Daylight Saving Time.  If dst is non-
             zero, future calls to gettimeofday(2) will return a non-zero
             value for tz_dsttime.
```

So `timer_script` blows:
```
++ date +%s -d '2017-10-27 05:51:31'
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
```

I'll try to cook a patch to properly use the right arguments depending on the OS, or fallback to `gdate` - so that the provided `timer_script` works ootb on !linux :)

**Comment by landryb** [comment]
For FreeBSD's date:
```
root@burp:~ # date -j -f '%F %T' '2017-10-27 05:51:31' +%s
1509076291
`

OpenBSD doesn't have `-f` to specify the provided format like FreeBSD, sooo..
```
daytona:~/ $date -j +%s 201710270551.31
1509076291
``` 

That's.. awkward :)

**Comment by landryb** [comment]
I'm puzzled at those lines here: https://github.com/grke/burp/blame/master/configs/server/timer_script#L80
```
	  || ! now=$(LANG=C LC_TIME=C date +"%Y-%m-%d %H:%M:%S") \
	  || ! nowsecs=$(LANG=C LC_TIME=C date +%s -d "$now")
```
wouldnt it be simpler to replace those two lines by
```
 || ! nowsecs=$(LANG=C LC_TIME=C date +%s)
```

as `now` isnt reused afterwards ? it avoids uselessly calling date twice.. and gives the current date in epoch seconds.

**Comment by grke** [comment]
Instead of trying to make the timer script do the right thing for all systems, I would prefer to do this:
https://github.com/grke/burp/issues/209

**Comment by landryb** [comment]
Sure, but in the meantime, if i provide you a PR that doesnt break linux and also works on *BSD, would you accept it ? :) Sure, i get that it's better to internalize this stuff (leaving the script possibility for flexibility) but that shouldnt prevent us from fixing things :)

**Comment by grke** [comment]
Hello,
Yes, I would be happy to accept your fix! :)

**Comment by landryb** [comment]
I have something that seems to work for freebsd/openbsd, and that shouldnt cause regressions on linux - see https://github.com/grke/burp/compare/master...landryb:portable_timer?expand=1 - ok, it *might* feel a bit awkward :)

**Comment by grke** [comment]
Hello,
When I ran it on linux, I get errors:
2017-11-12 02:53:18 +0000: burp[4325] Running timer script: testclient /var/spool/burp/testclient/current /var/spool/burp reserved1 reserved2 20h Mon,Tue,Wed,Thu,Fri,00,01,02,03,04,05,19,20,21,22,23 Sat,Sun,00,01,02,03,04,05,06,07,08,17,18,19,20,21,22,23
2017-11-12 02:53:18 +0000: burp[4325] Out of timeband: Mon,Tue,Wed,Thu,Fri,00,01,02,03,04,05,19,20,21,22,23
2017-11-12 02:53:18 +0000: burp[4325] In timeband: Sat,Sun,00,01,02,03,04,05,06,07,08,17,18,19,20,21,22,23
2017-11-12 02:53:18 +0000: burp[4325] date: invalid option -- 'j'
2017-11-12 02:53:18 +0000: burp[4325] /usr/share/burp/scripts/timer_script: Date command returned error for testclient.
2017-11-12 02:53:18 +0000: burp[4325] Try 'date --help' for more information.
2017-11-12 02:53:18 +0000: burp[4325] /usr/share/burp/scripts/timer_script returned: 1
2017-11-12 02:53:18 +0000: burp[4325] Not running backup of testclient

**Comment by landryb** [comment]
Well, does `date --version` has 'coreutils' in its output ?

**Comment by grke** [comment]
Hello,
Yes:

```
graham@small:~$ date --version
date (GNU coreutils) 8.26
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
graham@small:~$ 

```

**Comment by landryb** [comment]
And what if you run it with `bash -x` ? should give you the value for `gnu_date`...

**Comment by landryb** [comment]
Oh, i see where i failed. Let me improve that...

**Comment by landryb** [comment]
Should be better with 141e63481 which i've tested on linux this time :)

**Comment by grke** [comment]
Hello,

This thread, and having needed to manually test changes to the timer_script, has prompted me to implement #209. Internalising the timer script is now in master. You get the internal version by not defining 'timer_script' in your config. It has lots of automatic tests too.
Hopefully, this makes all the problems with different version of 'date' go away.

**Comment by landryb** [comment]
Works for me :) Thanks !
