### ISSUE TITLE
Files backed up again after path has changed

### ISSUE THREAD

**Issue by josvo** [grke/burp#632]
Assume we have a bunch o files: C:/Users/username/photos/pic1.jpg, ...
The path is changed to C:/Users/username/photos/holiday/pic1.jpg, ...

When there is a new directory, all the (allready saved, although in another path) files are backed up again. 
On server side, this looks like:
246M    0000001 2017-10-31 23:39:03 +0100 (original backup)
1.2M    0000002 2017-10-31 23:45:20 +0100 (same path)
246M    0000003 2017-11-01 19:54:02 +0100 (changed path)

So all files are transfered again. In theory, it would not be necessary to transfer all those files again, as they are allready there. Altouhg I'm not sure if this is solvable with protocol 1 at all...
Of course it is possible to dedup the files afterwards, but an ideal solution would be if there was no need to transfer the files again.
Tested on Windows 10 with protocol 1.

**Comment by grke** [comment]
Hello.

Yes, this is one of the reasons for protocol2 and it will never be different in protocol1.

Closing, but I appreciate your good intent.
