### ISSUE TITLE
IP_TOS is only for IPv4 sockets

### ISSUE THREAD

**Issue by landryb** [grke/burp#633]
https://github.com/grke/burp/blob/master/src/asfd.c#L398 -> sadly, it only works for IPv4 sockets, for IPv6 sockets setsockopt() call fails with:
```
main socket: error: setsockopt IPTOS_THROUGHPUT: Invalid argument
```

For v6, IPPROTO_IPV6 & IPV6_TCLASS should be used instead, but first one would need to check if the socket is AF_INET or AF_INET6..

**Comment by grke** [comment]
Hello,
I don't understand very well? Do you have a patch, or an example of how to use IPV6_TCLASS?

**Comment by landryb** [comment]
There are two things here - either you want to set IPTOS_THROUGHTPUT only if the socket is a v4 one (leaving the v6 case aside, as i have no idea if the behaviour with IPV6_TCLASS is the same) and then you need to test/check if the socket is AF_INET (but in the context of the function, i dunno if you have access to this information)
And the second case is, once you know if the socket isnt AF_INET, but it's AF_INET6 (ie not AF_UNIX) then you might want to set IPV6_TCLASS.

An example would be https://github.com/openbsd/src/blob/master/libexec/ftpd/ftpd.c#L534 or https://github.com/openbsd/src/blob/master/usr.bin/ssh/packet.c#L1997 in ssh.

**Comment by grke** [comment]
There is now code for this in master.
Thank you.
