### ISSUE TITLE
[NOT AN ISSUE] Burp backup check script

### ISSUE THREAD

**Issue by deajan** [grke/burp#648]
Hi,

Since we were talking about ways to verify burp backups in #630, I am currently developping a script that allows to execute burp verification process for n last backups for all clients.

I am also using burp to backup laptops, and since this means that I can get a lot of error mails regarding failed or aborted backups, the script also can list all clients that only have backups older than n days.
So I can get an email listing all clients that didn't have a successful backup in a week or so.

My script is currently in the works, but I would like to know if it would be possible to add this to the burp repo (and where?), and maybe add a little documentation I could write.

Guess this could interest more people than just me.

Current version is here https://gist.github.com/deajan/989ab96743033398ed79f06d43904449

Best regards.

**Comment by grke** [comment]
Hello,

If you think it is good to add this to the burp source, I would put it in configs/server, with all the other server-side script.

**Comment by deajan** [comment]
I improved the script to detect rogue clients (no client conf file), improved backup verification by paralellization (also interleaving different clients so I/O is better), and added various options.

There's still some work in progress, but most work is okay.
Before creating a PR, I would like you to check the script and see if it works for you (works for protocol 1 and 2 for me), or simply change command line parameters to be more "in phase" with the burp project.

Example of usage:
```./burp_checks.sh --backup-dir=/burp/perso/clients/ --exclude-clients=badcore-test.local,restoreclient --check-outdated-clients=7 --verify-last-backups=2 --destination-mails=alerts@example.com```

Maybe you can think of other operations the script could do.

Best regards.

**Comment by grke** [comment]
Hello,

It looks like a lot of effort went into this script.
I don't think I have enough time to check it thoroughly.
However, I did run it a few times and it seemed to work for the things I asked it to do.

I think that people that are not on sensible linux-type systems will have problems with things like the 'date' and 'find' and 'sed' commands, as I have found with the timer script.

I think an option to include clients might be nice.
And also short-form options (-d <blah> -e <blah>).
You also have a chunk of Windows-related stuff in your 'SendEmail' function that seems like it doesn't belong.

**Comment by grke** [comment]
It actually pointed out that one of my clients is out of date, I need to fix that. :)

**Comment by grke** [comment]
I think your "clients" folder check isn't quite right for protocol1. I have 'directory' in burp-server.conf set to /mnt/somepath/burp and your script wants "burp" to be "clients", so I always get the "does not seem to be a clients folder" warning.

**Comment by deajan** [comment]
Okay for the short-form options, I'll look into implementing those.
As for the windows related stuff in SendEmail, it's there because the function is supposed to work on virtually all environments (didn't code this one especially for this script).

Yep, tested an earlier version of the script on protocol 1 and since then I changed the way to detect whether the folder is okay. I'll rework that part to be protocol 1 & 2 compatible again.

Also added my earlier script "unstrip_vss" into this one to make it a "burp tool".
I will make a PR once I'll have sorted out the last parts here.

**Comment by deajan** [comment]
Updated the script with short syntax and better folder detection between protocol 1 and 2.

Example: Include all clients that begin with test, exclude all other clients, verify last backup, check if backup is older that 7 days
```./burp_tool.sh -d /storage/burp-protocol2/global/clients -c /etc/burp/bui2.conf -i "test.*" -e ".*" -o 7 -v 1```

I will let this script run for a while at my burp setups, and prepare a PR accordingly.
Would you mind validate ?

**Comment by deajan** [comment]
Btw, I would like to write a bit of documentation for the script.
Where should I write the docs for a PR ?

**Comment by grke** [comment]
Hello,
I usually put stuff in a text file in docs/, which makes it easy for me to add it to the burp website, or you are welcome to add a wiki entry on github.

**Comment by deajan** [comment]
Great. I'll write something up to make a full PR.
In the meantime, I added service watchdog functionality to the script and made some more bug fixes.
Going to be ready in no time.

**Comment by deajan** [comment]
I have created PR #661 for my script, which IMHO is ready for inclusion.

There's still the backup / verification concurrency issue I could work on. Started with function IsClientIdle that I'll have to launch, but this is a major work on my parallelExec function in order to take execution conditions.

**Comment by deajan** [comment]
I now have a new implementation, that before running each queued verify command, checks if client is idle, and if not, postpones verification for later, running next verify operation in the queue.
As the queue is interleaved for multiple clients, this should work not so bad.

Current PR doesn't have that feature yet, as I had to improve my main async functions I also use in other projects, which already have test frameworks for those.

In the meantime, do you think the PR is okay ?

**Comment by grke** [comment]
Hello,

I think it is all OK, except that if it is going in the scripts directory, I prefer not to include 'burp' in its name.
The reason is that I did some effort to generate names that mention 'burp' from AC_INIT line in configure.ac, so that it is possible to 'white label' it.
And the other scripts in the scripts directory look like this:
```
notify_script
ssl_extra_checks_script
summary_script
timer_script
```
I admit that it is silly that they all have '_script' on the end, but I think you should follow the same pattern.
So, I would prefer if it were called something like 'verify_script'.
That's pretty annoying for you, I should have noticed sooner. Sorry about that.

**Comment by deajan** [comment]
Indeed, I'll go your naming way.
Since the script does more than just verifying, I think I'd go for a more generic name like 'backup_tool_script'.
I put some efforts into this, hopefully people will begin to use it, once "found" on the docs.

I'll update the PR accordingly, probably including the new conditional feature once I have it enough tests on my setups.

**Comment by deajan** [comment]
Btw, I have some elements in my script like the following which I obviously cannot 'white label'.
```
## Burp executable (can be set to /usr/bin/burp, /usr/local/bin/burp...)
BURP_EXECUTABLE=burp
````
I guess I'll have to leave that.

**Comment by grke** [comment]
Hello,
There is a way to do it that I have used for other scripts.
For example, there is a file called 'summary_script.in' and the Makefile.am contains this line:

```
summary_script:
        $(AM_V_at)rm -f $@
        $(AM_V_GEN)$(do_subst) <$(srcdir)/configs/server/summary_script.in >$@
```

So, your one would be backup_tool_script.in, and it would have this instead of 'burp':
@name@

If that is too annoying for you to do, that is OK, I will merge your stuff, then adjust it myself.

**Comment by grke** [comment]
I will merge this shortly, and do the rename/substitution things. Hopefully tomorrow. Sorry to take ages about it.

**Comment by deajan** [comment]
Actually, don't merge it yet.
Since I had to do the renaming (which is already done), I worked on the conditional backup verifications, and which I would like to include into the PR.
Just waiting for it to be tested for some more days on my multiple burp platforms.
I'll update the PR next week with all mods.

**Comment by grke** [comment]
OK, thanks, I will wait until you say you are ready.

**Comment by deajan** [comment]
Care to run this one against one of your test servers ?
https://gist.github.com/deajan/d2cae9399fdd71e97a66fcfd08433051

Quite finished work. Has lot of functionality now. Doc is up to date in my PR.
Before merging, I'll just finish some refactoring which shouldn't change functionality.

**Comment by deajan** [comment]
Closing this since PR is ready.
