### ISSUE TITLE
offsite backup questions and possible changes

### ISSUE THREAD

**Issue by pablodav** [grke/burp#649]
Hello Graham/community, 

I was checking script https://github.com/grke/burp/blob/master/configs/server/offsite-backup 

Also thinking in the possibilities for offsite-backup, so I have some questions: 

- Is it possible to backup offsite "current" backup only? 
So I will backup only current symlink with its data, also use "mirror" for this "current" backup, so only changes will sync and also will delete files non existing on source. 

The actual script for "offsite-backup" is though to run as "post-script", but I'm thinking in the possibility to backup offsite only once a day in schedule task, so I will implement a post-script to add a "flag" file that marks the backup dir as "offsite_backup_pending" and also a flag after backup is done as "offsite_backup_ok" (like adding these files in client dir). What do you think about this?

**Comment by deajan** [comment]
Hello Pablo,

Maybe using an elaborate offsite backup script would be easier here.
I have a big rsync/ssh wrapper called obackup which handles includes/excludes, timed execution, email alerts etc that can be used as post-script here, or via cron.
In the config file, it is possible to specify:
```
RECURSIVE_EXCLUDE_LIST="/my/burp/client/directory/clients"
RSYNC_INCLUDE_PATTERN="current"
RSYNC_EXCLUDE_PATTERN='*/'
KEEP_DIRLINKS=yes
```

**Comment by pablodav** [comment]
Thanks for you answer @deajan , 

is it possible to share the script for you?

**Comment by deajan** [comment]
https://github.com/deajan/obackup :)

**Comment by grke** [comment]
Hello Pablo,

If deajan's script is good for you, let us know and we can close this issue.

Thanks, deajan.

**Comment by pablodav** [comment]
I haven't tested it yet, but will close the ticket because the questions are cleared now.
If I have some new questions, or some good result; I'm will be sharing it.

**Comment by pablodav** [comment]
Hello @deajan ,

I haven't tested it yet, but have been reading all documentation and configuration example. 
Now I have one more question for you or anyone else that have tested it. 

I think we need to enable hardlink backup option: 

```ini

## Preserve hard links. Make sure source and target FS can manage hard links or you will lose them.
PRESERVE_HARDLINKS=yes
```
As protocol=1 of burp uses hardlinks in its structure for backups. (At lease in a simple rsync usage I have used rsync with hardlinks option). 

Do you see any issue with it? I will use same fs in dest (ext4).

**Comment by deajan** [comment]
Indeed I do use this option on my burp replications.
