### ISSUE TITLE
Backup verification warnings for the last backup, regardless which backup is verified

### ISSUE THREAD

**Issue by deajan** [grke/burp#654]
Hello,

I'm running my burp_tool.sh script on all my burp servers via cron in order to validate the script functionality.
On one of my servers, I am verifying the last 7 backups, and get 7 warnings from burp, for earch backup:
```2017-12-04 01:54:34 +0100: burp[11603] WARNING: The latest backup needs recovery, but continuing anyway.```

Would it be possible to remove this warning when verifying a backup that does not need recovery ?
Since I'm trying to validate elder backups, I always get the warning, regardless if the backup is okay or not, so no script can determine if and elder backup is okay or not.

Best regards,
Ozy.

**Comment by grke** [comment]
Hello,
I think it is possible. The code has to see whether the backup is a hardlinked_archive, or if there is a newer hardlinked_archive that is not the most recent.

**Comment by deajan** [comment]
I Guess there aren't hardlinks for protocol 2?
Didn't see those warnings on my protocol 2 backups anyway.
Would be Indeed a nice fix, thanks.

**Comment by grke** [comment]
Yes, you are right, hardlinked_archive is irrelevant for protocol2.

But protocol2 still does the current/working/finishing symlink business, so it is possible to see the warning and for it to be accurate.

**Comment by grke** [comment]
Should be fixed in master now.

**Comment by deajan** [comment]
Terrific, going for a test ride these days :)

**Comment by deajan** [comment]
Had time to test, works for me :)

**Comment by grke** [comment]
Cool, thanks.
