### ISSUE TITLE
[Q] When is backup_script_pre_run?

### ISSUE THREAD

**Issue by melak** [grke/burp#659]
Am I reading `client/main.c` right that backup_script_pre is run just before an actual backup would take place, i.e. after the server had successfully authenticated and the timer and server scripts authorised the client? (Case in point, it would _not_ be run if the timer or server scripts decided it's not the right time to take a backup now?)

If so (rather, either way), a small note about this in the manual would be appreciated.

**Comment by grke** [comment]
Yes, it runs after the server decides that is time to backup.
I have updated the man page in master.
