### ISSUE TITLE
2.0.54: privilege escalation via PID-file manipulation

### ISSUE THREAD

**Issue by mkszuba** [grke/burp#663]
When running as non-root versions of burp older than 2.1.18 drop superuser privileges before creating PID files, meaning the pid-file directory must be writable for the user the burp server runs as - thus making it possible for said user to write arbitrary data to the PID file. If burp server is run using an init or daemon-monitoring system which tracks daemon-created PID files, said system can be tricked into e.g. killing an arbitrary process instead of the burp server.

On the master branch this was fixed by commit f765ad2c9f421eefcd3afc447ed45fa3fd2d17a0 but unfortunately the change was never backported to the 2.0 branch - and 2.0.54 remains the recommended stable release. On the plus side, said commit applies to 2.0.54 code without any trouble and seems to do exactly what it is supposed to.

**Comment by grke** [comment]
OK, thanks. What do you think I should do?
Current master release from yesterday is 2.1.26, which is 'stable candidate'. This will probably be the stable release by the end of January.

**Comment by mkszuba** [comment]
If 2.2.0 is indeed expected soon, I guess it depends on how much work it would be for you to backport the commit and release 2.0.55. Myself, I would go for it were it quick but only then - to my knowledge Gentoo is the only Linux distribution which uses a dedicated user to run the burp server (I have confirmed that Debian, Fedora and Arch all run it as root) and we have already applied this fix on our end.

**Comment by grke** [comment]
Hello,
OK, I will leave this issue open until I make 2.1.x 'stable', which should be the end of this month.

**Comment by grke** [comment]
2.1.28 'stable' is now released.

**Comment by grke** [comment]
Sorry, I do not consider protocol2 production-ready in this release, although I know some people are using it or testing it in production environments.
