### ISSUE TITLE
'docs' page for common list/verify/restore operations

### ISSUE THREAD

**Issue by grke** [grke/burp#670]
Add a 'docs' page that walks the reader through some common list/verify/restore operations, with example output.

**Comment by larsen0815** [comment]
Here are some commands I have saved in my personal docs. Might be helpful as a start.

List last backup:
````burp -a l -b current````

Restore single file/directory to "/restore":
````burp -a r -d /restore -r #RegEx#````

Restore from a specific backup:
````burp -a r -b 123 -d /restore -r #RegEx#````

Restore while not creating the first levels of directories:
````burp -a r -d /restore -s 5 -r #RegEx#````

**Comment by grke** [comment]
Now up:
http://burp.grke.org/docs/restoring.html
