### ISSUE TITLE
Burp on a file system with no xattr support

### ISSUE THREAD

**Issue by mkszuba** [grke/burp#671]
Let me begin by saying that this less of a bug report and more of a request for comments. Basically, I would like to discuss how this particular scenario should in your opinion be handled.

Anyway, turns out that running the burp test suite, regardless of whether burp has been built with or without ACL support, on a file system with no or incomplete extended-attribute support causes the failure of three tests:

`utest/client/test_extrameta.c:102:F:Core:test_extrametas:0: Assertion '!set_extrameta( NULL, path, expected, strlen(expected), NULL )' failed
utest/client/protocol2/test_rabin_read.c:80:F:Core:test_rabin_read:0: Assertion '!set_xattr( NULL, sb->path.buf, x.write, strlen(x.write), metasymbol, NULL )' fail
utest/client/test_xattr.c:149:F:Core:test_xattrs:0: Assertion '!set_xattr( NULL, path, x.write, strlen(x.write), metasymbol, NULL )' failed`

One of the affected file systems is tmpfs because it only supports _security_ and _trusted_ xattr name spaces whereas the failing tests operate  on _user_. This is unfortunate because building packages on tmpfs is fairly common among Gentoo users.

Now, under Linux _setxattr()_ and friends return ENOTSUP in the event of the underlying file system not supporting either the given name space or xattrs as a whole. The big question is, how serious is it for burp not to be able to use extended attributes?

**Comment by grke** [comment]
Hello,

It is not serious at all, unless you want to backup xattrs.
If you wish, you can compile it without xattr support.

For the gentoo users, do you think it would work to change the tests to operate on the 'security' or 'trusted' namespaces?

**Comment by grke** [comment]
Closing because of no response. If you want to talk more, we can reopen.

**Comment by mkszuba** [comment]
Sorry about lack of feedback, I tried a few things here but never reached anything conclusive. What I have found out is that using either 'security' or 'trusted' namespaces instead of 'user' would indeed work better but the change would have to be done carefully because many attributes from those namespaces can only be modified by users with appropriate capabilities (i.e. under most circumstances the superuser). One would have to find some which do not require this so that the test suite can still be run as a regular user, which is e.g. how Portage operates.

No need to reopen this in my opinion, just my severely belated two cents on the subject.

**Comment by grke** [comment]
Hello,
Do you know of any any in 'security' or 'trusted' that can be modified by normal users?

**Comment by mkszuba** [comment]
Alas, nothing that could be reliably used because what 'security' attributes can be modified by such users depends on active security modules. 'trusted' on the other hand is completely out of the question.

On the other hand, it seems there is very little interest in adding 'user' xattr support to tmpfs because it could allow the users to steal large amounts of RAM.

All in all, looks like it's either "if you want xattr support do not run the burp test suite on tmpfs" or telling the test suite to skip xattr tests if the underlying file system doesn't support 'user' xattrs. The former means more work for distro maintainers (i.e. me), the latter - for burp developers (i.e. you) ;-)

On a related note: I see there are three test suites which depend on extended-attribute support: _client/xattr_, _client/extrameta_ and _client/protocol2/rabin_read_, however the latter is handled differently than the former two - it is included regardless of the value of HAVE_XATTR but seems to do nothing unless HAVE_XATTR is in fact defined. Any particular reason for that? Or am I missing something?

**Comment by grke** [comment]
Hello,

I think it is just me being inconsistent about the HAVE_XATTR thing.

Do you have a suggestion for how to detect and skip the tests if the file system doesn't support 'user' xattrs?

**Comment by mkszuba** [comment]
In theory it should be simple enough, simply surround all the xattr test suites in a "try setting user.comment on a test file, do not continue if the syscall indicates a failure and errno == ENOTSUP" block. The tricky bit will be to keep it cross-platform. A minimal reimplementation of the code you have already got in burp proper, perhaps? Using said code directly would work too of course, then again having the execution of a test suite depend on output of one of the functions that test suite doesn't feel entirely reliable.

**Comment by grke** [comment]
Yeah, it seems like the test for whether to run the test is half of the actual test anyway.
It might just be best to skip if the filesystem is tmpfs. ie, just special case your use-case, and you have to live with those tests not running.
