### ISSUE TITLE
Backup protection strategy [feature request]

### ISSUE THREAD

**Issue by do11** [grke/burp#672]
Currently we could protect burp backups from vandalism by `manual_delete=1` option. But this is a bit complicated since requires coding deletion script w/o bugs.

Other strategy is `client_can_delete=0` with `client_can_force_backup=0`. This is actually good.

Would be useful also to have separate deletion protect option similar to `keep` which would not allow to delete latest backups while allowing to delete older backups.

**Comment by grke** [comment]
Hello,

Sorry, I don't understand very well.
Can you explain more about your suggested option and how it would work?
What would it be called?

**Comment by do11** [comment]
When box is hacked it's important to not to let a hacker to delete backups. She have everything to access burp and to delete backups (in default configuration).

I thought there should be option besides having `client_can_delete=0` with `client_can_force_backup=0`.

First, I thought options would be like `protect_keep` with the same semantics as `keep`, it should not let client to delete inside of protect_keep intervals. For example keep is 7, 4, 6 and protect_keep would be just 7.

Now I think this is weak strategy, because hacker would just fill 7 forced backups with deleted data and then delete anything over.

So, now I think, currently `client_can_delete=0` with `client_can_force_backup=0` is best strategy to protect backups. You may close the issue. If I get better idea I will post update. Excuse me for thoroughly thought feature request.

**Comment by grke** [comment]
OK, no problem.
