### ISSUE TITLE
bedup: leave garbage files with filenames containing ".bedup.<pid>"

### ISSUE THREAD

**Issue by gfa-** [grke/burp#674]
Hi !

I've a server where bedup often leaves garbage files with filenames containing this kind of string:
".bedup.XXX" ; with XXX being the pid of bedup.
When this happen, running bedup again will create new files with ".bedup.XXX.bedup.YYY", etc... I call bedup with these options, and use the current stable version v2.0.54 provided by debian 9:
bedup -c /etc/bedup-server.conf -v -l

After trying to narrow down the problem, I think the issue is related to the maxlinks limit feature of bedup (read from the config file, or from the "-m" argument). When check_files() finds a file entry "f" from the "find" link list having more than "maxlinks" links, the the "f" entry is overwritten with the first "newfile" which is would be link to this entry if the "maxlink" limit wouldn't have been reached.
However, reset_old_file(), in charge of overwriting the "f" entry only overwrites the "path" and "nlink" properties of the entry, leaving "ino" (inode number) unchanged.
Because of this, the next time check_files() is called with a "newfile" already linked to this newly overwritten "f" entry, check_file() leave these".bedup.<pid" files (do_hardlink() will call rename() to overwrite the oldpath by the newpath, but both have actually the same inode and rename() just does nothing and return OK in this case).

This patch below seems to fix the issue for me.
The 1st hunk fixes the issue described above. The 2nd hunk address another problem also related to maxlinks were running bedup might always undo some links and remake them differently when run multiple times in a row.
```
--- a/src/server/protocol1/bedup.c
+++ b/src/server/protocol1/bedup.c
@@ -289,10 +289,13 @@ static void reset_old_file(struct file *oldfile, struct file *newfile,
 {
        //printf("reset %s with %s %d\n", oldfile->path, newfile->path,
        //      info->st_nlink);
-       oldfile->nlink=info->st_nlink;
+       struct file *next;
+
+       next = oldfile->next;
        free_w(&oldfile->path);
-       oldfile->path=newfile->path;
-       newfile->path=NULL;
+       *oldfile = *newfile;
+       oldfile->next = next;
+       newfile->path = NULL;
 }

 static int check_files(struct mystruct *find, struct file *newfile,
@@ -326,6 +329,12 @@ static int check_files(struct mystruct *find, struct file *newfile,
                        found++;
                        break;
                }
+               if(newfile->nlink>=maxlinks) {
+                       // This new file file has enough links. Just let it as
+                       // is to avoid undoing all these hardlinks.
+                       found++;
+                       break;
+               }
                if((!newfile->part_cksum && get_part_cksum(newfile, &nfp))
                  || (!f->part_cksum && get_part_cksum(f, &ofp)))
                {
```

**Comment by grke** [comment]
Hello,

Thanks for this.
But, I think something is not quite right with the first hunk.
After your patch, it looks like this:

```
        struct file *next;

        next=oldfile->next;
        free_w(&oldfile->path);
        *oldfile=*newfile;
        oldfile->next=next;
        newfile->path=NULL;
```

It seems to me that oldfile->path will be freed (which also NULLs it), and then newfile->path is also NULLed. So, both oldfile and newfile are now NULL, which doesn't look right.

Also, since newfile->path was NULLed without a free, isn't that a memory leak?

Maybe you didn't mean to keep the 'newfile->path=NULL' line?

I think this is a shorter piece of code equivalent to your version, and without the 'newfile->path=NULL':
```
        free_w(&oldfile->path);
        newfile->next=oldfile->next;
        *oldfile=*newfile;
```
But even that doesn't look exactly right to me.
I will do some tests when I have time, and figure out what is going on.

**Comment by gfa-** [comment]
Hi,

Your version is equivalent as mine, but without setting newfile->path to NULL, and with less statements :) but I was not sure it was safe to change newfile->next.
i.e. :
- oldfile->path is freed before being overwritten
- all the oldfile fields are overwritten by those from newfile, except "next" (because we don't want to modify the linked list the oldfile element is belonging to).
- newfile->next is set to oldfile->next (not necessary, maybe not safe ?)


> Maybe you didn't mean to keep the 'newfile->path=NULL' line?

I meant it. I think newfile->path should be set to NULL , as done in the original code.
Otherwise, it will be freed at the end of the function check_files() while it's still referenced by the updated oldfile->path variable :
```
        if(found)
        {
                free_w(&newfile->path);
                return 0;
        }
```
There is no memory leak as the original newfile->path string is now referenced by oldfile->path.

The original reset_old_file() code:
```
        oldfile->nlink=info->st_nlink;
        free_w(&oldfile->path);
        oldfile->path=newfile->path;
        newfile->path=NULL;
```

**Comment by grke** [comment]
In the original code, oldfile->path gets given the path from newfile.
In your code, as I understand it, both oldfile and newfile end up with path NULL.
Though I am not 100% sure what *oldfile=*newfile does.

Anyway, that is OK, I will find time to test your change, and maybe make an automatic test that proves everything is OK.

**Comment by gfa-** [comment]
> In the original code, oldfile->path gets given the path from newfile.

Yes, and this is still true after my patch is applied.

If we consider this struct :
```
struct file
{
        char *path;
        dev_t dev;
        ino_t ino;
        nlink_t nlink;
        uint64_t full_cksum;
        uint64_t part_cksum;
        file_t *next;
};
```
Then
```
struct file *a = ...;
struct file *b = ...;

*a = *b;
```
is equivalent to :
```
struct file *a = ...;
struct file *b = ...;

a->path = b->path;
a->dev = b->dev;
a->ino = b->ino;
a->nlink = b->nlink;
a->full_cksum = b->full_cksum;
a->part_cksum = b->part_cksum;
a->next = b->next;
```
and equivalent (or almost equivalent as potential padding bytes are also copied in this case) to:
```
struct file *a = ...;
struct file *b = ...;

memcpy(a, b, sizeof(*a));
```

I prefer the 1st or 3rd way as it is more concise, and less error prone in case to would add some fields to "struct file" one day.

**Comment by grke** [comment]
I prefer the memcpy() version, as I have done other things that way, whereas I have never deliberately used the other version.

I have been unable to reproduce the problem, but I did make a test that exercises the max_links feature, and it passes with your changes. So the changes are now in master.

Thank you for your effort.
