### ISSUE TITLE
Stdout command line option

### ISSUE THREAD

**Issue by grke** [grke/burp#675]
From do11:

"I believe stdout option is wrongly placed in the config, which is only partly fixed in 2.1 branch with -Q option. Naive packagers forget (as in never know) to put -Q in init scripts when daemonizing burp server. It's inverted logic. Now if I want to run burp verbose on console (only case when it needs to be verbose, and where some --verbose option would be enough) I should each time update config to have stdout=1 then not forget to turn it back.

Please add option to turn on verbosity, so we could always keep stdout=0 in config."

**Comment by ziirish** [comment]
I believe #746 fixes this problem as well:

```
burp -c /tmp/burp-server.conf -t | grep stdout
                          stdout: 0
burp -c /tmp/burp-server.conf -t -o "stdout=1" | grep stdout
                          stdout: 1

```

**Comment by grke** [comment]
Although not intuitive, it is still really cool and demonstrates your change nicely.

**Comment by grke** [comment]
I have a patch that moves the '-Q' option to use ziirish's new overrides code.
It also makes '-v' override to stdout=1, also using the overrides code.
The old '-v' (version command) is moved to '-V'.

So, instead of:
burp -c /tmp/burp-server.conf -t -o "stdout=1"
You can do:
burp -c /tmp/burp-server.conf -t -v

**Comment by grke** [comment]
Now in master.
