### ISSUE TITLE
Testsuite fails on Alpine Linux

### ISSUE THREAD

**Issue by clandmeter** [grke/burp#687]
When building burp [testsuites fail ](https://github.com/alpinelinux/aports/pull/3322)on Alpine Linux with the following error msg:

```
make[1]: Leaving directory '/home/clandmeter/repositories/aports/testing/burp/src/burp-2.1.28'
make  check-TESTS
make[1]: Entering directory '/home/clandmeter/repositories/aports/testing/burp/src/burp-2.1.28'
Running suite(s): alloc
 base64
 client_auth
 client_monitor_lline
 client_protocol2_rabin_read
 client_xattr
 cmd
check_pack.c:346: Error in call to fread: Bad file descriptor
FAIL: runner
====================================================
1 of 1 test failed
Please report to https://github.com/grke/burp/issues
====================================================
make[1]: *** [Makefile:8256: check-TESTS] Error 1
make[1]: Leaving directory '/home/clandmeter/repositories/aports/testing/burp/src/burp-2.1.28'
make: *** [Makefile:8524: check-am] Error 2

```

**Comment by grke** [comment]
Hello,

check_pack.c is an internal file in the 'check' library.

I don't have alpine linux.
Are you able to determine exactly which test is failing?

...

Looking at utest/test_cmd.c, the check library is probably unhappy that I am closing stdout.
Try commenting out "close(1);" in utest/test_cmd.c to see if that helps.

**Comment by clandmeter** [comment]
```
make  check-TESTS
make[1]: Entering directory '/home/clandmeter/repositories/aports/testing/burp/src/burp-2.1.28'
Running suite(s): alloc
 base64
 client_auth
 client_monitor_lline
 client_protocol2_rabin_read
 client_xattr
 cmd

Index of symbols

  a: Append to a file
  b: Backup timestamp
  c: Generic command
  d: Directory
  e: Error message
  f: Plain file
  g: ----------------
  h: ----------------
  i: Interrupt
  j: ----------------
  k: Windows EFS file
  l: Soft link
  m: Extra meta data
  n: Encrypted meta data
  o: ----------------
  p: Message
  q: Save path part of a signature
  r: File attribute information
  s: Special file - fifo, socket, device node
  t: Path to data on the server
  u: Windows VSS footer
  v: Windows VSS header
  w: Warning
  x: End of file transmission
  y: Encrypted file
  z: Plain file changed
  A: ----------------
  B: Block data
  C: ----------------
  D: Request for block of data
  E: Timestamp now/end
  F: Fingerprint part of a signature
  G: Bytes estimated
  H: ----------------
  I: ----------------
  J: ----------------
  K: ----------------
  L: Hard link
  M: Path to a manifest
  N: ----------------
  O: Bytes
  P: Bytes received
  Q: Bytes sent
  R: File attribute information preceding block signatures
  S: Block signature
  T: ----------------
  U: Encrypted windows VSS footer
  V: Encrypted windows VSS header
  W: Control packet
  X: ----------------
  Y: Total counter
  Z: Grand total counter

 conf
 fzp
 hexmap
 pathcmp
 protocol1_handy
 protocol1_rs_buf
 protocol2_blist
 protocol2_blk
 protocol2_rabin_rabin
 protocol2_rabin_rconf
 protocol2_rabin_win
 sbuf_protocol2
 slist
 times
 client_delete
check_pack.c:346: Error in call to fread: Bad file descriptor
FAIL: runner
====================================================
1 of 1 test failed
Please report to https://github.com/grke/burp/issues
====================================================
make[1]: *** [Makefile:8256: check-TESTS] Error 1
make[1]: Leaving directory '/home/clandmeter/repositories/aports/testing/burp/src/burp-2.1.28'
make: *** [Makefile:8524: check-am] Error 2

```

**Comment by grke** [comment]
So... is there anything similar in the client_delete suite?

**Comment by clandmeter** [comment]
I couldn't find it.

**Comment by grke** [comment]
Then the only way to proceed is for me to install alpine linux and run whatever it is that you are running.

I will attempt to install 3.7.0 from https://alpinelinux.org/downloads/

Do you have instructions on how to run what it is you are running?
I know nothing about alpine linux and package management on it.

**Comment by clandmeter** [comment]
Sure,

We use abuild using [this build script](http://tpaste.us/rZ5d) , but you could also just try to build it manually.

Boot the iso and `setup-alpine` choose your install tmpfs|hd

We use edge branch to build so you should probably update to edge:
change v3.7 to edge in /etc/apk/repositories and make sure you have both main and community repos added/enabled.
update system: `apk -U upgrade -a`


Setup build env: `apk add alpine-sdk `
install deps: `apk add uthash-dev libressl-dev zlib-dev librsync-dev check-dev bash`

Download the source as usual and start building.

**Comment by grke** [comment]
OK, I have done all of the above, but when I "download the source as usual and start building", I don't have autoreconf:

**Comment by grke** [comment]
```
localhost:~# git clone https://github.com/grke/burp.git
Cloning into 'burp'...
remote: Counting objects: 27448, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 27448 (delta 10), reused 18 (delta 5), pack-reused 27399
Receiving objects: 100% (27448/27448), 14.55 MiB | 3.42 MiB/s, done.
Resolving deltas: 100% (19331/19331), done.
localhost:~# cd burp/
localhost:~/burp# autoreconf -vif
-ash: autoreconf: not found
```

Maybe you do something different here?

**Comment by grke** [comment]
Never mind. I did:
```
apk add autoconf automake libtool
```
Now it is looking OK.

**Comment by clandmeter** [comment]
Yes fetching from git will need autotools. I used the release tarball.

**Comment by grke** [comment]
Making asfd_alloc() in src/asfd.c look like this helps a little:

```
struct asfd *asfd_alloc(void)
{              
        struct asfd *asfd;
        asfd=(struct asfd *)calloc_w(1, sizeof(struct asfd), __func__);
        if(asfd)                         
                asfd->fd=-1;                  
        return asfd;
}
```
I will add the asfd_alloc() change to burp, as some of the tests are incorrectly closing fd 0.

But this doesn't fix everything.
A major problem on my alpine installation is that the 'check' library is not forking for each test. It means that when burp closes stdin or stdout in a test, it remains closed in subsequent tests.

To show this, I changed close_fd() in src/fsops.c to look like this:

```
void close_fd(int *fd)
{
        if(!fd || *fd<0) return;
fprintf(stderr, "%d here: %d\n", getpid(), *fd); fflush(stderr);
        //logp("closing %d\n", *fd);
        close(*fd);
        *fd=-1;
}
```

Now, when I run the tests on alpine, the output after the 'asfd' suite looks like this:
```
 asfd
19753 here: 100
19753 here: 100
19753 here: 100
19753 here: 100
19753 here: 0
19753 here: 1
19753 here: 0
check_pack.c:346: Error in call to fread: Bad file descriptor
```

You can see all the pids are the same. Whereas, on my debian computer, it looks like this:
```
 asfd
9015 here: 100
9016 here: 100
9017 here: 100
9018 here: 100
9019 here: 0
9020 here: 1
9021 here: 0
9022 here: 0
9022 here: 1
```

So why isn't 'check' forking on alpine?

I tried forcing it by adding this to utest/main.c, as explained in https://libcheck.github.io/check/doc/check_html/check_4.html#No-Fork-Mode both by the environment variable method (which I sometimes use when debugging and normally works) and by the srunner_set_fork_status() method.
Both attempts didn't work.

The behaviour seems like 'check' has been compiled without fork being enabled.

The burp utests each assume that they are in separate processes (as they should be because tests ought to be isolated from one another). So, when they are not, things go wrong. If they were isolated from one another, the test run would get to the end and you would get a report of actual failing tests - rather than 'check' errors that immediately interrupt the test run.

I can't progress this further, as the broken behaviour of 'check' on alpine is not my problem.

**Comment by clandmeter** [comment]
Thanks for checking.

The problems is related to https://github.com/libcheck/check/issues/138

So we had to disable forking as it would be blocked by our grsec kernel (excessive forking).
As this is a feature within check, maybe your testsuite could check if the features is enabled and disable tests which depends on it?

**Comment by ziirish** [comment]
My understanding is **every** test need their own *environment*.
So I'm afraid no test can run on Alpine Linux, at least with the provided 'check' library.

I don't know much about Alpine Linux, but in my view, most of its usage is concentrated in containers.
In such environment your grsec kernel is likely not to be used. Would you consider providing a 'check' package without the fork-disabled feature so we can run burp tests inside an Alpine-based container?

**Comment by BernhardGruen** [comment]
I just compiled the check library on Alpine Linux with `--enable-forks`. I think this could be set in following versions as the grsec kernel is gone anyways (@clandmeter I file a separate bug for this).
After that (and adding ncures-dev to makedepends) all tests but one run correctly:
This is the only test that still fails:
```
99%: Checks: 350, Failures: 1, Errors: 0
utest/server/test_timer.c:271:F:Core:test_timer_internal:0: Assertion 'strptime(d->time_now, DEFAULT_TIMESTAMP_FORMAT, &tm)!=NULL' failed
FAIL: runner
```

**Comment by grke** [comment]
Looks like alpine doesn't support %z in strptime. When I remove %z from the format, it gets past line 271, but of course fails the test because knowing the timezone is important.

Something to do with this?
http://www.openwall.com/lists/musl/2015/08/14/2

**Comment by clandmeter** [comment]
@grke Right, musl uses [posix standards](http://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html) so it will lack some features provided by glibc. 

@BernhardGruen you cannot set enable forks as our infrastructure still uses grsec kernels and tests will fail on our builders (travis runs alpine in a chroot on ubuntu so it wont fail).

**Comment by grke** [comment]
I find this strange, because alpine accepts %z for strftime, but not strptime (the opposite of strftime).
How am I supposed to read back a timestamp that I wrote with strftime in the format: "%Y-%m-%d %H:%M:%S %z" ?

**Comment by ncopa** [comment]
They have discussed it on the musl [mailing list](http://www.openwall.com/lists/musl/2017/04/19/2):
> code using %z or %Z in strptime is nonconforming and thus
> nonportable so it should be fixed (it will break not just
> on musl).
>
> that said it's a commonly requested feature, but the exact
> requirements are not known, different implementations
> handle %z differently (some support iso 8601 format only,
> others support rfc822 style zone specifiers too) %Z i think
> is even more inconsistent across implementations.

POSIX requires that `%z` is supported for [strftime](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strftime.html), but it does not mention `%z` for [strptime](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strptime.html).

It seems that we are not the only ones who finds that strange. It is [reported](http://austingroupbugs.net/view.php?id=879) to the Austing group too, so I guess this may be something we want to fix in musl.

**Comment by grke** [comment]
OK, I can't do anything more on the burp side, so I am closing this issue.
You can reopen it if you need me to do anything else.

Thank you.
