### ISSUE TITLE
feature request - different path for temp files from data files

### ISSUE THREAD

**Issue by jirib** [grke/burp#688]
I'm not sure I understand correctly the concepts behind all symlink and dirs during backup described in:

http://burp.grke.org/docs/working_dir.html

but as temp directory is inside each client dir it prevents assigning fast disks for data during the backup itself and data kept when backup is done - eg. backup tmp data would go to solid storage disk but later they would go to usual rotating disks.

iiuc this would be path for temp data during backup itself - /var/spool/burp/jirib-cluster1/0000001 2018-02-21 17:08:46/data.tmp/t/ ...

or is there any other way to archive fast writing of client backup data?

**Comment by grke** [comment]
Hello,

Burp doesn't  just write things to <backup name>/data.tmp/.
It will also read/write to/from all sorts of other places inside <backup name>/, as well as the immediately preceeding backup.
It also uses hardlinks extensively, so mixing up disks inside <backup name>/ will likely cause problems.

I don't think you can achieve precisely what you want, but maybe you could do something like regularly archiving the directory that 'current' points to. That is, read the symlink to find the real directory, then rsync it somewhere else. Have a short retention on the 'live' backups, and manage the archived ones some other way. Something like the 'offsite-backup' script in the burp source, but copied locally.

**Comment by grke** [comment]
I think this is answered. Closing.

**Comment by grke** [comment]
I suggest joining the burp-users mailing list if you want to ask more questions to do with this, because more people will look at your questions and answer them there.
