### ISSUE TITLE
when phase4 takes long time, listing backups from client shows 'no backups'

### ISSUE THREAD

**Issue by jirib** [grke/burp#689]
could there be a message that there's something going on on the burp server itself and thus maybe there is unfinished backup.

and output could be 'no backup' with addition 'Job:  <id>.tmp <timestamp> (phase 4)

**Comment by grke** [comment]
Yes, there could be.
I think the status monitor does something like that already, where it lists unfinished backups.

**Comment by grke** [comment]
In master, it now lists unfinished backups.
Closing, thanks.
