### ISSUE TITLE
ncurses unit test fails if checking a build without ncurses support

### ISSUE THREAD

**Issue by BernhardGruen** [grke/burp#690]
I just found out that the ncurses unit test fails if one tries to build burp without ncurses suport.
Some errors of this type arise: 
```
utest/client/monitor/test_status_client_ncurses.c:223:F:Core:test_status_client_ncurses_with_orig_client:0: Assertion '!status_client_ncurses_init(ACTION_STATUS)' failed
utest/test_asfd.c:158:F:Core:test_setup_asfd_ncurses_stdin:0: Assertion '(asfd=setup_asfd_ncurses_stdin(as))!=NULL' failed
```

One can also read this message during the test run:
`To use the live status monitor, you need to recompile with ncurses support.`

These tests were done on Alpine Linux with 2.1.28 and a check library with `--enable-forks`.

**Comment by grke** [comment]
OK.

**Comment by grke** [comment]
It's a bit tricky for me to reproduce this right at this moment, so can you tell me:

Does it happen with any other files than
utest/client/monitor/test_status_client_ncurses.c
utest/test_asfd.c
?

**Comment by grke** [comment]
This is now fixed in master, as far as I can tell.
