### ISSUE TITLE
SF shows old stable version which does not exist for Windows

### ISSUE THREAD

**Issue by jirib** [grke/burp#692]
2.1.28 is declared stable according to http://burp.grke.org/download.html

but SF site shows 2.1.26 as stable and this version does not exist for Windows.

```
> curl -4 -s 'https://sourceforge.net/projects/burp/files/?source=navbar/' | ~/go/bin/pup 'div#readme div text{}'
2.1.26: Stable (recommended)
2.0.54: Old stable
```

It is recommended to use the current stable version.

The latest release contains new features, but may have unexpected issues.

```
> curl -4 -s 'https://sourceforge.net/projects/burp/files/?source=navbar/' | ~/go/bin/pup 'tr.folder span.name text{}'
burp-2.1.28
burp-2.0.54
burp-1.4.40
burp-1.3.48
```

**Comment by grke** [comment]
Fixed. Thanks for letting me know.
