### ISSUE TITLE
Compiling burp with librsync 2.0.2

### ISSUE THREAD

**Issue by deajan** [grke/burp#693]
Hello,

I said in the performance statistics thread I'd try to recompile burp with a recent librsync, which is supposed to bring better diff speed (about 2.5 factor using blake2 algorithm).
Yesterday, I've commited some rpm spec changes at librsync project, and today they released a fresh 2.0.2 release, which I used to recompile burp today (gotta love that timing :)

So far linux burp compilation works (quick synthetic performance tests didn't show anything wonderfull yet, need to do real world tests).
I tried to read the burp source and I think blake2 is the default algorithm when both server and client support it, am I right ?

I then begun modifying cross compilation tools, I modified burp-depkgs build-script and librsync-patches in order to work with the new CMAKE build tool that comes with librsync 2.x.

I ran in a lot of errors, so I begun comparing working and current compilation environments.
I ended up noticing that even when using a vanilla burp-cross-tools set, I run into the same errors which are:
```
make[1] : on entre dans le rÃ©pertoire Â« /opt/burp/burp-2.1.28/src/win32/burp Â»
../Makefile.rules:48: obj32/alist.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/alloc.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/asfd.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/async.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/attribs.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/base64.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/berrno.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/bfile.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/bu.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/acl.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/auth.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/autoupgrade.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/backup.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/backup_phase1.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/protocol1/backup_phase2.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/protocol1/restore.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/protocol2/backup_phase2.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/protocol2/rabin_read.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/protocol2/restore.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/ca.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/cvss.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/delete.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/extra_comms.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/extrameta.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/find.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/glob_windows.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/list.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/main.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/monitor.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/monitor/lline.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/monitor/sel.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/monitor/json_input.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/restore.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/client/xattr.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/cmd.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/cntr.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/conf.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/conffile.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/cstat.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/forkchild.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/fsops.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/fzp.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/handy.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/hexmap.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/incexc_recv.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/incexc_send.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/iobuf.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/linkhash.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/lock.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/log.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/main.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/msg.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/pathcmp.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/prepend.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/prog.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol1/handy.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol1/msg.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol1/rs_buf.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol1/sbuf_protocol1.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol2/blist.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol2/blk.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol2/rabin/rabin.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol2/rabin/rconf.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol2/rabin/win.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/protocol2/sbuf_protocol2.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/regexp.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/run_script.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/sbuf.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/server/protocol2/champ_chooser/incoming.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/slist.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/ssl.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/strlist.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/times.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/vss.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/vss_XP.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/vss_W2K3.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/vss_Vista.d: Aucun fichier ou dossier de ce type
../Makefile.rules:48: obj32/yajl_gen_w.d: Aucun fichier ou dossier de ce type
```

and

```
pcreposix.c:56:0: warning: "PCREPOSIX_EXP_DECL" redefined [enabled by default]
In file included from pcreposix.c:46:0:
config.h:254:0: note: this is the location of the previous definition
pcreposix.c:57:0: warning: "PCREPOSIX_EXP_DEFN" redefined [enabled by default]
In file included from pcreposix.c:46:0:
config.h:257:0: note: this is the location of the previous definition
  CCLD     libpcreposix.la
  CXX      libpcrecpp_la-pcrecpp.lo
  CXX      libpcrecpp_la-pcre_scanner.lo
  CXX      libpcrecpp_la-pcre_stringpiece.lo
  CXXLD    libpcrecpp.la
  CC       pcretest-pcretest.o
  CC       pcretest-pcre_printint.o
  CCLD     pcretest.exe
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-depkgs-librsync1/src/../mingw-w64-i686/lib:/opt/burp/burp-depkgs-librsync1/src/../mingw-w64-i686/bin'
libtool:   error: Continuing, but uninstalled executables may not work.
  CC       pcregrep-pcregrep.o
  CCLD     pcregrep.exe
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-depkgs-librsync1/src/../mingw-w64-i686/lib:/opt/burp/burp-depkgs-librsync1/src/../mingw-w64-i686/bin'
libtool:   error: Continuing, but uninstalled executables may not work.
  CXX      pcrecpp_unittest-pcrecpp_unittest.o
  CXXLD    pcrecpp_unittest.exe
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/../lib'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/../lib:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/$
libtool:   error: Continuing, but uninstalled executables may not work.
  CXX      pcre_scanner_unittest-pcre_scanner_unittest.o
  CXXLD    pcre_scanner_unittest.exe
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/../lib'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/../lib:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/$
libtool:   error: Continuing, but uninstalled executables may not work.
  CXX      pcre_stringpiece_unittest-pcre_stringpiece_unittest.o
  CXXLD    pcre_stringpiece_unittest.exe
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/../lib'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/opt/burp/burp-depkgs-librsync1/src/pcre-8.41/.libs:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/../lib:/opt/burp/burp-cross-tools/mingw-w64-i686/i686-w64-mingw32/lib/$
libtool:   error: Continuing, but uninstalled executables may not work.
make[1]: Leaving directory `/opt/burp/burp-depkgs-librsync1/src/pcre-8.41'
```

My vanilla environment is burp 2.1.28 with burp-cross-tools 2.1.22.
Since I get those errors anyway ,do these compile time errors produce any special behavior later or may I just discard them ?

I continued patching burp-cross-tools and eventually ended building win32 burp targets using librsync 2.0.2.

Shall I make a PR for the cross-compiling repo, or just send you my patches since the cross-compiling repo is in a non working state AFAIK ?

Best regards.

**Comment by deajan** [comment]
I've run all my tests on CentOS 7, x64 and of course the cross compilation works and builds working burp executables, I just happen to get those errors which look scary.

As for the changes I made, they should be portable to any other linux since they only modify the burp-depkgs which build with the cross tools.
I'll wait for you to have a bit time and a running internet connection, in the meanwhile, I can begin some librsync 2.0.2 against 1.0.0 speed tests with burp :)

**Comment by dbaarda** [comment]
Note the librsync speedups added since v2.0.1 are mostly because of a much better hashtable. It speeds up delta calculations regardless of md4 or blake2 blocksums, particularly for large files (5x+ for 1GB+ files). It should also have reduced memory requirements.

The blake2 blocksums was mostly a security fix, making it harder to craft files with hash collisions that would corrupt themselves. It also gives us larger 32byte blocksums (old default was 8, md4max is 16). This will make signature files nearly 4x bigger.

Personally I think 32byte strongsums is overkill. Excluding crafted attacks, the old 8bytes was OK for files upto 512MB,  12bytes upto 32TB, and 16bytes upto 2EB. So even if you are paranoid, 16bytes should be plenty. So for v2.0.2 rdiff I'd use -S16 to halve your signature size.

Another significant speedup is to set your --block-size to sqrt(filesize). This will reduce the signature size, speedup delta calculations, and reduce the chance of a blocksums collision at the cost of slightly increased delta sizes.

**Comment by deajan** [comment]
Thanks for your insight :)

**Comment by grke** [comment]
Here is the block size calculation that I have been using for a while:

```
size_t get_librsync_block_len(const char *endfile)
{
        size_t ret=0;
        uint64_t oldlen=0;
        oldlen=strtoull(endfile, NULL, 10);
        // round to a multiple of 16.
        ret=(size_t)(ceil((sqrt((double)oldlen))/16)*16);
        if(ret<64) return 64; // minimum of 64 bytes.
        if(ret>MAX_BLOCK_SIZE) return MAX_BLOCK_SIZE;
        return ret;
}

```

**Comment by deajan** [comment]
If block sizes should be equal to sqrt(filesize), it would mean that your minimum filesize is 64*64 = 4KB.
As far as my C gets me, I assume that ```#define MAX_BLOCK_SIZE ((uint32_t)1 << 17)``` makes a max block size of 128K which gives a file size of 16GB.

I do think that there are not much files today which are about 4KB size..
I could make the following tests in lab:

```
#define MAX_BLOCK_SIZE ((uint32_t)1 << 18)
...
if (ret<512) return 512; // minimim of 512bytes
```

which would work best for files between 256K and 64GB.

**Comment by grke** [comment]
The MAX_BLOCK_SIZE line was copied from rsync itself (not librsync), so I think it is probably good.

**Comment by deajan** [comment]
Hmmm... rsync and librsync are different beasts, and as funny as it sounds, rsync doesn't use librsync which is another implementation :)
Anyway, at least using 512 bytes minimum block size versus 64 bytes might improve speed. I'll have some tests.
What about @dbaarda strongsum point, does burp have use of 32bits signatures ? If yes, how about using those 16bits signatures ?

**Comment by dbaarda** [comment]
For smaller files there's not much speedup using larger blocks, so min 64bytes is probably fine.
For larger files I don't think there's any point having a max block size.

The max strongsum size is 32bytes per block, not 32bits. The minimum strongsum size can be calculated as;

B = (M + 2*ln2(filesize) - ln2(blocksize))/8

Where M is the number of bits redundancy, giving less than 1/(2^M) chance of a strongsum collision per file.

**Comment by deajan** [comment]
Indeed, mixed up bits and bytes :)
Thanks for the explanation, this will save me time doing tests.

**Comment by grke** [comment]
I have now updated my build systems, and burp-cross-tools to much newer versions. See here:

https://github.com/grke/burp/issues/645

I will now try updating librsync to 2.0.2 for Windows.

**Comment by grke** [comment]
"Since I get those errors anyway, do these compile time errors produce any special behavior later or may I just discard them ?"

I get those warnings too, you can ignore them.

**Comment by deajan** [comment]
I have made a pull request on https://github.com/grke/burp-cross-tools/pull/1 some time ago, including the patches I made for librsync-2.0.2 for the windows builds (I also left librsync-1.0.0 build commands in my PR).
Server builds with librsync 2.0.2 without any further modification.

I am almost done building my new lab where I have two different burp servers I can play with for speed comparaisons.
I just miss where in burp I can set the librsync strongsum size dbaarda is talking about.

**Comment by deajan** [comment]
Sorry if I wasn't clear enough. I'm searching the code bit that allows me to tweak that value, in order to make different builds and check for performance improvements / regressions depending the strongsum size.

**Comment by grke** [comment]
Oh, OK, the file is:
src/server/protocol1/blocklen.c

**Comment by deajan** [comment]
Hmmm... That's the block I modified some comments above.
Talking about the constant strongsum size, which obviously is 16 to 32 bytes. This value creates the unique fingerprint of a file.
I'll have to get deeper into that code to understand whether block_len and strongsum_len are mixed in that code.

**Comment by grke** [comment]
Oh, do you mean RS_DEFAULT_STRONG_LEN?
It is set to 8 at the moment, because that is what librsync 0.9.7 used to use.
It is passed into rs_sig_begin() and rs_sig_gzfile() in src/server/protocol1/backup_phase2.c and backup_phase4.c.

It makes sense now. It should be increased to 16, I think.

**Comment by grke** [comment]
The strong length is now 16 in git master, and I am now using librsync 2.0.2 to build the Windows installers.
Thanks for your ideas, help and patches!
Now closing this issue.

**Comment by grke** [comment]
I tidied the code a little.
If you wish to change the strong length, now all you need to do is go to src/protocol1/rs_buf.h and change PROTO1_RS_STRONG_LEN, at the bottom, and recompile. You only need to do this on the server side because only the server generates the signatures.

**Comment by deajan** [comment]
Thanks. I'll have my performance tests scheduled later this week.
