### ISSUE TITLE
Long path names lock up?

### ISSUE THREAD

**Issue by grke** [grke/burp#695]
From the mailing list:

Dear list,

I'm trying to backup a linux box with home directory mounted via `encfs
--reverse` -- it encrypts files contents as well as their names (unlike burp),
but creates very long names in the process. Client version is 2.1.8, server
version is 2.0.54 (yes I know this is not an officially supported
combination). Backup proceeds for some time with expected warnings "Path too
long for tree - will save in data structure instead", but then breaks on
server with the following messages:

> 2018-02-23 14:52:14: burp[8839] could not mkdir
/mnt/burp/XXXXXXXXX-XXXXXXXX-XXXXXXX_XXXX/working/data.tmp/t/mnt/encfs/backup/ho
me/UcZq9Ixg-9j4GinWbEbQ-xlg/4GqxvNQadh-cTxD-JD7oqFAQ/13l4HN6M0pqOlpg6daa3iVFz/hb
hRFDBjqtVzmIC-8Wnavybc/X7-MxWfkohbpUpLm5S6O-bSW/QWpnZZlEPNSkyP,WiYPXLU1P/ALOiyDJ
fCd3p64b9erCCrxhe/dw0wQX8t5534Rx79SyHlJiq2Wfb-j4v0pncOteHoDw6SirQwS5LSkF5hAnm9qD
-NcDs29ZzVsM0WZdqx9OW6nQ7cYZ3Joa-wrQgYkV0I5naW6GA0E7iGW8pmk,sxVnNqS5yZt5Ugf22KhJ
n7nYpqiVNYm4BrdJNZ6,nppgcuCYSMt1fUeQgqJqhhvUXW7gutcc2zK2FzlZ9FwEjLeoBPEFaucLKIyc
8kTeVwOflT,zr7n
> 2018-02-23 14:52:14: burp[8839] build path failed
> 2018-02-23 14:52:15: burp[8839] error in start_to_receive_new_file
> 2018-02-23 14:52:51: burp[8839] End phase2 (receive file data)
> 2018-02-23 14:52:51: burp[8839] error in backup phase 2

Client process just hangs at this point and has to be interrupted with ^C .
Interestingly, I can in fact create directory with this name on a command line
without problems (probably it is truncated in log?).

I guess this is some problem with 2.0.54, but I don't quite remember if it's
fixed already or needs further investigation. Can anybody with good memory of
list discussions please help?

**Comment by grke** [comment]
I am unable to reproduce. Currently waiting on the mailing list for additional clues.

**Comment by qm2k** [comment]
I'm the original reporter and I also cannot reproduce this after upgrade to 2.1.32.

**Comment by grke** [comment]
Cool, thanks for the update. I'm assuming it's no longer a problem.
