### ISSUE TITLE
No strcasestr on AIX

### ISSUE THREAD

**Issue by trustchk** [grke/burp#698]
strcasestr is a nonstandard extension that glibc and many BSDs have adopted, but it hasn't made it into AIX. Almost all operating systems (appart from some BSDs) have provide this function, though. The only place it is in use is the internal timer script (server/timer.c). We rely on an external timer script and have thus simply replaced it with strstr to be able to compile burp.
A general approach would be to check for the existence of strcasestr in configure, but I haven't had much luck with that. If it is missing, a simple tolower() on the strings should be enough to feed it into strstr. I've found a replacement: http://unixpapa.com/incnote/string.html (bottom-most, the mentioned functions strcspn and strncasecmp are available on AIX 7.1, I don't have older or newer versions to check).

**Comment by grke** [comment]
Thanks, I will do the 'tolower()' method, it is easy.

**Comment by grke** [comment]
Done, now in master.
