### ISSUE TITLE
Internal Timer: Interval wrong by 1 hour

### ISSUE THREAD

**Issue by Aisbergg** [grke/burp#714]
I am running Burp server and client inside a Docker Container using Alpine 3.7 as OS. I am still playing around with the backup timing and came across the problem, that the calculated time for the next backup is wrong by one hour.

Here are three examples with timing intervals of 1s, 1m and 1h:
```
2018-04-30 19:54:17 +0200: burp[530] In timeband: always
2018-04-30 19:54:17 +0200: burp[530] Last backup: 2018-04-30 19:46:12 +0200
2018-04-30 19:54:17 +0200: burp[530] Next after : 2018-04-30 20:46:13 +0200 (interval 1s) # should be 2018-04-30 19:46:13 +0200 

2018-04-30 19:47:13 +0200: burp[523] In timeband: always
2018-04-30 19:47:13 +0200: burp[523] Last backup: 2018-04-30 19:46:12 +0200
2018-04-30 19:47:13 +0200: burp[523] Next after : 2018-04-30 20:47:12 +0200 (interval 1m) # should be 2018-04-30 19:47:12 +0200 

2018-04-30 19:55:17 +0200: burp[531] In timeband: always
2018-04-30 19:55:17 +0200: burp[531] Last backup: 2018-04-30 19:46:12 +0200
2018-04-30 19:55:17 +0200: burp[531] Next after : 2018-04-30 21:46:12 +0200 (interval 1h) # should be 2018-04-30 20:46:12 +0200
```

**Comment by grke** [comment]
Hello,

Thanks for reporting it.
Can you please post of the output of 'env' when run in the same environment, with the same user, as your burp daemon?

For me, everything is OK. For example, I can set my TZ environment variable to 'GST-10', and I get:
```
2018-05-02 16:43:57 +1000: burp[12359] Last backup: 2018-05-02 16:42:43 +1000
2018-05-02 16:43:57 +1000: burp[12359] Next after : 2018-05-02 16:52:43 +1000 (interval 10m)
```

**Comment by grke** [comment]
And, 'GST-2':

```
2018-05-02 08:51:41 +0200: burp[12565] Last backup: 2018-05-02 08:51:36 +0200
2018-05-02 08:51:41 +0200: burp[12565] Next after : 2018-05-02 08:52:36 +0200 (interval 1m)
```

**Comment by Aisbergg** [comment]
I will check it next week and hopefully find the cause of the problem.

**Comment by Aisbergg** [comment]
I modified the `timestamp_to_long` function in `src/server/timestamp.c` like this:

```c
long timestamp_to_long(const char *buf)
{
	struct tm tm;
	const char *b=NULL;
	if(!(b=strchr(buf, ' '))) return 0;
	memset(&tm, 0, sizeof(struct tm));
	if(!strptime(b+1, DEFAULT_TIMESTAMP_FORMAT, &tm)
	  && !strptime(b+1, DEFAULT_TIMESTAMP_FORMAT_OLD, &tm))
		return 0;

	//----------------------------------------------------------------------------
	char buf2[255];
	long tlong;
	printf("### 1: %s \n", b+1);
	strftime(buf2, sizeof(buf2), "%Y-%m-%d %H:%M:%S %z", &tm);
	printf("### 2: %s \n", buf2);
	tlong = (long)mktime(&tm);
	strftime(buf2, sizeof(buf2),
		DEFAULT_TIMESTAMP_FORMAT, localtime(&tlong));
	printf("### 3: %s \n", buf2);
	//----------------------------------------------------------------------------

	return (long)mktime(&tm);
}
```

The output is:
```
### 1: 2018-05-10 16:40:47 +0200 
### 2: 2018-05-10 16:40:47 +0000 
### 3: 2018-05-10 17:40:47 +0200 
```

The time conversion doesn't work so great. Maybe there is an busybox implementation issue...

**Comment by Aisbergg** [comment]
Well, the problem persists when using Ubuntu 18.04. The function `mktime` seems to be the root of the problem. See: https://stackoverflow.com/a/12122642

I control the timezone with `/etc/localtime`. I cannot simply change the `TZ` env, because then all other times, like the logging time will be wrong.

**Comment by grke** [comment]
Are you able to try this change?

```
diff --git a/src/server/timestamp.c b/src/server/timestamp.c
index a7781f71..a8856bcf 100644
--- a/src/server/timestamp.c
+++ b/src/server/timestamp.c
@@ -74,5 +74,10 @@ long timestamp_to_long(const char *buf)
        if(!strptime(b+1, DEFAULT_TIMESTAMP_FORMAT, &tm)
          && !strptime(b+1, DEFAULT_TIMESTAMP_FORMAT_OLD, &tm))
                return 0;
-       return (long)mktime(&tm);
+printf("a: %d\n", tm.tm_isdst);
+tm.tm_isdst=-1;
+printf("b: %d\n", tm.tm_isdst);
+       long x=(long)mktime(&tm);
+printf("c: %d\n", tm.tm_isdst);
+       return x;
 }
```

And then 'make runner' and './runner'.
Somewhere in the middle of the output, it will run the code and it will look like this (the following is mine, on a system that has no problems):

```
a: 0
b: -1
c: 0
a: 0
b: -1
c: 0
```

I would be interested to see what it looks like for you.
It is possible that setting tm.tm_isdst to -1 makes the problem go away, as mktime() might then properly detect dst for you.

**Comment by grke** [comment]
The -1 thing is an idea a little bit further down on the stackoverflow you linked to.

**Comment by Aisbergg** [comment]
Setting `tm.tm_isdst=-1;` fixes the problem:

```
a: 0
b: -1
c: 1
2018-05-12 19:47:46 +0200: burp[4804] Last backup: 2018-05-12 19:47:27 +0200
2018-05-12 19:47:46 +0200: burp[4804] Next after : 2018-05-12 19:47:28 +0200 (interval 1s)
```

Question is will mktime make the right decision and get daylight savings right everytime?

**Comment by grke** [comment]
Thanks for reporting and testing.
I think that this is the best solution currently available and it works better than the existing code, so I have merged it to master.
