### ISSUE TITLE
Client config doesn't fall back to server name when ssl_peer_cn is not set

### ISSUE THREAD

**Issue by Iznohak** [grke/burp#720]
As the title says. I think the bug is in src/conffile.c, line 722 (on master branch).

	if(!get_string(c[OPT_SSL_PEER_CN]))
	{
		const char *server=get_string(c[OPT_SERVER]);
		logp("ssl_peer_cn unset\n");
		if(!server)
		{
			logp("falling back to '%s'\n", server);
			if(set_string(c[OPT_SSL_PEER_CN], server))
				return -1;
		}
	}

You probably meant to write:

		if(server != NULL)
		{
			...

Thanks.

**Comment by grke** [comment]
Hello,

Indeed, that does look wrong, I will update it soon, thank you.

**Comment by grke** [comment]
Updated in master. Thanks for reporting.
