### ISSUE TITLE
Strange code in protocol1/restore.c

### ISSUE THREAD

**Issue by melak** [grke/burp#721]
`src/client/protocol1/restore.c`
```c
 86         if(ret)
 87         {
 88                 char msg[256]="";
 89                 snprintf(msg, sizeof(msg),
 90                         "Could not transfer file in: %s", rpath);
 91                 if(restore_interrupt(asfd, sb, msg, cntr, PROTO_1))
 92                         ret=-1;
 93                 ret=0;
 94         }
 95         return ret;
```
What is this supposed to be? As far I can tell, this is pretty much equivalent to

```c
if(ret)
{
        snprintf(msg, ...);
        restore_interrupt(asfd, sb, msg, cntr, PROTO_1));
}
return 0;
```

**Comment by grke** [comment]
In your version, you have lost the error that restore_interrupt() may produce...

Double checking now, there is a problem - restore_interrupt currently always returns 0.
It should return -1 when asfd->write_str() fails. I will fix that.

**Comment by melak** [comment]
It's being lost anyway - look at 91-92-93, it's missing an "else" at the very least.

**Comment by grke** [comment]
Aha, I see what you mean.
I will fix that too, thanks for pointing this out.

**Comment by grke** [comment]
Updated in master.
