### ISSUE TITLE
[Not an issue] Display burp backups on calendar in terminal

### ISSUE THREAD

**Issue by hakong** [grke/burp#722]
I wrote a script to display burp backups on a calendar in terminal. Maybe of some use?
It's mostly a draft, and I plan on adding some more features, but works fine at the moment.
https://gist.github.com/hakong/292188fbf136df84c6d3427eb019c2d8

Will show local client backups
`./display-burp-backups-on-calendar.sh`

Will show all clients
`./display-burp-backups-on-calendar.sh all`

Will show backups from LAPTOP-hakong, DESKTOP-hakong, and DESKTOP-kvm
`./display-burp-backups-on-calendar.sh LAPTOP-hakong DESKTOP-hakong DESKTOP-kvm`

![image](https://user-images.githubusercontent.com/4422113/40887048-fdac7e2c-6731-11e8-9998-9db4daccdd51.png)
![image](https://user-images.githubusercontent.com/4422113/40887054-1c7b1a5c-6732-11e8-8d48-d229acd9304d.png)

**Comment by grke** [comment]
Oh, wow, that's good!

I use cal all the time, so I like this.

Is there a way to add it to backup_tool_script in the 2.2.x (master) branch?

**Comment by hakong** [comment]
I'm not sure what you mean, as an extra option in the script or as part of it existing function?
Either way I haven't looked at backup_tool_script and am not entirely sure what it does, and doubt I have time to dive into it.

I want to add the following features to the script sometime in the future, until then we can probably close this:
* Number of months to view (1, 2, 3 months back in time)
* Specific month to view (parse input with "date" command for flexibility)
* Client wildcards
* General cleanup and structuring

I'd like to be able to list by client OS, but at a quick glance I can't see how I can get that information.

Did you test the script? Would be cool to see screenshots of it working for someone else than me.

**Comment by grke** [comment]
Hello,

I meant an extra option in backup_tool_script, because it already does some of the things that you are doing. If it is obvious how to slot it in there, then it might be better to do that instead of having another separate script. Unfortunately, I did not write backup_tool_script, so I can't just say whether it is a good idea or not, and also lack time lack yourself.

I have tried running it, screenshots coming up.

**Comment by grke** [comment]
![2018-06-06-071302_1359x767_scrot](https://user-images.githubusercontent.com/695039/41022530-30a92ce4-69ad-11e8-933f-6c721305272b.png)
![2018-06-06-071421_1359x767_scrot](https://user-images.githubusercontent.com/695039/41022532-30e161b8-69ad-11e8-9c25-7fad0472720b.png)

**Comment by grke** [comment]
The first one, I ran with options 'grke', 'all', and nothing.
It complains about setlocale, but that is cal itself, I don't think you need to worry about that.
I don't know why 'all' did not give anything.

The second one, I edited the months to be '3' in the script, to see what would happen, and it worked.

The date '06' looks odd. I think it is highlighting it because it is the current day, and it conflicts with your highlighting somehow.

**Comment by hakong** [comment]
Strange, the highlighting works fine for me.
Can you debug and show me?

`bash -x ./display-burp-backups-on-calendar.sh all`
`bash -x ./display-burp-backups-on-calendar.sh pi`

**Comment by deajan** [comment]
I think I can easily port this into backup_tool_script if needed.

**Comment by grke** [comment]
```
root@pi:/tmp# bash -x /tmp/display-burp-backups-on-calendar.sh all
+ clients_arg=all
+ month_count=1
+ [[ all == '' ]]
+ [[ all == \a\l\l ]]
++ burp -a S
++ grep -F 'last backup: '
++ awk '{print $1}'
+ clients='do11
fumie
fumie.bak
grke
grke.net
osx
pi
sean
small
space
space2
testclient
toshiba.bak
win64'
+ for client in '$clients'
++ burp -a l -C do11
++ grep '^Backup: '
++ awk '{print $3}'
+ backups=
+ [[ '' == '' ]]
+ echo 'Whoops, no output from burp. Probably wrong client name.'
Whoops, no output from burp. Probably wrong client name.
+ exit
```

**Comment by grke** [comment]
```
root@pi:/tmp# bash -x /tmp/display-burp-backups-on-calendar.sh pi
+ clients_arg=pi
+ month_count=1
+ [[ pi == '' ]]
+ [[ pi == \a\l\l ]]
+ clients=pi
+ for client in '$clients'
++ burp -a l -C pi
++ grep '^Backup: '
++ awk '{print $3}'
+ backups='2016-06-03
2017-05-24
2017-06-21
2017-07-21
2017-08-18
2017-09-15
2017-10-13
2017-12-15
2018-01-15
2018-02-12
2018-03-18
2018-04-15
2018-05-13
2018-05-20
2018-05-27
2018-06-02
2018-06-03
2018-06-04
2018-06-05
2018-06-06
2018-06-07
2018-06-08'
+ [[ 2016-06-03
2017-05-24
2017-06-21
2017-07-21
2017-08-18
2017-09-15
2017-10-13
2017-12-15
2018-01-15
2018-02-12
2018-03-18
2018-04-15
2018-05-13
2018-05-20
2018-05-27
2018-06-02
2018-06-03
2018-06-04
2018-06-05
2018-06-06
2018-06-07
2018-06-08 == '' ]]
++ echo '2016-06-03
2017-05-24
2017-06-21
2017-07-21
2017-08-18
2017-09-15
2017-10-13
2017-12-15
2018-01-15
2018-02-12
2018-03-18
2018-04-15
2018-05-13
2018-05-20
2018-05-27
2018-06-02
2018-06-03
2018-06-04
2018-06-05
2018-06-06
2018-06-07
2018-06-08'
++ cut -d- -f1-2
++ sort -V
++ uniq
++ tail -n 1
+ months=2018-06
+ echo '==== pi ===='
==== pi ====
+ for month in '$months'
++ echo '2016-06-03
2017-05-24
2017-06-21
2017-07-21
2017-08-18
2017-09-15
2017-10-13
2017-12-15
2018-01-15
2018-02-12
2018-03-18
2018-04-15
2018-05-13
2018-05-20
2018-05-27
2018-06-02
2018-06-03
2018-06-04
2018-06-05
2018-06-06
2018-06-07
2018-06-08'
++ grep 2018-06
++ cut -d- -f3
++ sort
++ uniq
+ days='02
03
04
05
06
07
08'
++ echo '02
03
04
05
06
07
08'
++ tr '\n' '|'
++ rev
++ cut -c2-
++ rev
+ days_expr='02|03|04|05|06|07|08'
++ date --date=2018-06-01 '+%m %Y'
+ cdate='06 2018'
+ cal 06 2018
+ sed -r 's/ ([0-9]( |$))/0\1/g'
+ grep --color -EC10 '((^| )(02|03|04|05|06|07|08))'
cal: setlocale: No such file or directory
     June 2018        
Su Mo Tu We Th Fr Sa  
               01 02  
03 04 05 06 07  8 09  
10 11 12 13 14 15 16  
17 18 19 20 21 22 23  
24 25 26 27 28 29 30  
                      
```

**Comment by hakong** [comment]
Ok, fixed the first issue. Script was exiting on the first client because `burp -a l -C do11` was not returning any backups (no backups for this client?).
Still not sure about the second with the highlighted date in `cal`. Unable to reproduce it.
![image](https://user-images.githubusercontent.com/4422113/41162589-de51062c-6b25-11e8-8279-40c930f70267.png)

Can you try these three:
`cal`
`cal | sed -r 's/ ([0-9]( |$))/0\1/g'`
`cal | sed -r 's/\x5f\x08//g;s/ ([0-9]( |$))/0\1/g'`
`c=$(cal); echo "$c" | sed -r 's/ ([0-9]( |$))/0\1/g'`
`c=$(cal); echo "$c" | sed -r 's/\x5f\x08//g;s/ ([0-9]( |$))/0\1/g'`

**Comment by grke** [comment]
Yes, the highlighting on the current day is fixed.
Yes, 'all' now works.

I noticed one more thing.
I have a client that last backed up in July 2017.
For some reason, the 20 in 2017 is highlighted.

![2018-06-08-213228_376x171_scrot](https://user-images.githubusercontent.com/695039/41182019-494bbba2-6bb7-11e8-97b2-65df9b2adfcd.png)

**Comment by grke** [comment]
I guess your 'cal | sed | grep --color' needs to skip things that are not the actual day numbers

**Comment by hakong** [comment]
Yeah, I had this issue before and thought I fixed it.
I'm at the bar now, will fix later tonight or tomorrow :)
Guess it's a matter of only matching `[0-9]( |$)`

**Comment by hakong** [comment]
Can you try again now? I edited the gist.

**Comment by hakong** [comment]
Alright, updated the gist again. Should work.

**Comment by grke** [comment]
Yes, all things appear fixed.

**Comment by deajan** [comment]
@hakong, want me to integrate into backup_script_tool ?

**Comment by hakong** [comment]
Sure!

**Comment by deajan** [comment]
Okay, I have a next version scheduled anyway :)
I'll send you a gist once I'm ready.

**Comment by hakong** [comment]
![image](https://user-images.githubusercontent.com/4422113/41628859-fb43d9a0-7415-11e8-9ab7-fc2914367960.png)
Did a quick test, seems to work :)
Thanks for cleaning the script up and integrating it!

ps.
Shouldn't `$(type -p burp)` or `$(which burp)` be the default in `BACKUP_EXECUTABLE`?
![image](https://user-images.githubusercontent.com/4422113/41628927-3db89d48-7416-11e8-9e9f-ba6347c75921.png)

**Comment by deajan** [comment]
This is actually configurable in the script, and there is a note about using type -p.
Since there might be multiple burp installations on the same server, I prefered leaving a manual value by default.

Anyway, thanks for your script which comes handy.
You might want to play a bit with my script to see if it can be enhanced.

**Comment by deajan** [comment]
Calendar added in PR #740
