### ISSUE TITLE
iobuf_to_printable does not behave as expected

### ISSUE THREAD

**Issue by Iznohak** [grke/burp#723]
A simple test case to demonstrate:
- Server version 2.2.4
- Client version 2.2.2
- version_warn set to 1 on both client and server (the default)
1. Client connects to server
2. Server prints "WARNING: Client '_cname_' version '2.2.2' does not match server version '2.2.4'. An upgrade is recommended."

Expected result: client should also print "WARNING: Client '_cname_' version '2.2.2' does not match server version '2.2.4'. An upgrade is recommended."
Actual result: client prints "WARNING: w:0066:(binary data)"

The issue actually lies in is_printable (iobuf.c):
```
static int is_printable(struct iobuf *iobuf)
{
	size_t l;
	for(l=0; l<iobuf->len; l++)
		if(!isprint(iobuf->buf[l]))
			return 0;
	return 1;
}
```
which returns 0 because warning messages are terminated by a newline character ('\n'), which is not considered printable by isprint().

Possible suggested fix:
```
		if(!isprint(iobuf->buf[l]) && !isspace(iobuf->buf[l]))
```
isspace() will accept linefeed and tab characters (good), but also carriage return, form feed and vertical tab (perhaps not so good).

Or simply:
```
		if(!isprint(iobuf->buf[l]) && (iobuf->[l] != '\n'))
```
which might be too specific.

Hope this helps. Thanks.

**Comment by grke** [comment]
Thanks for pointing this out, I will try the '\n' version. :)

**Comment by Iznohak** [comment]
Actually on second thought it may not be the right way to approach the problem. This code must have worked fine for some time, and some other change must have broken it - the fix I suggested is merely a band-aid.

I don't know what is the assumed contract on messages passed between Burp client and server, but typically the lower-level layers should not contain formatting data. For human-readable messages, the presentation and display of those messages should be left up to the receiver (client or server) to decide: whether to add a newline, or to embed the text into another message, or something else...

Here the server is appending a newline to the message and the client is not expecting it. So a more correct way to fix this would be to change the routines in log.c so that THEY append the newline as necessary when they log on the host, but not when they send a message to the peer, and change the callers so that they do not append newlines to their log messages. But this would be a large change likely to break many things without extensive testing.

Another approach would be to decouple the logging from doing any communication with the peer. At a conceptual level such a mix doesn't feel right. This would allow for logging fully formatted human-readable messages on one hand, and for sending human-readable, but unformatted and codified, text messages to the peer, on the other hand. For example: WARNING VERSION-MISMATCH <client-version> <server-version>. And then the peer is free to parse and display it in any possible way (including localized version if desired). But again, this would be a large change to undertake.

Anyway, my suggested fix is probably fine for the short-term, but I wanted to share some food for thought :) Thanks.

**Comment by grke** [comment]
Hello,

Thanks for the ideas. I agree that only log.c should append newlines when logging directly on the host.
I also agree that the suggested fix is fine for now.

**Comment by grke** [comment]
Master is now updated.
