### ISSUE TITLE
http://grke.net is plaintext

### ISSUE THREAD

**Issue by hakong** [grke/burp#725]
Website does not redirect to https by default, and certificate for grke.net is issued to
```
DNS Name=burp.grke.net
DNS Name=burp.grke.org
DNS Name=meiai.com.au
```
but is missing:
```
DNS Name=grke.net
DNS Name=grke.org
DNS Name=www.grke.net
DNS Name=www.grke.org
```
I would even go as far as recommend separating plaintext from ssl using different webservers, and serving no content over plaintext, only a redirect. This prevents plaintext leaks in case of configuration mistakes.
I do this sometimes, keeps configs simpler. Run haproxy/nginx on port 80, with only a redirect and then apache on 443 😄

**Comment by grke** [comment]
Hello,

Thanks for this, but I don't need anything other than byrp.grke.net and burp.grke.org to go to https, and they do.
