### ISSUE TITLE
Fix 'burp -t' missing fields

### ISSUE THREAD

**Issue by grke** [grke/burp#726]
Some of the lines output by 'burp -t' have missing field names, fix them.

**Comment by Iznohak** [comment]
There are also configuration settings that are missing from the 'burp -t' output.
I've noticed these: librsync_max_size, hard_quota, soft_quota. They don't show in the list. There may be more.

**Comment by grke** [comment]
OK, that's interesting. Maybe they are the missing field entries.

**Comment by grke** [comment]
They are not the missing field entries, I have just not implemented the output for the CT_SSIZE_T type:

```
                case CT_SSIZE_T:
                        // FIX THIS
                        break;

```

**Comment by grke** [comment]
Fixed in master.
