### ISSUE TITLE
[Feature Req] Override config options by cmdline args

### ISSUE THREAD

**Issue by melak** [grke/burp#727]
My particular use case is I have several burp servers dropped here and there, then as my notebook is connected to a particular network (think friends, family, whatnot), backups are taken.

Currently this involves replicating the client config file basically only for changing the `server` directive in them. The situation would be much simplified if I could override `server` from the command line. There could be some other options where overriding would make sense, although browsing through my configs, there's nothing else I could think of (someone else probably will, though).

**Comment by deajan** [comment]
I think @pablodav has a powershell script that does something like that.

**Comment by pablodav** [comment]
My script https://github.com/pablodav/burp_eclient 
Doesn't change `server`, it changes speed and other settings in config before launching burp. 

The idea could be used to implement what @melak explains, but probably there are other better ways to do it too.

But I think implementing change of server based on identified network connection is not good feature to add to burp, as it could complicate things necessarily. 

The simplest way:

* Create 3 different configurations for each network
* Create 3 different schedule jobs for each config

We do this way and is a very stable one.

You can also log into different log files in this way.
The clients will work when server is reachable.

Option 2:

Setup your script that changes the server in .conf file, like burp_eclient does. 
This is not stable way, not recommended at all.

**Comment by deajan** [comment]
You may also setup a unique task which will launch a script that detects the current network (whatever fits, ping, detect subnet or else), and then launches a burp instance with a network specific configuration file, eg ```burp -c burp-network.conf``` depending on the detected network.

**Comment by grke** [comment]
Without thinking much about it, I do think it would be nice to override any config option on the command line.

Something like:
```
burp -o 'server=1.2.3.4' -o 'port=5071'
```

**Comment by grke** [comment]
Now in git master.
