### ISSUE TITLE
[Feature req] Enhanced logging

### ISSUE THREAD

**Issue by deajan** [grke/burp#728]
Hello,

When a burp backup fails, we usually get a log entry like `2018-06-14 07:23:59 +0200: burp[13710]   last good entry:    f:0046:C:/Users/user/Documents/Divers Documents/Thumbs.db` when backup is resumed later.
In the case of a very big file which will never be transmitted because of limited bandwidth, it would be very useful to have a log entry like `last tried file: f:xxxx:/some/path/to/file` whenever the server gets a network error or loses the client, so we know which file could eventually be excluded from backup.

**Comment by grke** [comment]
Nice idea, thanks.
Should be pretty easy to do.

**Comment by grke** [comment]
Done for protocols 1 and 2 in latest master.
