### ISSUE TITLE
Fix in #693 disabled blake2 protocol in librsync

### ISSUE THREAD

**Issue by deajan** [grke/burp#730]
Hello,

I currently have setup two burp test setups, one with librsync-1.0.0 server & client, and the other with librsync-2.0.2 server & client.
So far, bad news, all my tests show same speed and no improvements between both versions.
Nevertheless, I noticed that beginning with burp 2.2.2, blake2 rsync protocol is no longer used.
I dived a bit into the code and noticed https://github.com/grke/burp/commit/e3876aae17144ee17d53af96012df862a76b2256 (issue #693) which sets `#ifdef RS_BLAKE2_SIG_MAGIC` in extra_comms.c for both server and client.
Since librsync.h does not explicitly set any #define RS_BLAKE2_SIG_MAGIC but creates a typedef enum containing the magic number, blake2 protocol gets disabled.

I have recompiled current burp, removing all the  `#ifdef RS_BLAKE2_SIG_MAGIC`, and of course I get blake2 compatibility back.
I don't know how to detect the RS_BLAKE2_SIG_MAGIC number in a enum at compile time.
Since we can assume no one will ever compile burp-2.2+ on an unix having librsync < 1.0.0, how about just removing the tests for blake2 protocol ?

I've setup a quick and dirtty PR #729 for this just in case.

**Comment by grke** [comment]
Thank you.

I have pushed a change to master, for the next release.

I have made it try to compile something using RS_BLAKE2_SIG_MAGIC during configure time, which then sets HAVE_BLAKE2 if it works, and unsets it if it doesn't. Then the actual burp code looks for HAVE_BLAKE2 before attempting to use RS_BLAKE2_SIG_MAGIC.
