### ISSUE TITLE
Typo in retention doc page

### ISSUE THREAD

**Issue by gmp042** [grke/burp#734]
I believe there is a typo in the retention.html doc page. 

_This guarantees to keep 7 backups in a row, plus 4 on multiples of 7, plus 12 on **multiples of 4*12**_

After the 4 multiples of 7, 12 multiples of 4*7 are kept. Is it right?

**Comment by grke** [comment]
Thank you, I think you are right.
I will correct this for the next release. :)

**Comment by grke** [comment]
Now updated with 2.2.8 release.
