### ISSUE TITLE
[RFE] multiple definition of address option

### ISSUE THREAD

**Issue by jirib** [grke/burp#737]
It's not possible to define multiple address option in burp server conf file, thus currently burp allows us only listen on all interfaces or just one IP.

```
# burp -v 
burp-2.1.28

# grep ^address /etc/burp/burp-server.conf             
address = 192.168.1.1
address = 192.168.2.1
# burp -c /etc/burp/burp-server.conf -t | grep address 
                         address: 192.168.2.1
                  status_address: localhost
# fstat -n | grep 'burp.*internet'                     
_burp    burp       84255    0* internet stream tcp 0xffff800000b0fdc0 192.168.2.1:4971
_burp    burp       84255    1* internet6 stream tcp 0xffff800000b0f540 [::1]:4972
_burp    burp       84255    2* internet stream tcp 0xffff800000b0f760 127.0.0.1:4972
```

**Comment by grke** [comment]
Hello,
How do you expect the listening port configuration to behave?
For example, if somebody set these options:
```
address=1.1.1.1
address=2.2.2.2
port=4971
port=4972
```
Would it listen on:
```
address=1.1.1.1:4971
address=1.1.1.1:4972
address=2.2.2.2:4971
address=2.2.2.2:4972
```
or
```
address=1.1.1.1:4971
address=2.2.2.2:4972
```
?


I think the first case is intuitive.
But upon implementing it, I expect somebody will eventually ask how to configure the second case.
So, I think the second case needs new config syntax.
For example:
```
listen=1.1.1.1:4971
listen=2.2.2.2:4972
```

**Comment by jirib** [comment]
IMO the second case is right one. Maybe sshd's source could help? https://github.com/openbsd/src/blob/ce5af731b6d0313ef957df6cb6ca70746614d7e1/usr.bin/ssh/servconf.c#L2414

**Comment by grke** [comment]
Implemented it last week, now in git master. Closing.
