### ISSUE TITLE
[RFE] burp knowing last connection attempt of a client

### ISSUE THREAD

**Issue by jirib** [grke/burp#739]
I just find out that one of my clients did not do backups:

```
Jul 25 10:07:01 brq-setup CROND[31619]: (root) CMD (   /usr/sbin/burp -a t)
Jul 25 10:16:01 brq-setup anacron[31141]: Can't open temporary file for writing: No space left on device
Jul 25 10:16:01 brq-setup anacron[31141]: Aborted
```

Thus it did not even try to make connection to my burp server. Thus any server script won't be executed (eg. one informing monitoring system).

Wouldn't it be helpful to make burp to know last connection attempt of a client? We could query burp for such info and discover "disconnected" clients.

Maybe something like `utmp(5)` which remembers last login into UNIX-like system.

IIUC we could grep burp logs (those can get rotated) but IMO it could be handy to have it inside burp itself. Maybe a `wtmp`-like file in each client's directory or another format which could be `grep`  for example.

```
# ls -l /data/backup/local/burp/brq-setup/ | tail -n 3
drwxr-xr-x. 4 root root 124 Jul 25 10:34 0000118 2018-07-19 16:39:59 +0200
drwxr-xr-x. 3 root root 102 Jul 25 10:34 0000119 2018-07-25 10:33:14 +0200
lrwxrwxrwx. 1 root root  33 Jul 25 10:33 current -> 0000119 2018-07-25 10:33:14 +0200
>> here could be a file containing last connections of the client<<
```

**Comment by grke** [comment]
Nice idea, there is already a ".created" file there, and this would be similar. ".connect", maybe. But that would imply for every connection - including lists/verifies, etc. You are only interested in connections that are attempting to backup (timed or forced). I'll try to think of a name. I guess the file could get big and also cause lots of disk access if you have lots and lots of clients. Maybe it needs to be disable-able.

**Comment by jirib** [comment]
What about to have in the info: a client name, src ip, time the connection started, duration, what the connection was about (list, verify, timed backup)?

Ideally, if we could see on client info of last "login" of the same client to the server. Like SSH does.

**Comment by deajan** [comment]
There is the backup_tool_script which runs on server, and checks for last succesful backups of clients.
When last successful backup is older than n days, it will send an email directly to a client configured address, or to an admin. This could mitigate your problem.

**Comment by grke** [comment]
In master, I have implemented a file in each server side client directory called '.command', and it lists the commands that a client asked the server to run. It has this info:

time address client command

I think this achieves the requested feature.
Here is a sample:

``` 
2019-06-15 06:07:11 +0000 127.0.0.1 testclient c:0006:list :
2019-06-15 06:07:23 +0000 127.0.0.1 testclient c:000C:backupphase1
2019-06-15 06:08:21 +0000 127.0.0.1 testclient c:000C:backupphase1
2019-06-15 06:08:23 +0000 127.0.0.1 testclient c:0009:verify 0:
2019-06-15 06:08:34 +0000 127.0.0.1 testclient c:0010:verify 0:asdfsdf
2019-06-15 06:08:54 +0000 127.0.0.1 testclient c:0011:restore 0:asdfdsf
2019-06-15 06:09:03 +0000 127.0.0.1 testclient c:0011:backupphase1timed
2019-06-16 10:43:05 +0000 127.0.0.1 testclient c:0006:list :
2019-06-16 10:43:23 +0000 127.0.0.1 testclient c:0006:list :
2019-06-16 10:43:39 +0000 127.0.0.1 testclient c:000A:restore 0:
```

The client name can differ in the same file, because it might be a restoreclient that connected and ran the command.

**Comment by ziirish** [comment]
Does this log monitor commands as well?

**Comment by deajan** [comment]
Just to add my 2 cents, there's already a last client backup connection timestamp in the statistics JSON interface, ie:
```
```
"number": 18,
                    "timestamp": 1557479613,
                    "flags": [
                        "working"
                    ],
```
 
Where working suggests that a client connected but didn't finish the backup.

**Comment by grke** [comment]
Hello,

The new feature doesn't log monitor commands.
