### ISSUE TITLE
backup_script_pre option in man page should talk about script return code

### ISSUE THREAD

**Issue by jirib** [grke/burp#742]
It's not clear from man page what will happen if backup_script_pre does not return 0. One has to do his own test or read src of burp.

This part in man page should be improved.

https://github.com/grke/burp/blob/master/manpages/burp.8.in#L595

**Comment by ziirish** [comment]
Hello,

I suppose you either did some tests or read the source code so would you mind sharing what the expected documentation should be?

It would be even better if you could provide us with a pull request.

Thanks

**Comment by jirib** [comment]
Right but I'm not sure about src, I'm not good reading C. But IIUC it does not continue to do_backup_client, https://github.com/grke/burp/blob/94675f3099136e0e4221987c7038dac9240205aa/src/client/main.c#L140. My test was done with a shell script with `false`.

**Comment by grke** [comment]
It treats it as an error, and doesn't backup.
The logic being, if your pre-script failed, then presumably your data is not ready to be backed up.
