### ISSUE TITLE
Insufficient buffer size in maybe_write_first_created_file

### ISSUE THREAD

**Issue by qm2k** [grke/burp#744]
Function [`maybe_write_first_created_file(...)`](https://github.com/grke/burp/blob/ecfc6c5153ee67b889666fc5fb6b37718ba88366/src/server/run_action.c#L403) writes timestamp with truncated timezone due to too insufficient buffer size. Need to bump `tstmp` size by at least 2 bytes.

Truncation itself occurs in [`timestamp_write_to_buf(...)`](https://github.com/grke/burp/blob/d60427d0721cdee9509ee6ce7ce367691dc8d65b/src/server/timestamp.c#L48), looks like there's no buffer overrun. I checked [other](https://github.com/grke/burp/blob/dd2fd8c7bf6a09f48c0b13060ffadad6eebea1b4/src/server/sdirs.c#L101) [two](https://github.com/grke/burp/blob/f1b1eb6f7ece6a0914772161b235ba006538071e/src/server/rubble.c#L25) places it is being used at, buffer is larger there.

(Probably caused by combination of #563 and #564. Since I requested both features, I ought to have tested it earlier, sorry. Didn't think upgrading our deployment would take so long.)

**Comment by grke** [comment]
Thanks for reporting, I will fix it for the next release.

**Comment by grke** [comment]
Fixed in master now.
