### ISSUE TITLE
burp should warn every time it can't read a file

### ISSUE THREAD

**Issue by deajan** [grke/burp#758]
Hello,

I'm currently trying some corner case burp scenario in Windows, where a backup fails with:
```
2018-09-07 15:45:35: burp[3584] Phase 1 end (file system scan)
2018-09-07 15:45:35: burp[3584] Phase 2 begin (send backup data)

2018-09-07 15:45:39: burp[3584] WARNING: Could not open L:/GED: A required privilege is not held by the client.

2018-09-07 15:45:39: burp[3584] WARNING: Could not open f:0006:L:/GED
2018-09-07 15:45:39: burp[3584] WARNING: Could not open L:/GED/test: A required privilege is not held by the client.

2018-09-07 15:45:39: burp[3584] WARNING: Could not open f:000B:L:/GED/test 
```

The failure is supposed to happen in my tests (missing permissions).
What bugs me here is that the file manifest shows the file being backed up, and I can restore those files too (indeed they have a size of zero octets).

This leads to every backup that happened after that one not complaining anymore since file comparaisons show identical zero length files, even if the file contains data.

Shouldn't situations like this trigger warnings every time ?

(Issue can be easily reproduced by removing ntfs extended permissions read, or by trying to backup a network share mapped as drive).

**Comment by grke** [comment]
Yeah, I think the bug is that it shouldn't create 0 length files in the manifest, it should warn and have nothing, so next time it will see the files as new.

**Comment by grke** [comment]
Hello,

I have been trying to remove the extended permissions read thing, but I cannot reproduce the behaviour you describe.
Here is what I did:

I have a directory on a Windows machine with a file in it.

I right-click the file -> properties.
Security tab -> Advanced button
A new window appears, I have three rows: Allow System, Allow Administrators, Allow Users.
For each one of these:
Change permissions, a new Window pops up, looks the same as the last one, but I can choose 'edit'. I can click a box for 'deny' 'Read extended attributes'. I 'OK' everything.
I will attach a screenshot showing the permissions I have.

I then start a cmd.exe permissions with 'run as administrator', and run 'burp.exe -a b' by hand.
It backs up all the files without any warnings. The file that I tried to deny permissions on is backed up fine, the burp server's version has the contents of it.

**Comment by grke** [comment]
![2018-09-15-053631_1161x768_scrot](https://user-images.githubusercontent.com/695039/45583006-65441f00-b8fd-11e8-8b6e-07ce63571121.png)

**Comment by grke** [comment]
So, do you have some more detailed instructions on how to reproduce the issue? Also, what burp version are you using?

**Comment by grke** [comment]
Something similar was happening on Linux, described here: https://github.com/grke/burp/issues/763
There is a fix for that issue in 2.2.12.
I think it fixes this issue too.
If it does not, let me know and we'll reopen this issue.

**Comment by deajan** [comment]
Indeed version 2.2.12 works for me :)
Also, I've tried some ugly scenarios to trigger a test where burp could not backup but won't warn, and well...humm... it seems that you fixed #165 somehow too...
I could backup and restore files that were on a windows network share (using protocol 1 & 2), hence... no warnings neither.

**Comment by grke** [comment]
That's good, but also strange!
Which version of Windows are you using?
I should get around to trying a network drive backup again, to check what is going on.

**Comment by deajan** [comment]
Win10 1803 x64.
Previous tests were made with burp 2.2.4, with bad ACL and/or network shares.
Now tests with burp 2.2.12 work for both cases.
Of course the network share is mounted as the same user running burp.
