### ISSUE TITLE
burp-2.1.32 | timer_arg

### ISSUE THREAD

**Issue by jacky35** [grke/burp#761]
Hello,
if I set the variable "timer_arg" to 1 second, the value does not seem to be taken into account.

burp[1679]: Running timer for poste999
burp[1679]: In timeband: Mon,Tue,Wed,Thu,Fri,00,01,02,03,04,05,11,12,16,17,18,19,20,21
burp[1679]: Out of timeband: Sat,Sun,00,01,02,03,04,05,06,07,08,17,18,19,20,21,22,23
burp[1679]: Last backup: 2018-09-21 18:33:39 +0200
burp[1679]: Next after : 2018-09-21 19:33:40 +0200 (interval 1s)

He still needs a delay of one hour is normal?

burp-2.1.32

**Comment by grke** [comment]
Hello,
What happens if you set it to 1 hour?
Does it go two hours in the future?

**Comment by jacky35** [comment]
burp[3335]: Last backup: 2018-09-24 09:49:25 +0200
burp[3335]: Next after : 2018-09-24 10:49:26 +0200 (interval 1s)

burp[3351]: Last backup: 2018-09-24 09:49:25 +0200
burp[3351]: Next after : 2018-09-24 11:49:25 +0200 (interval 1h)

burp[3347]: Last backup: 2018-09-24 09:49:25 +0200
burp[3347]: Next after : 2018-09-24 12:49:25 +0200 (interval 2h)

**Comment by grke** [comment]
Hello,
I think that this is a DST issue, and it was fixed in burp 2.2.4.

**Comment by jacky35** [comment]
yes that seems good

burp[1769]: Last backup: 2018-09-24 16:15:12 +0200
burp[1769]: Next after : 2018-09-24 16:15:13 +0200 (interval 1s)

**Comment by grke** [comment]
Cool, thanks for testing and reporting.

Also, if you need to stay on some older version, you may try using the external timer_script, which probably doesn't have this bug. Just add this to your burp-server.conf:
```
timer_script = /usr/share/burp/scripts/timer_script
```

Now closing.
