### ISSUE TITLE
server should not create 'directory' for backup client

### ISSUE THREAD

**Issue by jirib** [grke/burp#764]
IMO server should not create 'directory' for clients, eg. the "parent" directory where there is a subdir named based on 'cname'.

IMO this should be either done by a package mgmt sw (eg. part of EL/Fedora .spec) or manually by administrator.

Why?

A mistake/forgotten change - eg. cloning burp server to different host with different directory layout - could cause burp server creating such 'directory' and putting client's data into unintended location => filling filesystem.

Repro steps:

1. create a client on server
2. define directory either in server conf or clientconfdir/<cname> which does not exist
3. run backup on client

The result is burp would happily create whole path.

```
# rpm -q burp
burp-2.1.32-1.el7.x86_64

# grep ^directory /etc/burp/clientconfdir/t470s
directory = /1/2/3/4/5
```

```
burp -a b
...
```
```
# find /1/
/1/
/1/2
/1/2/3
/1/2/3/4
/1/2/3/4/5
/1/2/3/4/5/t470s
/1/2/3/4/5/t470s/.created
/1/2/3/4/5/t470s/lockfile
/1/2/3/4/5/t470s/0000001 2018-10-04 00:29:44 +0200
/1/2/3/4/5/t470s/0000001 2018-10-04 00:29:44 +0200/phase1.gz.tmp
/1/2/3/4/5/t470s/0000001 2018-10-04 00:29:44 +0200/timestamp
/1/2/3/4/5/t470s/0000001 2018-10-04 00:29:44 +0200/log
/1/2/3/4/5/t470s/0000001 2018-10-04 00:29:44 +0200/incexc
/1/2/3/4/5/t470s/working
```

Logging could also be better, there's no info about burp creating whole directory path.

```
...
Oct  4 00:29:44 host1 burp[5041]: Connect from peer: 192.168.1.6:31214
Oct  4 00:29:44 host1 burp[5041]: 0/5 child processes running on port 4971
Oct  4 00:29:44 host1 burp[5041]: Child 1 available
Oct  4 00:29:44 host1 burp[5041]: forked child on port 4971: 5693
Oct  4 00:29:44 host1 burp[5693]: auth ok for: t470s
Oct  4 00:29:44 host1 burp[5693]: Client t470s does not want a certificate signed
Oct  4 00:29:44 host1 burp[5693]: SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
Oct  4 00:29:44 host1 burp[5693]: Server is using protocol=0 (auto)
Oct  4 00:29:44 host1 burp[5693]: Client supports being sent json counters.
Oct  4 00:29:44 host1 burp[5693]: Client has set protocol=1
Oct  4 00:29:44 host1 burp[5693]: in do_backup_server
Oct  4 00:29:44 host1 burp[5693]: Using librsync hash blake2
Oct  4 00:29:44 host1 burp[5693]: Logging to /1/2/3/4/5/t470s/0000001 2018-10-04 00:29:44 +0200/log
Oct  4 00:30:04 host1 burp[5041]: pipe from child: end of data
Oct  4 00:30:04 host1 burp[5041]: pipe from child: disconnected fd 6
Oct  4 00:30:04 host1 burp[5693]: exit child
...
```

**Comment by jirib** [comment]
I would expect nice log message and failure.

**Comment by grke** [comment]
Hello,

IMO, I think that the current behaviour is fine.

**Comment by grke** [comment]
...because it is very easy to correct the administration mistake that you describe, and IMO, burp being obstructive because somebody possibly doesn't know what they really want does not outweigh the benefit of just doing what was requested.
