### ISSUE TITLE
exclude_dir_regex

### ISSUE THREAD

**Issue by jacky35** [grke/burp#771]
Hello,
Can you add the exclude_dir_regex feature in Burp.

Thank you very much for your time and a very good day.

Jacky

**Comment by grke** [comment]
Hello,

Sorry for taking so long to get back to you on this. I was very busy with making difficult security patches. 

Are you able to describe exactly what you want this feature to do, and how you would use it?

Thank you.

**Comment by grke** [comment]
No response, closing.
