### ISSUE TITLE
Empty action in server_post_script

### ISSUE THREAD

**Issue by C-Otto** [grke/burp#775]
The actions I receive in my server_post_script can be "backupphase1timed" for "timer conditions not met" and "backupphase1timedcheck" both for met and unmet timer conditions, but never "backupphase1timed" for a successful backup. Instead, after a backup, the action is just the empty string.

Moreover, for "burp -a l" in the client (listing the backups), the action also is the empty string, making it hard to determine whether a backup actually was performed.

Empty string for -b, -t (if backup is performed), -l, -L, -d, no script invocation for -e (which is OK).

burp-2.0.54 (Debian)

**Comment by grke** [comment]
Fixed in master.
Thanks for reporting.
