### ISSUE TITLE
Brup-2.2.12 installation issue

### ISSUE THREAD

**Issue by leonderosario** [grke/burp#778]
Hello, I need some help installing Burp 2.2.12. I've upgraded from 2.1.32 on a Debian 9 distro but the daemon on the new version is not starting. I tried manually but not working. Is there any documentation to read about installation issues?
Thanks

**Comment by ziirish** [comment]
Hello,

How did you install it? By compiling it from sources? Using a package?

**Comment by leonderosario** [comment]
Hello ziirish, thanks for your quick response. I used the file in https://sourceforge.net/projects/burp/files/burp-2.2.12/, decompress it and followed the README instructions. I did it twice because first I used the make install-configs and, because it didn't start then I installed again using make install-all but nothing.

**Comment by ziirish** [comment]
So you said it didn't work manually either. What command did you run?

**Comment by leonderosario** [comment]
After installation, I ran:
#burp -c "/etc/burp/burp-server.conf"

and no process was started in the system monitor. Also I tried #burp -a s with the following output:

# burp -a s
2018-11-26 14:39:24 -0300: burp[6813] Connecting to localhost:4972.
2018-11-26 14:39:24 -0300: burp[6813] could not connect to localhost:4972.
2018-11-26 14:39:24 -0300: burp[6813] status_client_ncurses exiting with error: -1

I didn't have this issue when installing 2.0.54 neither 2.1.32

**Comment by ziirish** [comment]
Ok, I may have an idea then. Since 2.2.10 or something the `address`, `port`, `status_address` and `status_port` have been replaced respectively with `listen` and `listen_status`.

So you may want to edit your server config accordingly with something like:

```
listen = 0.0.0.0:4971
listen_status = 127.0.0.1:4972
```

**Comment by leonderosario** [comment]
Ziirish,

Yes, the problem was there. While "listen"  was already setup in burp-server.conf, the "listen_status" was not. So, that line was not activated during installation. Thanks, now server is working again.

I have another question regarding changing server hardware and certificates but I think I should open another ticket, correct?

**Comment by ziirish** [comment]
Yes, the prefered way to ask questions is to send an email to the burp-users mailing list. It is hosted on sourceforge as well.
