### ISSUE TITLE
burp return codes

### ISSUE THREAD

**Issue by zhavranek** [grke/burp#781]
Hello, what are burp client return codes? Man page (https://burp.grke.org/docs/manpage.html) describe value 0..4 and my linux burp-2.1.32 exit with 0 or 2 or 134 or 139.

**Comment by deajan** [comment]
Exit codes 134 and 139 should be system related (eg: 139 is SIGSEGV segmentation fault).
You should check your syslog.

**Comment by grke** [comment]
Yes, high numbers like that are things like segfaults.
