### ISSUE TITLE
Visibility problem in server/bu_get.c (new in 2.2.14)

### ISSUE THREAD

**Issue by melak** [grke/burp#783]
FreeBSD 11.2:
```
  CC     src/server/main-bu_get.o
src/server/bu_get.c: In function 'do_bu_get_list':
src/server/bu_get.c:178:10: warning: implicit declaration of function 'scandir'; did you mean 'fchdir'? [-Wimplicit-function-declaratio]
    && (n=scandir(dir, &dp, filter_dot, alphasort))<0)
          ^~~~~~~
          fchdir
src/server/bu_get.c:178:40: error: 'alphasort' undeclared (first use in this function)
    && (n=scandir(dir, &dp, filter_dot, alphasort))<0)
                                        ^~~~~~~~~
src/server/bu_get.c:178:40: note: each undeclared identifier is reported only once for each function it appears in
*** Error code 1
```
Looking at `dirent.h`:
```c
#if __POSIX_VISIBLE >= 200809 || __XSI_VISIBLE >= 700
int      alphasort(const struct dirent **, const struct dirent **);
int      dirfd(DIR *);
#endif
```
This appears to be needing a `-D_XOPEN_SOURCE=700` added to the compile flags (having added this to `bu_get.c` made compile proceed and ultimately succeed).

Having looked at OpenBSD and DragonFlyBSD, `scandir` and `opendir` are guarded only by `#if __POSIX_VISIBLE >= 200809`, which should also be fixed by adding `-D_XOPEN_SOURCE=700` to the compile flags.

**Comment by grke** [comment]
Hello,
Are you able to try out this patch?

```
diff --git a/src/burp.h b/src/burp.h
index 87a82dda..a3b105ee 100644
--- a/src/burp.h
+++ b/src/burp.h
@@ -12,6 +12,13 @@
 #define _POSIX_PTHREAD_SEMANTICS 1
 #define __STDC_FORMAT_MACROS 1
 
+#if defined(HAVE_DRAGONFLY_OS) || \
+    defined(HAVE_FREEBSD_OS) || \
+    defined(HAVE_NETBSD_OS) || \
+    defined(HAVE_OPENBSD_OS)
+       #define _XOPEN_SOURCE 700
+#endif
+
 // System includes.
 #include <inttypes.h>
 #include <ctype.h>

```

**Comment by melak** [comment]
```diff
diff --git a/src/burp.h b/src/burp.h
index 87a82dda..6b411aa3 100644
--- a/src/burp.h
+++ b/src/burp.h
@@ -12,6 +12,16 @@
 #define _POSIX_PTHREAD_SEMANTICS 1
 #define __STDC_FORMAT_MACROS 1
 
+#if defined(HAVE_DRAGONFLY_OS) || \
+    defined(HAVE_FREEBSD_OS) || \
+    defined(HAVE_NETBSD_OS) || \
+    defined(HAVE_OPENBSD_OS)
+       #if defined(_XOPEN_SOURCE) && _XOPEN_SOURCE < 700
+               #undef _XOPEN_SOURCE
+       #endif
+       #define _XOPEN_SOURCE 700
+#endif
+
 // System includes.
 #include <inttypes.h>
 #include <ctype.h>
```
This makes compilation warning-free (in this regard) on FreeBSD at least, I suppose it is defined something less than 700 (didn't check).

Yep, this looks like the solution, cheers!

**Comment by grke** [comment]
Both the changes above actually break my automatic testing environment, so I am not going to make this change until I can figure out why.

**Comment by grke** [comment]
Hello,

My automatic testing environment was on some old version of FreeBSD (8 or 9, I think).

So I have updated it to FreeBSD 12 - it is the official Amazon AMI for that version.

However, I have not been able to reproduce the problem that you report. I only had unrelated compiler warnings that I have now fixed. Everything works cleanly.

I am therefore closing this issue.
