### ISSUE TITLE
Bad condition in fsops.c:filter_dot()

### ISSUE THREAD

**Issue by melak** [grke/burp#784]
https://github.com/grke/burp/blob/ab2c86c2da971f11ac4094575dadcd7dc586239d/src/fsops.c#L441-L448

As flagged by Clang, `address of array 'd->d_name' will always evaluate to 'true'`, I suppose this was meant to be`if(d && d->d_name && (...))` or some other suitable variation on this theme?

**Comment by grke** [comment]
Fixed in master.
