### ISSUE TITLE
2.2.16 burp client on windows system not correct restore direcotory name with Chinese charset

### ISSUE THREAD

**Issue by imweijh** [grke/burp#797]
Testing with one directory and 2 files in it.
![image](https://user-images.githubusercontent.com/23710675/52864194-96f33780-3174-11e9-97ec-7ee39c7f64d2.png)

![image](https://user-images.githubusercontent.com/23710675/52864592-6cee4500-3175-11e9-96c1-8a1857c33b0a.png)

burp list the backup,filename not correct display
![image](https://user-images.githubusercontent.com/23710675/52864739-c8203780-3175-11e9-9731-b023761b30ca.png)

burp restore
![image](https://user-images.githubusercontent.com/23710675/52864828-00c01100-3176-11e9-9127-451d87d0113b.png)

Get 2 dirs with one has the wrong name(in fact we has only one dir when backup) .
![image](https://user-images.githubusercontent.com/23710675/52864892-2cdb9200-3176-11e9-83a6-e8c162271b1c.png)
![image](https://user-images.githubusercontent.com/23710675/52866104-f2bfbf80-3178-11e9-9ee6-887f2341c226.png)

On burp server the directory and file name is OK.
![image](https://user-images.githubusercontent.com/23710675/52865061-98256400-3176-11e9-8c4d-fa7b249f4698.png)

I think on windows we need convert the unicode to the locale MBCS (here is cp936) when restore the filename.

**Comment by grke** [comment]
OK, how do I convert the unicode to the locale MBCS on Windows?

**Comment by imweijh** [comment]
Hi,maybe these?
https://github.com/grke/burp/issues/168#issuecomment-323510230
https://stackoverflow.com/questions/1525456/converting-unicode-to-multibyte

**Comment by imweijh** [comment]
![image](https://user-images.githubusercontent.com/23710675/52896058-7b803f00-31fd-11e9-8b3a-bb5bc895f804.png)

![image](https://user-images.githubusercontent.com/23710675/52896066-8c30b500-31fd-11e9-95f7-974c08b55426.png)

![image](https://user-images.githubusercontent.com/23710675/52896045-5f7c9d80-31fd-11e9-85e5-bda65793f38a.png)

more screenshot

**Comment by imweijh** [comment]
burp client 1.4.40 restore chinese dir no problem. 
1.4.40  burp list have the same problem,but restore is OK.

**Comment by grke** [comment]
When you say 2.1.32 and 1.4.40 restore with no problems, are you changing the client side, or the server side, or both?

**Comment by grke** [comment]
If 2.1.32 is really OK, it shouldn't be too difficult to diff between the two versions and find what changed.

**Comment by imweijh** [comment]
> When you say 2.1.32 and 1.4.40 restore with no problems, are you changing the client side, or the server side, or both?

server side is 2.2.16.
just use different client version.

**Comment by grke** [comment]
Hello,

I think the problem probably started in 2.2.14.
Are you please able to check the 2.2.12 client, to see if it works OK?
https://burp.grke.org/downloads/burp-2.2.12/
If you can confirm that, I think I know the exact patch that made this start happening.

Thank you for helping.

**Comment by imweijh** [comment]
> Hello,
> 
> I think the problem probably started in 2.2.14.
> Are you please able to check the 2.2.12 client, to see if it works OK?
> https://burp.grke.org/downloads/burp-2.2.12/
> If you can confirm that, I think I know the exact patch that made this start happening.
> 
> Thank you for helping.

Hi,
Comfirmed, client version '2.2.12' is OK,
restore no problem.

**Comment by grke** [comment]
Hello,

Sorry, I am having trouble reproducing the problem.

Are you able to tar or zip the backup directory (/var/spool/burp/<client>) of your original test case, and attach it to this issue?

Then I can copy it to my backup server and try to reproduce exactly what you are seeing.

**Comment by imweijh** [comment]
Hello,
I upload testdata to https://github.com/imweijh/helloworld/blob/master/burpdata.tgz

**Comment by grke** [comment]
Hello,

Thanks!
I can now reproduce the problem, exactly what you are seeing.
I will try to fix it, but I'm not sure how long it will take - fixing Windows problems often takes a lot of time.

**Comment by imweijh** [comment]
Thanks, glad if I can help.

**Comment by grke** [comment]
Hello,

I had to fight really really hard for a few hours, but I think I have a fix.
Are you able to test this Windows client, please?

https://burp.grke.org/downloads/test/burp-win64-installer-2.3.1.exe

**Comment by imweijh** [comment]
![image](https://user-images.githubusercontent.com/23710675/53102698-30508e00-3567-11e9-8e18-6a1aff30704c.png)

No problem, client 2.3.1 works like a charm
Thanks.

**Comment by grke** [comment]
I will probably do a 2.2.18 release with this fix, and I will include your test files/directories in the automated tests.

**Comment by imweijh** [comment]
![image](https://user-images.githubusercontent.com/23710675/53218849-b6202680-3698-11e9-9de4-4c058c963d91.png)
Hi,
About the action "list" display mess characters, could I open a new issue?

**Comment by grke** [comment]
I don't think it is different to https://github.com/grke/burp/issues/168

**Comment by imweijh** [comment]
> I don't think it is different to #168

OK. 
Google find this
https://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using

glad if I can help.

**Comment by grke** [comment]
OK, issue 797 is now fixed in master, and 2.2.18 is also released, with this fix.
Thanks for your reporting and your help!
