### ISSUE TITLE
Help on regex

### ISSUE THREAD

**Issue by deajan** [grke/burp#799]
Hello,

I'm currently improving my burp incexec files found at https://github.com/deajan/linuxscripts/tree/master/burp/incexc, and would need a little help with the regex.

First of, this ruleset triggers the following in my logs:
```
Feb 22 09:00:04 stm burp[16082]: unknown escape sequence '\$' in config 'exclude_regex = "[A-Z]:/\$recycle.bin"' - treating it as '$'
```
I think this rule comes directly with burp default config client side where I copied it from.

Also, I'd need to understand if doublequotes are needed, eg if the following two lines are equivalent or not:
```
exclude_regex=^[A-Z]:/\$recycle\.bin$
exclude_regex="^[A-Z]:/\$recycle\.bin$"
```

In the end, what kind of regex are usable ? POSIX ? Perl ? with extensions ?
Could you please help me out ? I'm willing to improve the doc for it once I understood it well enough :)

**Comment by grke** [comment]
The windows client is currently using https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.bz2

The 'unknown escape sequence' message is coming from inside of burp's conf file parsing mechanism, in a function called 'remove_quotes()'. If you do not put quotes around the regex, as it is in the default windows burp.conf, then that log message will not come out, and the regex will be compiles exactly as it appears:
```
exclude_regex=^[A-Z]:/\$recycle\.bin$
```

**Comment by deajan** [comment]
Thank you alot, I'll rewrite my rules and test them again :)

**Comment by deajan** [comment]
Updated a lot of rules, and I begin to have a quite okay ruleset I hope.
Is there anywhere I could share this at the burp project so users could be aware it exists and hopefully improve it  ?
https://github.com/deajan/linuxscripts/tree/master/burp/incexc

**Comment by grke** [comment]
Possibly, mention it in the burp github wiki? Link at the top of the page.

**Comment by deajan** [comment]
Done, thanks :)
