### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Djam94800** [grke/burp#804]
Hello,

We have a problem when backing up to Windows via WSL.
We can mount our network drives, navigate inside, copy, read and write. No problem.
But when Burp tries a backup, we have the following error:

`burp[8640] WARNING: Could not open directory /mnt/i/scripts: Permission denied`

Burp version : 2.2.18

Help please.

DG

**Comment by grke** [comment]
Hello,

I have never used this WSL thing.

Are you trying to backup /mnt/i/scripts (ie, on the client), or is that where you are trying to save the backup (ie, on the server).

If /mnt/i/scripts is on the server, what user is the server-side burp running as?
Does that user have permissions for /mnt/i/scripts?
   
If /mnt/i/scripts is on the client, what user is the client-side burp running as?
Does that user have permissions for /mnt/i/scripts?

**Comment by Djam94800** [comment]
That's fine "/mnt /i/scripts" that I want to backup. 
This is a mounted share (drvfs).

I can read and write files.

In fact / mnt / i is a network drive on windows. and to access this one, I am riding it under wsl via (drvfs). So since wsl I have good access to files.

**Comment by Djam94800** [comment]
With burp 2.0.54 

`2019-03-21 09:16:31: burp[86] WARNING: Could not open /mnt/i/scripts/GROUPpolicies.reg: Permission denied
2019-03-21 09:16:31: burp[86] WARNING: Could not open /mnt/i/scripts/InstallV2.bat: Permission denied
2019-03-21 09:16:31: burp[86] WARNING: Could not open /mnt/i/scripts/Intranet.msc: Permission denied`

**Comment by Djam94800** [comment]
Thanks

**Comment by grke** [comment]
Did you solve it? What was the solution?

**Comment by Djam94800** [comment]
In fact I left a clean installation under Linux.

Thanks
