### ISSUE TITLE
[RFC] nobackup semantics

### ISSUE THREAD

**Issue by melak** [grke/burp#815]
`nobackup` currently is "If this file system entry exists, the _directory_ containing it will not be backed up" (emphasis mine).

Would it not make sense to change this to "the _contents_ of the directory will not be backed up, _but the directory itself will be_"?

I think this mostly speaks for itself. One wouldn't want to back the contents of `/tmp` up, but `/tmp` itself is quite necessary; or maybe things like antivirus definition files - there's little point in backing them up as they get downloaded afresh after a restore, but you'd still need the directory itself to exist (or database data directories, or what have you).

Thoughts?

**Comment by grke** [comment]
Hello,
It makes sense to me, and is an easy change.
I will try to do this for the next release.

**Comment by grke** [comment]
Now in master.
