### ISSUE TITLE
Wrong time (off by one) shown in -a S

### ISSUE THREAD

**Issue by C-Otto** [grke/burp#819]
On my server when running burp -a S I see this line:

`hostname           idle  last backup: 0001710 2019-07-17 22:40:43 +0200`

The current time is 2019-07-17 21:59:00 +0200, which is before the time shown above.

The log file indicates 21:40:43 instead of 22:40:43.

The time is configured correctly on both systems.

burp 2.1.32 (Debian 11)

**Comment by grke** [comment]
Hello,

This was most likely fixed in 2.2.4, and the recommended version is 2.2.18.

If it is still a problem for you in 2.2.18, you can reopen the issue.

Thank you.

**Comment by C-Otto** [comment]
Seems to be a duplicate of #714. Thanks.
