### ISSUE TITLE
[Off topic] iSCSI recovery and burp backups

### ISSUE THREAD

**Issue by deajan** [grke/burp#824]
Hello,

I'm using iSCSI instead of nfs shares for burp storage in order to gain performance, given the fact that nfs is slow for small files.
So far so good, I ran into a couple of problems, and would like to discuss them with other burp users here:

My problems:

1. Issue: Network shares
Let's say I mount an iSCSI (or nfs) share on my burp server as /burp-data
If the share isn't mounted (network problem or else), burp would write a new backup (0000001) in the mountpoint itself.
1.  Solution
In order to prevent that, my burp server runs as user `burp`.
Mountpoint /burp-data is `drwx------.  9 root root`
Once mounted /burp-data becomes `drwx------.  9 burp burp`
This should prevent burp writing new backups. It will only complain about not being permitted to mkdir.

2. iSCSI read only mounted drive after network outage
My second problem is a bit uglier, and so far I didn't find a good solution.
Once in awhile, I find my iSCSI network drive mounted as read only, especially after a NAS reboot or network outage.

As for now, I have an ugly script running via cron every 10 minutes, which checks the iSCSI session and the mountpoint being RW:
```
#!/usr/bin/env bash

portal="isci_server_ip:3260"
iqn="iqn.2019-08.local.server"
mountpoint="/burp-data"

function iscsi_login {

        # Check session, if not established, login
        iscsiadm -m session | grep "$iqn"
        if [ $? -ne 0 ]; then
                umount "$mountpoint"
                iscsiadm -m node -T "$iqn" -p "$portal" --login
        fi
}

function iscsi_mount {
        # Check if mounted as rw, if not, login and remount
        mount | grep "$mountpoint" | grep "rw,"
        if [ $? -ne 0 ]; then
                umount "$mountpoint"
                iscsi_login
                mount "$mountpoint"
        fi
}

iscsi_mount
```

Indeed it would not be able to remount my iSCSI share if the filesystem isn't clean, and at this point I'd rather not run an xfs_repair or fsck automatically.
Anyway, I think this solution is an ugly workaround.

Any of you guys having burp setups with remote storage ?
What are your solutions ?

Best regards.

**Comment by grke** [comment]
Hello,
Sorry, I don't have remote storage.
You may get more responses for this on the burp-users list?

**Comment by deajan** [comment]
Thanks, I'll do so, in the meantime please allow me to keep that issue open for the next two weeks.

**Comment by grke** [comment]
Yes, no problem at all with that.

**Comment by trustchk** [comment]
I'm currently testing a setup where burp is managed by pacemaker on top of ZFS that sits on a shared FibreChannel storage (still SCSI, just not over ethernet). So for example, pacemaker stops burp if the filesystem fails and doesn't start it if the filesystem can't be "started". I suppose there could be ways to do that via systemd magic, too.
Anyway, a pre script run by the burp server checks if the clients backup directory exists and aborts it it can't be found (I'm creating it via scripts outside of burps view). The script simply exits non-zero if it isn't satisfied. In your case, you could try to create a file or write a timestamp to an existing one, and if that doesn't work simply exit non-zero and burp aborts.
I haven't gone the full way of monitoring the system yet, though. We plan on using icinga or prometheus, at least for icinga there are checks that show if a filesystem is mounted "ro".

**Comment by deajan** [comment]
Thanks, monitoring my system is already done (via backup_tool_script which is run by my supervision tool), but preventing burp from issuing the backup on storage failure via the `server_script_pre` directive is indeed a brilliant idea.

A quick and dirty pre script could then look like
```
#!/usr/bin/env bash

set -o pipefail

mount | grep 'mymountpoint' | grep 'rw,'
exit $?
```

I'll try to play with that. Thanks again.

**Comment by grke** [comment]
Hello,
Do you still want this to stay open?

**Comment by deajan** [comment]
Thanks for your patience ;)
Guess I got what I need.
