### ISSUE TITLE
End-of-line comments/trailing comments # like this not fully supported.

### ISSUE THREAD

**Issue by BlessDeix92** [grke/burp#828]
Currently, burp does not appear to support end-of line comments as I would have expected.

Example I tested with:

ssl_dhfile = /etc/burp/dhfile.pem # TEST end of line comments

And then I restarted my burp server and got this in my syslog:

Aug 19 22:45:02.504024 myhost systemd[1]: Stopped burp backup server.
Aug 19 22:45:02.510013 myhost systemd[1]: Starting burp backup server...
Aug 19 22:45:02.522470 myhost burp[17571]: Creating /etc/burp/dhfile.pem # TEST end of line comments
Aug 19 22:45:02.522498 myhost burp[17571]: Running '/usr/sbin/burp_ca --dhfile /etc/burp/dhfile.pem # TEST end of line comments --dir /etc/burp/CA'
Aug 19 22:45:06.643600 myhost burp[17571]: /usr/sbin/burp_ca returned: 0

Yea I don't think that should have happened.

I saw in issue #224 that someone had requested end-of-line comment support but I suspect it's not quite working how I imagined. Are the quotes required when using end-of-line comments?

Thanks!

**Comment by grke** [comment]
Yes, try putting your configuration value in quotes.
