### ISSUE TITLE
Windows (VSS?): complete stall in phase two

### ISSUE THREAD

**Issue by WeaponMan** [grke/burp#830]
I was trying to get whole systems backups going on Windows 7 with burp and after x amount of time sending the backup to the server the "progress bar" just stalls.
I checked network on the server no incoming traffic.

After couple of failed attempts to fix it I moved onto Windows 10 to see if there is same problem and yes there is.
Last resort was trying to increase VSS Write timeout and it stalled again in the middle of phase 2.

The backup has size more than 20GB and it takes time to push 20GB thru QoSed connection.

I am using same version 2.2.18 on server and client with librsync and protocol set to 1.

(I dont really know how VSS works under the hood in burp but thinking it will after some time it just stops spitting bytes)

**Comment by grke** [comment]
Hello,

What VSS Write timeout are you talking about?
I've never heard mention of other people having to change such a thing.
It doesn't sound like a burp setting, or the cause of your problem - the problem sounds like a networking issue.

Is it the first backup of the client? In that case, librsync=1 will not matter.
If it is not the first backup, it could be librsync getting stuck on some huge file. In which case, you could try librsync=0.

It could also be a QoS problem, and the QoS is breaking things - but I can't help with that.

**Comment by WeaponMan** [comment]
I mean the setting in `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\SPP\CreateTimeout`.

It is the first backup of that machine.

I will try to backup the data on diffrent server to see if the fixes the problem.

**Comment by WeaponMan** [comment]
It started giving `network write problem asfd_do_write_ssl: 5 - 0=No error` at the start of the phase 2 on protocol 1, so changed to protocol 2 and backup was successfully sent to the server.

If you don't wanna investigate further why this happens then consider this issue closed.

**Comment by deajan** [comment]
This looks suspiciously like a network filter, ie a https proxy.
Can you provide full logs of the client ?
I had the case where proxies made protocol 1 fail but protocol 2 succeed.
What port your server is listening on ?
What network appliances / UTM are between client and server ?

**Comment by WeaponMan** [comment]
Client logs here https://drive.google.com/file/d/1Mjkimzs0gohGiEOBiG7usjp0Q4zl06Ib/view?usp=sharing 
Server is listening on port 4971.
Both client and server is running on kvm + libvirtd, but not on same hypevisor and I cant access the server hypevisor to tune the network driver or iptables setup.
Client WM is using network driver called e1000e and the server is using what seems to be virtio.
I don't really know what gear is on the way to the from client to the server (out of my control).

**Comment by deajan** [comment]
Okay, so this is really not a VSS issue.
Usually, bad VSS triggers before phase 1.

This really looks like the problem I had with a provider proxy between client and server on 4G networks, especially if you say protocol 2 is working (https://github.com/grke/burp/issues/782).

I don't think you have a problem with kvm or your network card either, I have a couple of kvm hypervisors with burp.

**I would bet that you have a filtering device on your client network.**
Can you test the client from another internet access, like one you know for sure isn't filtered (eg home DSL/broadband or something like that) ?
If of course you cannot do that with the VM, try installing a burp client on a laptop that is on a non filtered network to outrule a server filter issue.

**Comment by WeaponMan** [comment]
I had problems with e1000e drivers on linux VMs before when I was running MC server behind NAT with port forwarding.
I tried that on work computer with Win 10 on it was running for a while and midway it just stopped sending data no errors just hangs on sending data.

Compared the traceroutes from work/home they are diffrent until they hit the pop server in Prague.

I tested on local machine with client VM Windows and hypervisor as server it sometimes hang too on sending data to the server.

I don't have a laptop that runs Windows on hand, only one with linux.

**Comment by deajan** [comment]
The main thing here is to know whether the client or the server networks have issues.
Since you can't control the server, you have to outrule the client network (thus testing different ones) before contact the server administrator and asking him to not proxy port 4971.

**Comment by WeaponMan** [comment]
nvm, this was just a test for our company if we can use this to backup our windows machines, turns out no.
Protocol 1 doesn't really work on our network or isn't reliable enough to use it.
Protocol 2 works but its experimental and in some cases slow.
Thank you for your input, I don't really want to deep dive into it because I don't even considering using it anymore.
