### ISSUE TITLE
Changed File

### ISSUE THREAD

**Issue by jacky35** [grke/burp#833]
Hello,
In the "Working" folder,
There is a "changed" file to list all new files.

Is it possible to keep this file even outside the working folder.

For all backups

Thank you.

**Comment by grke** [comment]
Hello,
This file is a temporary file that only exists as part of the process of making the backup.
I can see how it may be useful to you to keep. I will think about that.

**Comment by grke** [comment]
Hello,
This file doesn't quite contain the details that you might think it contains. It is only exists as part of the process of making a backup, and may have misleading information in it.
I would prefer not to keep it around, as it would generate many confused support requests.
I think that it would be better to improve the 'diff' feature.

**Comment by jacky35** [comment]
Hello,
I come back to the subject.

Is it possible after a backup. To have a report file with :

- The list of files edit.
- The list of deleted files.
- List of files added.

This can be very useful in some cases.

ere is my idea suggestion;)

Have a good day,
Jacky

**Comment by grke** [comment]
Hello,
I think all that you want is a good 'diff' feature.
