### ISSUE TITLE
Documentation is out of date in regards to ext3

### ISSUE THREAD

**Issue by ShalokShalom** [grke/burp#839]
ext3 is no more. RIP: https://wiki.gentoo.org/wiki/Ext3

Still here: https://burp.grke.org/faq.html

Is the homepage open source?

**Comment by grke** [comment]
Hello,
Thanks for that, I will update it this month.
The website is a branch in the burp git repo called 'website'.

**Comment by ShalokShalom** [comment]
Ah, a different branch ^^

Maybe mention it on the homepage and /or the readme?

**Comment by grke** [comment]
Website updated.

Thanks for the suggestion, but the website is only for me to update, so I prefer it to be obscured.
