### ISSUE TITLE
unexpected command in authorise_client(): e:001D:unable to authorise on server

### ISSUE THREAD

**Issue by JumpyWizard404** [grke/burp#840]
Hello Everyone, we are testing Burp to use as a backup solution, now for the test all the settings are left as default with nothing being customized on both the server and the windows client as i am trying to test out the functions, i have generated the certs on the server, and had them transferred to the client. Firewall is down on both sides, and when a manual backup with burp.exe -a b is attempted the error in the title appears. Does anyone please have any idea where i need to start looking. Thank you

**Comment by ziirish** [comment]
Hello,

This error usually mean either the password does not match in both the *burp.conf* file client-side and in the */etc/burp/clientconfdir/<cname>* file server-side or the certificate mismatch.

You can have a look at the burp-server logs to have further details.

**Comment by JumpyWizard404** [comment]
thank you for the info ill try it out. Unfortunately im still a noob when it comes to linux so

**Comment by JumpyWizard404** [comment]
Thank you so much the issue was with the missmatch of  passwords in /etc/burp/clientconfdir
