### ISSUE TITLE
burp gentoo

### ISSUE THREAD

**Issue by shaulyn** [grke/burp#843]
an error occurs when starting burping on gentoo

> Jan 17 09:40:19 calculate burp[7581]: Creating /etc/burp/CA/CA_burpCA.crl
> Jan 17 09:40:19 calculate burp[7581]: Running '/usr/sbin/burp_ca --name burpCA --config /etc/burp/CA.cnf --dir /etc/burp/CA --crl'
> Jan 17 09:40:19 calculate burp[7581]: /usr/sbin/burp_ca returned: 1
> Jan 17 09:40:19 calculate burp[7581]: Error running /usr/sbin/burp_ca
> Jan 17 09:40:19 calculate burp[7581]: CA setup failed

**Comment by shaulyn** [comment]
> /usr/sbin/burp_ca --init --ca burpCA --dir /etc/burp/CA --config /etc/burp/CA.cnf
> Init... burpCA
> Generating RSA private key, 2048 bit long modulus (2 primes)
> .............................................................................................................................+++++
> ..................................+++++
> e is 65537 (0x010001)
> Cannot write random bytes:
> 140107479320384:error:2407007A:random number generator:RAND_write_file:Not a regular file:crypto/rand/randfile.c:183:Filename=/dev/urandom

**Comment by grke** [comment]
Hello,
What version of burp is this?

**Comment by grke** [comment]
No reply, closing.
