### ISSUE TITLE
Performance drops

### ISSUE THREAD

**Issue by mnlipp** [grke/burp#846]
I have just experienced an extreme drop of performance with 2.2.18 when backing up one of my computers. Everything was okay until about 70% were reached. Then the performance dropped dramatically. There was nothing special in any log file (neither server nor client). 

It took me some time to come up with an idea how to find out what happened. Finally, I started watching the changed files in the target directory. While I looked, I found that the journald archive files were backed up with about 1MByte/s (on a Gigabit network). These seemed to be the last, however, because then Phase 2 was over rather quickly.

I'll watch the files being backed up closer next time and report.

**Comment by grke** [comment]
Hello,
What are you doing to determine performance?
Is burp using librsync?

**Comment by mnlipp** [comment]
Well, as mentioned: I watched the files in the "working" directory. At that particular occurrence, when the journal archives were processed, I saw the size of the received files growing at about  1 MByte/s (they are 135 MByte each, so you can watch for a while).

I'm using librsync. I just checked, it's the default and I didn't change it. However, right below on the man page I just found `librsync_max_size`. I'm not familiar with the details of librsync. Is there a drawback using it for larger files? Should I uses that limit setting?

**Comment by grke** [comment]
If you are using librsync and are watching the files arrive, you are most likely seeing the differences between the old and new file as calculated by librsync. It doesn't add the diff to the old file to recreate the new file until phase4 of the backup.

If your network is fast enough for you not to care about calculating the differences, and you are OK to back up the whole file each time, you might as well set librsync=0.

**Comment by mnlipp** [comment]
So, calculating the differences is that much slower than transferring the complete file? Strange.

Is there a way to configure *transfer* of the complete file but *storage* of only the differences? I don't care about transferring the complete file over the network, but I'd like to save the space on the backup disk.

**Comment by grke** [comment]
Yes, set librsync=0.

**Comment by mnlipp** [comment]
Thanks!
