### ISSUE TITLE
unknown cmd: k while doing verify

### ISSUE THREAD

**Issue by HoBauC** [grke/burp#848]
Hi!
burp version on server and clients 2.3.22. Using protocol 2.
I have a trouble while verifing: 
burp  -C client1 -b 7 -a v 

long output ends with:

```
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 3040320
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 3040384
BBBBBBBBBBBBfBfBfBfB2020-02-05 08:36:22 +0700: burp[32420] unknown cmd: k
 3040404

--------------------------------------------------------------------------------
Start time: 2020-02-05 08:26:11
  End time: 2020-02-05 08:36:22
Time taken: 10:11
                             Attempted | Expected
                   ------------------------------
             Files:              67681 |        0
            Blocks:            2972723 |        0
       Grand total:            3040404 |        0
                   ------------------------------

             Messages:             0
             Warnings:             0

      Bytes estimated:             0
        Bytes checked:             0
       Bytes received:      27669562 (26.39 MB)
           Bytes sent:           653
--------------------------------------------------------------------------------
2020-02-05 08:36:22 +0700: burp[32420] ret: -1
```

I don't know if backups good or not? This output looks like a bug in verify prcedure. 
On version 2.3.20 the same error. Other several clients, i tested, outs the same.

**Comment by grke** [comment]
Hello,

'k' means a Windows EFS file.

In src/client/protocol2/restore.c, I have the comment:
```
FIX THIS: Encryption and EFS not supported yet.
```
The verify uses the same code, and the case statement that would handle CMD_EFS_FILE is commented out.
It doesn't make any attempt to warn or skip over that entry, it just hits the default case of fully erroring.
I think that, whilst it is not supported, it should at least try to warn and skip.

**Comment by HoBauC** [comment]
Thanks for the tip.  Аs a temporary solution inserted  dummy  handle for EFS files and recompiled. 

>  case CMD_EFS_FILE:
                        logp("restore_file warninng : EFS not supported\n");
                        break;

Verify finished with no error.

```
Start time: 2020-02-05 13:34:08
  End time: 2020-02-05 14:06:39
Time taken: 32:31
                             Attempted | Expected
                   ------------------------------
             Files:             207765 |        0
            Blocks:            9164145 |        0
       Grand total:            9371910 |        0
                   ------------------------------

             Messages:             0
             Warnings:             0

      Bytes estimated:             0
        Bytes checked:             0
       Bytes received:      88241582 (84.15 MB)
           Bytes sent:           671
--------------------------------------------------------------------------------
2020-02-05 14:06:39 +0700: burp[4815] verify finished
```
But size conters doesn't work? Or my dummy is wrong?

**Comment by grke** [comment]
Hello,
This is as good as the counters for verify/restore looks for protocol 2 at the moment.

**Comment by grke** [comment]
Hello,
There is a change in master that warns about and skips these entries now.
