### ISSUE TITLE
file permissions

### ISSUE THREAD

**Issue by shaulyn** [grke/burp#850]
why doesn't burping restore file permissions?
I can provide any logs you tell me. I save using burps in windows files with NTFS rights. during recovery, they are restored without NTFS access rights. what am I doing wrong.

**Comment by grke** [comment]
Hello,

Please give me details on:

* what burp version you are using
* what the operating system is
* what NTFS access rights you are setting on these files
* what command you are using to restore
* the output when you run the command

Thank you.

**Comment by shaulyn** [comment]
Gentoo - Latest version installed: 2.2.18

the rest of the data will show how I will be at work

**Comment by grke** [comment]
Hello,

I tried a few things with recent 2.3.x server and client, on Windows 7.
 
As far as I can tell:
Protocol 2 restores permissions correctly on files, but not on directories. This is expected.
Protocol 1 restores permissions correctly on everything I tried.

I am closing.
If you still have problems, and want help, you need to provide much more detail than you have done in the two issues you have raised so far.

Thank you.

**Comment by shaulyn** [comment]
Forgive me, really prva saved. I double-checked everything. burps using shadow copies? Does he know how to do differentiated or incremental backup?
