### ISSUE TITLE
OpenSSL 1.1.1 CA md too weak

### ISSUE THREAD

**Issue by cpasqualini** [grke/burp#857]
Hi

Burp server is not starting after upgrading our system (Debian stretch to buster)

`# burp -c /etc/burp/burp-server.conf -F -n
139951280041408:error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak:../ssl/ssl_rsa.c:310:
`
This server is running from even older versions, which has been upgraded without any issues.

As this is the Burp _Server_ I cannot found a way to regenerate the Burp's created keys, with the now required security, without having to build a new CA and go every client host and manually synchronize the certificates again.

¿Is there a way to fix this CA without starting from scratch?

Thanks

**Comment by grke** [comment]
Hello,
Sorry, but I don't currently know of a way to get around this other than to regenerate the certificates. It happened to me too, when I upgraded debian. The ssl library insists upon it.

**Comment by cpasqualini** [comment]
If this happened to you too... well let's start to build again
Thanks for your GREAT work!

**Comment by grke** [comment]
Thanks for the kind words, and sorry that I don't have a less annoying solution for that.

**Comment by kiorky** [comment]
For the posterity and as a TEMPORARY workaround on clients, you can re-lower openssl standards by adding to `/etc/ssl/openssl.conf`

at the beginning of the file

```
openssl_conf = default_conf
```

at the end of the file
```
[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = ssl_default_sect

[ssl_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=1
```

But, yes, re-rolling out new certificates is the best

**Comment by jkugler** [comment]
If you want to just have the security downgrade affect burp, and not everything on your system, you can do this:

Create this file on the client:

/etc/burp/burp_ssl.conf
```
openssl_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=0
```
Then, before burp is invoked:

`export OPENSSL_CONF=/etc/burp/burp_ssl.conf`

**Comment by pagalba-com** [comment]
hit that too. What is the behaviour if server ca certificates are removed, but I have no access to clients running? 
Is there any procedure to force client re-establish certificate trust?

**Comment by grke** [comment]
Hello,
The client will not try to get new certificates signed if it already has had certificates signed.
