### ISSUE TITLE
Small typo in cron.example

### ISSUE THREAD

**Issue by Azrael3000** [grke/burp#860]
https://github.com/grke/burp/blob/9363e4edfd4f33930a4642e42081026e5e470bc1/configs/server/cron.example#L6

should be burp-server.conf instead of burp.conf

**Comment by grke** [comment]
Hello,
The path to the script is also incorrect.
Thanks for telling me.

**Comment by grke** [comment]
Oh - burp.conf is correct. It uses the client side status monitor.

**Comment by grke** [comment]
The issues are tidied up in the latest git master. Thank you.
