### ISSUE TITLE
burp_ca fails if hostname -f doesn't works

### ISSUE THREAD

**Issue by pablodav** [grke/burp#861]
Hello @grke ,
Hope you are doing fine.

I just noticed there is a bug with burp_ca file, during tests with debian-10-ansible container here: 
https://travis-ci.org/github/CoffeeITWorks/ansible_burp2_server/builds/686834178#L1397

I just noticed burp_ca failed because `hostname -f` didn't work on this image.

Possible fix for line 64 is here, it's tested and works:

https://github.com/CoffeeITWorks/ansible_burp2_server/commit/d41b03dfd62ddf7a867b8008d1f0c670fb1a9da5

I think with this fix we can remove line 67.

What do you think?

**Comment by grke** [comment]
Hello,

You can't remove line 67, because it also catches the cases on other listed OSes don't get output from the different hostname-like commands.
This will be better:
```
*) name="$(hostname -f || true)"
```
I will make that change in master shortly.
Thank you for reporting.

**Comment by grke** [comment]
My fix is now in master.

**Comment by pablodav** [comment]
Great! Have a nice weekend
