### ISSUE TITLE
Ubuntu focal: dh key too small

### ISSUE THREAD

**Issue by 4001982248998** [grke/burp#862]
The latest Ubuntu LTS server version 20.04 does not seem to work with BuRP. After building the client, TLS certificates are normally being generated upon first contact with the server. But now, it seems to fail because of a too small diffie-hellman file:

```sh
sudo burp -a l
2020-05-14 14:51:01 +0200: burp[2222558] Could not find ssl_cert /etc/burp/ssl_cert-client.pem: No such file or directory
2020-05-14 14:51:01 +0200: burp[2222558] Could not find ssl_key /etc/burp/ssl_cert-client.key: No such file or directory
2020-05-14 14:51:01 +0200: burp[2222558] Could not find ssl_cert_ca /etc/burp/ssl_cert_ca.pem: No such file or directory
2020-05-14 14:51:01 +0200: burp[2222558] Connecting to 10.11.12.15:4971
2020-05-14 14:51:01 +0200: burp[2222558] SSL connect error
139696584450688:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../ssl/statem/statem_clnt.c:2149:
```

I guess this is an issue of heightened security expectations in Focal's openssl installation. Where can this be configured or worked around?

**Comment by grke** [comment]
Hello,

What version of burp is this, on both server and client side?

Is the server side also using ubuntu 20.04?
Or is the server side an existing burp installation?
Maybe the ubuntu 20.04 is complaining that the server side diffie-helman is too small.

You can also check the burp_ca script on both sides. There is a section that generates the dhfile, it looks like this...

```
if [ -n "$dhfile" ] ; then
        openssl dhparam \
                -dsaparam \
                -out "$dhfile" \
                2048
        chmod 600 "$dhfile"
fi
```

...where the '2048' is the size of the file that it generates.
To generate a new dhfile, you can rm and let it generate it again.

**Comment by 4001982248998** [comment]
Hello,

sorry for not providing the version details. I am using the current stable version, 2.2.18 on both server and client. The server is running an older version of Ubuntu, 16.04.

However, you have set me on the right track. I was unsuccessful with renewing the dhfile file on the client, but did not have the idea to do that on the server! After replacing the dhfile on the server with a (significantly) larger length, ssl communication and backups worked again.

Thank you ten tons for writing and maintaining this software!

**Comment by grke** [comment]
You're welcome, good luck.
