### ISSUE TITLE
burp client fails: Could not find ssl_cert /etc/burp/ssl_cert-client.pem

### ISSUE THREAD

**Issue by donpdonp** [grke/burp#863]
First time burp user here: Installed 2.1.32 from deb package. burp in server mode was able to generate CA data and server cert file and key file. The client cert/key is not there and documentation does not address how to generate it. From what I gather the cert is generated automatically somehow but its not happening and I don't know how to make it happen.

```
root@storj3a:/etc/burp# burp
2020-05-14 13:28:29 -0700: burp[26366] Could not find ssl_cert /etc/burp/ssl_cert-client.pem: No such file or directory
2020-05-14 13:28:29 -0700: burp[26366] Could not find ssl_key /etc/burp/ssl_cert-client.key: No such file or directory
2020-05-14 13:28:29 -0700: burp[26366] Connecting to localhost:4971
2020-05-14 13:28:29 -0700: burp[26366] SSL connect error
```

**Comment by grke** [comment]
Hello,

Thank you for your interest in burp.

Do you have a burp server running on localhost:4971?
You can run a command like 'ss -plnt' to see.

Does the burp server output anything when the client tries to connect?
You can run the burp server in the foreground to see, like this:
burp -c /etc/burp/burp-server.conf -F -v

**Comment by donpdonp** [comment]
Hello, yes the server is running. restarted just now

```
root@storj3a:/etc/burp# burp -c burp-server.conf -F -v
burp-2.1.32
root@storj3a:/etc/burp# burp -c burp-server.conf -F
(server waits here)
```

from another ssh session into the same server:
```
root@storj3a:/home/donp# burp
2020-05-14 13:59:52 -0700: burp[28439] Could not find ssl_cert /etc/burp/ssl_cert-client.pem: No such file or directory
2020-05-14 13:59:52 -0700: burp[28439] Could not find ssl_key /etc/burp/ssl_cert-client.key: No such file or directory
2020-05-14 13:59:52 -0700: burp[28439] Connecting to localhost:4971
2020-05-14 13:59:52 -0700: burp[28439] unexpected command in authorise_client(): e:001D:unable to authorise on server
```

**Comment by donpdonp** [comment]
the problem is clear (missing client cert/key), its just not clear what to do about it. Does burp use SSL client certs for authentication? How are the certs normally generated?

**Comment by grke** [comment]
Hello,

The problem is actually that your passwords do not match.
Once they match, the client and server will exchange certificates and use them from that point onwards.

On the server, look in the file called '/etc/burp/clientconfdir/<clientname>'.

On the client, look it the file called '/etc/burp/burp.conf'.

The configuration item called 'password' needs to match in both files.

**Comment by ziirish** [comment]
Side note, on server you must have a file in `/etc/burp/clientconfdir/` named as the `cname` in your client conf file (`/etc/burp/burp.conf`).

For instance, if you have `cname = testclient` and `password = azerty` in your `/etc/burp/burp.conf` client-side, then you have to run `echo "password = azerty" >/etc/burp/clientconfdir/testclient` server-side.

**Comment by donpdonp** [comment]
Ah yes I did change the cname in an attempt to fix things. One I put cname back to `testclient`, it got a cert from the server as usual. I'm not sure why it didnt work the first time.

Thanks for the help! a couple documentation suggestions:

In addition to `unexpected command in authorise_client()` in the log, maybe add a message about mismatched passwords. And the README would be a great spot for the sidenote about the purpose of clientconfdir. thanks!
