### ISSUE TITLE
consider github assets on releases instead of sourceforge

### ISSUE THREAD

**Issue by pablodav** [grke/burp#865]
Hello Graham!

I see issues often with sourceforge to download files, I see it on daily tests and also while testing my roles during development.

Errors like: 
```
TASK [ansible_burp2_server : autoupgrade | Get autoupgrade package] ************
    Monday 01 June 2020  21:51:53 -0300 (0:00:08.673)       0:02:14.683 ***********
    failed: [ansible_burp2_server-04] (item={'src': 'https://sourceforge.net/projects/burp/files/burp-2.2.18/burp-win64-installer-2.2.18.exe/download', 'dest': '/etc/burp/autoupgrade/server/win64/2.2.18/package'}) => {"ansible_loop_var": "item", "changed": false, "dest": "/etc/burp/autoupgrade/server/win64/2.2.18/package", "elapsed": 31, "item": {"dest": "/etc/burp/autoupgrade/server/win64/2.2.18/package", "src": "https://sourceforge.net/projects/burp/files/burp-2.2.18/burp-win64-installer-2.2.18.exe/download"}, "msg": "Request failed: <urlopen error timed out>", "url": "https://sourceforge.net/projects/burp/files/burp-2.2.18/burp-win64-installer-2.2.18.exe/download"}
```

https://travis-ci.org/github/CoffeeITWorks/ansible_burpui_server/jobs/693665779#L1353

https://travis-ci.org/github/CoffeeITWorks/ansible_burpui_server/builds/691974008#L1303

https://travis-ci.org/github/CoffeeITWorks/ansible_burpui_server/builds/689860749#L1300

Many projects today uses github release assets, it's pretty easy to use it, you only need to drag & drop the files over the release while you create it or later when you edit it, like:

https://github.com/pablodav/burp/releases/tag/2.2.18

I have uploaded it there just as workaround now to the issues I see with sourceforge.

Have a nice day!

**Comment by grke** [comment]
Good idea, I was having similar problems with my release this month. I will look into it.

**Comment by grke** [comment]
I am now uploading to github instead of sourceforge.

https://github.com/grke/burp/releases/tag/2.3.30
