### ISSUE TITLE
Intermittent test timeouts since 2.3.30

### ISSUE THREAD

**Issue by mkszuba** [grke/burp#869]
Since 2.3.30, i.e. also in 2.3.32, I have seen occasional errors in the burp test suite caused by timer expiration. Specifically:

```
utest/protocol2/rabin/test_rabin.c:62:E:Core:test_rabin_blks_generate_empty_file:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_find:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_client_conf:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_client_conf_ca_conf_problems:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_client_includes_excludes:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_client_conf_monitor_exe:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_client_conf_ports_opt_port_and_restore:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_client_conf_ports_opt_port_and_all:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_client_conf_ports_no_opt_port_and_all:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_backup_script_pre_post:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_backup_script:0: (after this point) Test timeout expired
utest/builders/build_file.c:15:E:Core:test_authorise_server:0: (after this point) Test timeout expired
```

As mentioned above, these timeouts do not occur every time I run the test suite. Alas, I have yet to see any patterns in when they do show up.

**Comment by grke** [comment]
Hello,
This means that these tests are taking too long to run.
Perhaps the hardware that you are running them on is too slow?

These are not intensive tests.
For example, "test_client_conf" writes a very small burp config file, and reads it back. Maybe your disk is under load from other processes?

**Comment by mkszuba** [comment]
I have considered this too but it doesn't seem to be the culprit, or at least not a direct one. For instance, just a moment ago I tried repeatedly compiling burp and running its test suite on a system already executing a parallel build of Firefox as well as an I/O stress test on the drive. The CPU load oscillated between 1.5 and 2 *per core*, I/O rates were pretty close to what the drive in question can handle - yet the burp test suite succeeded every single time.

What should the timeout be for the tests in question? I see some _tcase_set_timeout()_ calls in various parts of the test suite but I haven't figured out which one applies yet.

**Comment by grke** [comment]
Hello,
What do you think the timeouts should be?
At the current level, I have no problems on my build servers, which are very underpowered machines, but they do not do much else than build burp.

**Comment by mkszuba** [comment]
No idea! I just wanted to know what the current value is so that I know where to start when I try to experiment with higher values.

**Comment by grke** [comment]
https://libcheck.github.io/check/doc/check_html/check_4.html
In section 4.9:
"To be certain that a test won’t hang indefinitely, all tests are run with a timeout, the default being 4 seconds."
...
"The default timeout used for all test cases can be changed with the environment variable CK_DEFAULT_TIMEOUT, but this will not override an explicitly set timeout."

Maybe try setting CK_DEFAULT_TIMEOUT to something higher than 4?

**Comment by mkszuba** [comment]
Ah, so it's the default. I thought one of the explicitly-set values might apply here. Anyway, I'll keep you posted!

**Comment by mkszuba** [comment]
I have run into this again while bumping burp to 2.3.34 in Gentoo and this time I actually managed to trigger the test timeout (for the default value) several times in a row. I then set CK_DEFAULT_TIMEOUT to 10 and the test suite passed... except when I set it back to 4 it still did.

**Comment by grke** [comment]
Seems to be resolved.
