### ISSUE TITLE
add S3 backend for server

### ISSUE THREAD

**Issue by ops34** [grke/burp#872]
Would be cool to use burp server with storage backend in any of S3 providers storage. Advantages in manageability, price, durability. Server can be minimal in this case.
S3 wrapper filesystems would not do here - native S3 backend support is needed.

**Comment by svalouch** [comment]
Just out of curiosity, why would a S3 filesystem mount not work here and how would features like hardlinked backups translate to S3?

**Comment by grke** [comment]
Hello,
My initial response to this request is:

Burp's whole purpose is disk based backups/restores.
If burp is to not treat the storage as a normal filesystem, it would be a completely different piece of software.

If the server is minimal, why does it need to be burp at all?

**Comment by grke** [comment]
No reply, closing.
