### ISSUE TITLE
Right way to backup databases

### ISSUE THREAD

**Issue by dmitry-sinina** [grke/burp#873]
Currently we are handling database backups using **backup_script_pre**/**backup_script_post** - we are creating some dump or data copy, and BURP able to backup it. But this technique is not usable to backup big databases - it requires a lot free space on server.

Bareos/bacula have [bpipe](https://docs.bareos.org/TasksAndConcepts/Plugins.html#bpipe-plugin)  plugin to solve this issue. As I understand BURP **read_fifo** allow us to do same, but question how to run DB backup tool(pg_dump) before fifo reading, is it possible?

**Comment by dmitry-sinina** [comment]
backup_script_pre doesn't fit because BURP waiting for script completion but we need to start some parallel process with pg_dump  that will write to fifo.

**Comment by grke** [comment]
Hello,

What is stopping you from making the script background the pg_dump process so that the script exits, and the pg_dump process continues?

If you do that, you should probably make a post script run on failure that tries to clean up the backgrounded process.

**Comment by dmitry-sinina** [comment]
I will try, but looks like it will be not possible to detect pg_dump failure during backup in this way

**Comment by grke** [comment]
Sorry, I didn't specifically mean on pg_dump failure. I meant on any kind of backup failure, like the server running out of disk space or something like that.

**Comment by grke** [comment]
Question has been answered, closing.
