### ISSUE TITLE
[RFC] Client and server in separate binaries

### ISSUE THREAD

**Issue by melak** [grke/burp#877]
Let's say I have a system that is a Burp server as well as a Burp client (backing up to somewhere else). Using AppArmor (not sure how the other MAC frameworks work), ideally, I would want to confine the server such that it can read and write its spool, some bits and bobs for certificate management and the usual stuff, but nothing else. On the face of it, this is perfectly doable, but - since client and server are the same binaries on disk, the resulting AA profile applies to client invocation as well, preventing the client from reading what it needs to back up (I hope I'm making sense here).

A hard link is an option (in fact that's what I'm doing now), but maybe separating `burpd` from `burp` might be an option? Or some other ideas, perhaps?

**Comment by grke** [comment]
Hello,

Sorry, but splitting the burp binary is not something I am planning to do. It sounds like your hardlink solution works fine.
