### ISSUE TITLE
Cross-system restore

### ISSUE THREAD

**Issue by t-dan** [grke/burp#879]
Hello,
the burp supports -C option to allow restore from a different machine that the backup has originally been made for (together with the appropriate configuration).

I have tried to use this option to restore backups made on Windows - from Linux. However, even the simple text files have some sort of information pre-pended, making them unreadable when restored on Linux. Looking at the burp server, the information is already in the files.

My question is - what is this information for? It seems that this information **is not** stored in files when backup is made from Linux system.
Is it somehow possible to make such a cross-system restore?

Thank you for the answer,
Dan T.

Let me note that the restore made from Windows worked without issues.

**Comment by grke** [comment]
Hello,
It is Windows backup API data.
Have a look in the burp manpage, or help output, for the -x option.

**Comment by ARTIC-TTS-experiments** [comment]
Thank you very much for the explanation. I have completely missed that option.
Now all works as expected.
