### ISSUE TITLE
burp v 2.2.18 won't backup folder just files

### ISSUE THREAD

**Issue by GusevVictor** [grke/burp#882]
Hi all! I want to test burp for backup my Windows 10 desktop, there is strange problem.

I have create folder "1" in my C: drive

After that I created folder like this: C:/1/folder , and file like this: C:/1/file

After OK backup I have in current directory on server only with file but there is no folder and there no any error message

**Comment by GusevVictor** [comment]
if a folder is empty then burp won't backup it. If it has a content - burp backup it fine!

**Comment by grke** [comment]
Hello,

Burp avoids creating unnecessary inodes for empty directories on the server side.
The fact that a directory exists is recorded in the manifest for that backup, and on restore the directory will be created.
You can see that the directory exists in the manifest by using burp in the client side to list the backup:
burp -a L
