### ISSUE TITLE
Make SSL certificate revocation work automatically

### ISSUE THREAD

**Issue by grke** [grke/burp#89]
There is a server pre script called ssl_extra_checks_script that does something to do with checking expiry dates and certificate revocation. Now that ssl certificate signing works automatically, it would be good to include ssl_extra_checks_script by default so that it works automatically too.
However, I don't really understand what ssl_extra_checks_script does or what it is supposed to do, so it needs to be understood first.

**Comment by ziirish** [comment]
Hello,

I've been playing with certificates revocation and I noticed that the revocation check is already implemented in burp: 04eec1e9a34fac58d7dc3e8e7f2ed820eed88711

I think you can update or close this issue.

**Comment by grke** [comment]
Thanks for pointing this out.

There is some documentation for the revocation stuff here:
http://burp.grke.org/docs/add-remove.html

It is still not as "automatic" as I would like, but it seems that issue 89 is really about the old ssl_extra_checks_script. So, let's close this issue.

**Comment by tallship** [comment]
What about something like the way Apache deals with OCSP?

https://en.wikipedia.org/wiki/OCSP_stapling

Maybe something for the roadmap?
