### ISSUE TITLE
restore_file error

### ISSUE THREAD

**Issue by GusevVictor** [grke/burp#891]
Hi all! Could you help me with a following problem, please?

I have backup Windows Machine server/client 2.4.0

After that I want to restore it to an another PC, but I have error: restore_file error this comes after WARNING Could not transfer file. The file has path contains russian symbol and file has russian name. Please see a screen shot.

![изображение](https://user-images.githubusercontent.com/7081357/134525464-2903c218-95a9-4c35-a430-e7cc11ff113c.png)

What is wrong?

**Comment by grke** [comment]
Hello,
At this point, it has managed to open a file.
It is trying to append 16000 bytes to the file, but the write is failing.

Some ideas:
- Maybe check whether your disk is full?
- Did any bytes get saved to the file, or is it just zero length?
- Does the file restore ok on the original computer (specify a different restore location so you don't overwrite the original file)?
- Does the Windows event log record anything?
- Does the file restore ok to a linux computer?

**Comment by GusevVictor** [comment]
Thank a lot for your answer. I have problem in a client.

The problem was in drive letters. I use WinPE for restore and WinPE confuse with C: and D: drive letters because of this I try to restore into small partition drive (small system drive 'Restore partition'). After correct it I have no problem. 

Thank a lot for good OpenSource software!
