### ISSUE TITLE
compiler Warning Werror=format-security

### ISSUE THREAD

**Issue by kalos** [grke/burp#894]
As reported in debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=997159

File src/client/monitor/status_client_ncurses.c reise a "fatal" Warning: error: format not a string literal and no format arguments [-Werror=format-security]
I've bypass this error using -Wno-error=format-security but I think the best solution is to use the mvprintw function correctly or an alternative function (sorry but I'm not an C expert)

Thanks!

**Comment by grke** [comment]
Hello,

Thanks for that, fixes are now in git master.
