### ISSUE TITLE
Problems building Windows Client

### ISSUE THREAD

**Issue by mikaku** [grke/burp#897]
Hello,

First of all, thank you very much for this good piece of software.

I'm trying to make my first win32 build, but I'm failing with some unexpected problems.

I've followed the steps in the README and README.VSS files from the **burp-cross-tools** and now I've a Docker image that should be ready to build the Windows clients. I did this on a fresh CentOS 7(.9) installation, but I think this is not a problem since all the magic is inside the Docker image.

Now, the README file in **burp** says:

```
[...]

You can now start the docker image, copy the burp sources inside, and
build the burp installers themselves.

Change to the burp source directory.

Standing in src/win32, run the following:

  make            (for 32bit clients)
  make WIN64=yes  (for 64bit clients)
```

I was not sure where to put the `tar.gz` file with the Burp sources, so I put it in `/`, this is what I have in the root directory after untarring the Burp source code:

```
# ls -l
total 17140
drwxr-xr-x.   1 root root     4096 Jan 15 21:57 bin
drwxr-xr-x.   2 root root     4096 Jul 10  2020 boot
drwxr-xr-x.  11 root root     4096 Jan 16 19:12 burp
drwxr-xr-x.   1 root root     4096 Jan 16 07:36 burp-cross-tools
-rw-r--r--.   1 root root 17464196 Jan 16 19:16 burp.tar.gz
drwxr-xr-x.   5 root root      360 Jan 17 09:53 dev
drwxr-xr-x.   1 root root     4096 Jan 17 09:53 etc
drwxr-xr-x.   2 root root     4096 Jul 10  2020 home
drwxr-xr-x.   1 root root     4096 Jan 15 21:55 lib
drwxr-xr-x.   2 root root     4096 Dec 20 00:00 lib64
drwxr-xr-x.   2 root root     4096 Dec 20 00:00 media
drwxr-xr-x.   2 root root     4096 Dec 20 00:00 mnt
drwxr-xr-x.   2 root root     4096 Dec 20 00:00 opt
dr-xr-xr-x. 107 root root        0 Jan 17 09:53 proc
drwx------.   1 root root     4096 Jan 17 09:53 root
drwxr-xr-x.   1 root root     4096 Jan 15 21:54 run
drwxr-xr-x.   1 root root     4096 Jan 15 21:56 sbin
drwxr-xr-x.   2 root root     4096 Dec 20 00:00 srv
dr-xr-xr-x.  13 root root        0 Jan 17 08:37 sys
drwxrwxrwt.   1 root root     4096 Jan 16 08:31 tmp
drwxr-xr-x.   1 root root     4096 Dec 20 00:00 usr
drwxr-xr-x.   1 root root     4096 Dec 20 00:00 var
```

After that, I changed to the directory `burp/src/win32`, and once there I ran `make WIN64=yes` but I got the following error message:

```
# make WIN64=yes
/

Could not find burp-cross-tools.
Makefile:52: recipe for target '../../burp-cross-tools' failed
make: *** [../../burp-cross-tools] Error 1
```

What steps I'm missing?

**Comment by mikaku** [comment]
Pressed ENTER key by mistake, sorry.

**Comment by mikaku** [comment]
OK, I managed to solve the compilation problems. It turns out that it needs a pair of symbolic links:

```
cd /
tar zxf burp.tar.gz || exit 1
pushd burp
ln -s /burp-cross-tools/cross-tools/ burp-cross-tools
ln -s /burp-cross-tools/depkgs/ burp-depkgs
popd
```

**Comment by mikaku** [comment]
Now I need to know why installer32 is not building:

```
# make
Creating Makefile.inc
/burp/burp-cross-tools

The GCC cross compiler isn't installed.
You must run build-win32-cross-tools and build-dependencies first.

Makefile:68: recipe for target 'Makefile.inc' failed
make: *** [Makefile.inc] Error 1
```

Indeed, it looks like the 32bit cross compiler toolchain was not built during the creation of docker image.
Any ideas?

**Comment by grke** [comment]
Hello,

Yes, I decided to stop supporting 32 bit windows because it was taking up a lot of my time for not much benefit, but I forgot to update burp/src/win32/README.
If you look in burp-cross-tools/depkgs/build-script.sh, there is this line commented out near the bottom:

{code}
#do_build mingw-w64-i686 i686-w64-mingw32 mingw
{code}

And burp-cross-tools/cross-tools/build-script.sh, there are these three lines commented out near the bottom:

{code}
#orig_path="$PATH"
#build_mingw_w64 "$target_i686" "$mingw_w64_i686_prefix"
#export PATH="$orig_path"
{code}

You could try uncommenting them, maybe it still works.
Or you could try 'git checkout dc3f8fb105c6263a444257298d799e690426d8bc', which is the commit before I commented out those lines.

**Comment by mikaku** [comment]
Yes, I see now those lines commented out.
I'll try uncommenting them. :smiley:
Thank you!

**Comment by mikaku** [comment]
Just to inform you that it worked well.
Thanks again!
