### ISSUE TITLE
If you have huge files that get touched, problem to complete backup, exclude_logic question

### ISSUE THREAD

**Issue by pagalba-com** [grke/burp#898]
If you have huge files that get touched, librsync=1 is probably your problem.
The first backup of such a file will be OK, but then librsync will take forever to generate signatures and diffs.
The disadvantage of librsync=0 is that the huge file will be backed up a second time if it is touched, but librsync won't lock everything up.
I recommend ruling that out before anything else. Doesn't have to take days or weeks, just backup a huge file, then touch it, then try backing it up again.

There is another config that you can think about if you like librsync being on - check 'librsync_max_size' in the man page.

You may also find the 'exclude_logic'+'file_size' options interesting.

_Originally posted by @grke in https://github.com/grke/burp/issues/874#issuecomment-713319396_

**Comment by pagalba-com** [comment]
> exclude_logic

sorry to resurrect old thread, I wonder where documented is this option?

I have a special case, backup of large file stuck the backup multiple times, until occasionally successful.

I wanted to create topic / proposal to have ability to combine options, like exclude files larger than 300mb with extensions avi, mpeg, mkv, mov and so on video files, still allow client to backup 20GB size Outlook.pst file.

My observation, is that outlook file, as it's so big, and has incremental changes, will be 9 of 10 reasons to fail backup. 

But disabling librsync does not help, as problem is that file changes while backup is finished, it times out, laptop goes to sleep, and so on, all start again and fails, because on uncompleted backup, large file changed.

The exclude_logic would help a lot, at least to allow concentrate on one large file, still skipping other, not so important.

I was thinking about possibility to do configuration as per include directory, like web servers do, then it could be possible to set different size limits, excludes and other parameters, depending on backup directory location.

**Comment by grke** [comment]
Hello,
The 'exclude_logic' option is documented in the man page.
Either type 'man burp', or look at it online: https://burp.grke.org/docs/manpage.html
