### ISSUE TITLE
Documentation differs between homepage and config file

### ISSUE THREAD

**Issue by Boldie** [grke/burp#899]
On your page the following is documented:

```
If you do not want the client to automate the CA stuff, do not set ca_burp_ca. 
Clients as of 1.3.2 will not include the old default certificates, so if you
```

but the config file needs a set ca_burp_ca to work as expected. This is also commented in the default config file. So please update the homepage docs on page https://burp.grke.org/docs/burp_ca.html

**Comment by grke** [comment]
Hello,
I think maybe you misunderstand what that text is about.
It is saying that, if you have your own way of creating the certificates manually, then do not set ca_burp_ca. The option is for automatic certificate generation.

**Comment by grke** [comment]
(and the default client config file is consistent with this)
