### ISSUE TITLE
CA cert upgrade manual

### ISSUE THREAD

**Issue by pagalba-com** [grke/burp#901]
Hi,

because of openssl hardened requirements, old, year 2010 ca cert is too weak for modern linux client, thus I want to force expire and create new certificate on server, still keeping the peering of clients, as not to all I have access.

What would be correct path or commands, as burp ca cert is still valid 10 years.

**Comment by grke** [comment]
Hello,

Sorry, but I don't know of a way to resolve this without being able to access the clients.

**Comment by pagalba-com** [comment]
so only option is to manually delete cert files from clients?

**Comment by grke** [comment]
Either that, or hack the server OS to accept weaker certificates.

**Comment by grke** [comment]
For example, you can probably change /etc/ssl/openssl.cnf to do that.

If you manage that, it would probably be possible to add a burp autoupgrade script that could delete the client side certs. Then you'd need to delete the server side client certs, then the clients would regenerate their certificates and get them re-signed.
Being able to access the client sounds easier, unless you have plenty of time to spend on trying to get this to work.
