### ISSUE TITLE
Macos forward_past_entry() stuck repeat cycle

### ISSUE THREAD

**Issue by pagalba-com** [grke/burp#902]
Hi,

I have few mac test users and after some use, they start to experience issue, which I found was on Windows some time ago: 
https://github.com/grke/burp/issues/889

But I have not drive letters and/or case mixture.
The backup fails in cycles of such logged events:

2022-03-10 21:42:24 +0200: burp[395] Found interrupted backup.
2022-03-10 21:42:24 +0200: burp[395] Will resume on the next backup request.
2022-03-10 21:42:24 +0200: burp[395] Backup resumed
2022-03-10 21:42:24 +0200: burp[395] Client version: 2.5.2
2022-03-10 21:42:24 +0200: burp[395] Protocol: 2
2022-03-10 21:42:24 +0200: burp[395] WARNING: Client 'my-mac' version '2.5.2' does not match server version '2.4.0'. An upgrade is recommended.
2022-03-10 21:42:24 +0200: burp[395] forked champ chooser pid 396
2022-03-10 21:42:27 +0200: burp[395] Connected to champ chooser.
2022-03-10 21:42:38 +0200: burp[395] Phase 2 begin (recv backup data)
2022-03-10 21:42:38 +0200: burp[395] Begin phase1 (read previous file system scan)
2022-03-10 21:42:51 +0200: burp[395] Setting up resume positions...
2022-03-10 21:43:09 +0200: burp[395]   last good entry:    f:0081:/Users/testuser/Library/Application Support/MobileSync/Backup/00008101-000E090C22E8001E/2f/2f0fc29f4105060bd
87092e06cec1c4512922dcd
2022-03-10 21:43:09 +0200: burp[395]   setting pos_phase1
2022-03-10 21:43:11 +0200: burp[395]   setting pos_current
2022-03-10 21:43:11 +0200: burp[395] End of file in forward_past_entry()
2022-03-10 21:43:16 +0200: burp[395] End backup
2022-03-10 21:43:16 +0200: burp[395] error in backup phase 2
2022-03-10 21:43:16 +0200: burp[395] Backup failed

Client version was 2.3.x and later tried to upgrade to last possible, so no 2.5.2. No change.

It seems that during large backup, some files vanish, some files change, and restarted backup starts failing in a loop.

My suggestion would be to change the backup process in general.
phase1 scan takes long time in case of big amount of files and data. This is the case of user home directory, as well as files changed on the fly, like Outlook pst or ost file.
Thus during phase2, file data transfer, the actual files and content is changed, as much time already passed.

The idea would be to do phase1 and phase2 in small chunks, like 10 dirs scan, data send, and loop it until all dirs are processed.
If not 10-20 dirs at one step, there is an option to do chunking based in include directive.
For example 
include=/Users/user1/Docs
include=/Users/user1/Images
or something like include=/Users/*

the loop would go through include directories.

Another thing, are frequently changing files. These require special approach, so if scan detect file of 'frequently_changing_file_types=pst,ost,sqlite,mbox,dbox,mdbox,log,vmdk,qcow2,vdi,sav'
or directory name from list:
'frequently_changing_dirs=var,log,mysql,mail,Maildir,spool,mongodb,postgresql'
then phase1 and phase2 would loop emediatelly over these files and dirs, e.g. on match, phase1 complete, starting phase2, and return back to phase1 on transfer complete.

**Comment by grke** [comment]
Hello,
Thanks for your suggestions, but your ideas to about the backup process are massive changes. And they won't work, because you would need to do multiple VSS snapshots for a single backup.

**Comment by pagalba-com** [comment]
Does it apply to Macos? VSS looks more like Windows thing. I see problem, that files change/vanish during the backup, which clearly shows that backup is not done on snapshot of FS, but on bare file reading.
At least there should be recovery mechanizm, that if file not found, just skip it, or if file changed, reread it.

**Comment by grke** [comment]
> Does it apply to Macos? VSS looks more like Windows thing. I see problem, that files change/vanish during the backup, which clearly shows that backup is not done on snapshot of FS, but on bare file reading. At least there should be recovery mechanism, that if file not found, just skip it, or if file changed, reread it.

Yes, burp should just skip the file if it is missing, or read it if it is there. Burp should already do this.

And burp is cross-platform, so any change of the backup process has to be appropriate in a cross-platform manner. Changing the backup process in such a way that it will only work on one platform isn't appropriate.

**Comment by grke** [comment]
> I seems that I discovered some important point, it may help others who are experiencing some unpredictable backup failures. I moved burp recently to container service, and made 4GB RAM limit. Also configuration allows 5 children to run. So I was able to capture the moment, when 3 clients made a backup, one existed, and rest two where continuing, but suddenly memory usage spike came, from around 2-3GB RAM usage it topped to max 4GB and second later backup failed, and I got two failed backup email notifications at once. Vuala! I checked server logs and found: burp[707] Backup failed: .... burp[692] Backup failed: .... burp[8] pipe from child 8: end of data burp[707] exit child burp[8] pipe from child 8: disconnected fd 8 burp[8] pipe from child 7: end of data burp[692] exit child burp[8] pipe from child 7: disconnected fd 7
> 
> These logs absolutely tell nothing about reason of child exit, but now I know that this is situation of OOM.
> 
> After RAM limit increase, now failing client is running more than an hour, memory usage grows from 600MB till 4GB+ already, and growing. This means the problems will arise on systems with not sufficient amount of RAM, so system with 8 GB RAM can serve 2 larger clients at most.
> 
> It is quite a hypothetical question, if it is memory leak? And if not, if it is possible to implement total memory limitation from config file or even better limit to 80% of available RAM?
> 
> Note: protocol 2.

Protocol 2 uses a lot more memory than protocol 1 due to needing to load blocks into memory.
Here are some protocol 2 config options related to memory:

{code}
       rblk_memory_max=[B/KB/MB/GB]
              The maximum amount of data from the disk cached in server memory
              during a protocol2 restore/verify. The default  is  256MB.  This
              option  can be overridden per-client in the client configuration
              files in clientconfdir on the server.

       sparse_size_max=[B/KB/MB/GB]
              The maximum (uncompressed) size of the sparse file of each  pro‐
              tocol  2  dedup_group.  The default is 256MB. If the sparse file
              grows beyond this size, entries will be  removed  starting  with
              the oldest, unless it is the only one left for a client.
{code}

Yes, it is possible that there is a memory leak during some operation.
But it is also possible that there is no memory leak, and it just needs that much memory during that operation.
When a client finishes phase2, the server side needs to do more operations in order to finalise the backup. It sounds like the spike happens at this point.

**Comment by grke** [comment]
Sorry, I am discontinuing work on the protocol 2, which has never been production ready, and it is removed in the latest release of burp.
