### ISSUE TITLE
burp fails cert validation w/ OpenSSL 3.0

### ISSUE THREAD

**Issue by nitro322** [grke/burp#916]
I'm having trouble getting a burp client compiled against OpenSSL 3.0 to communicate with a burp server.  Specifically, I get:

```
# burp -a l
2023-07-09 21:30:50 -0500: burp[3148] Connecting to server:4971
2023-07-09 21:30:50 -0500: burp[3148] auth ok
2023-07-09 21:30:50 -0500: burp[3148] Server version: 3.1.4
2023-07-09 21:30:50 -0500: burp[3148] nocsr ok
2023-07-09 21:30:50 -0500: burp[3148] SSL is using cipher: TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD

2023-07-09 21:30:50 -0500: burp[3148] Certificate doesn't verify (68).
2023-07-09 21:30:50 -0500: burp[3148] check cert failed
```

The server log doesn't give me much useful, basically stating to check the client log, but happy to share if it'd be helpful.

This is a client/server setup that I've had working for maybe a year now.  The problems began after a recent upgrade to OpenSSL 3.0.  Here are the details:

client:
OS: gentoo amd64
burp: 3.1.4
openssl: 3.0.9

server:
OS: gentoo amd64
burp: 3.1.4
openssl: 1.1.1u

I have several other clients on my LAN still connecting successfully; only this one client that I upgraded recently is failing.  If I downgrade OpenSSL to 1.1.1u and rebuild burp, it begins working again.

I'm using the burp CA to generate and sign the certs, so nothing unusual there.  However, my burp server was originally built/configured in 2014 and is still using the same cert generated at that time.  My best guess is OpenSSL 3.0 doesn't like something about that old cert, but can't get enough debug info to figure out what.

Any recommendation here?  Cert re-generation would be my next guess, but I have about 10 other clients backing up and not crazy about breaking and having to go regenerate new client certs for all of them.

**Comment by grke** [comment]
Hello,

Code 68 looks to be this, from openssl's x509_vfy.h:
{code}
# define         X509_V_ERR_CA_MD_TOO_WEAK                       68
{code}

Yes, I think you are right, it is about openssl 3 not liking the old CA and certs.
This is the openssl maintainer's way of strengthening algorithms that were once good enough, but are now seen as too weak.
I don't think you have much choice other than to regenerate the CA and the certs.

**Comment by nitro322** [comment]
That's unfortunate, but understood.  Had a chance to work on this more tonight, but replacing the CA seems to have created a different problem.  New CA and server cert definitely created and in use:

```
# openssl s_client -connect server:4971 </dev/null 2>/dev/null | openssl x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = burpCA
        Validity
            Not Before: Jul 15 01:11:39 2023 GMT
            Not After : Jul 10 01:11:39 2043 GMT
        Subject: CN = server
<SNIP>
```

I deleted ssl_cert*  and CA-client/client.csr from my client, then ran burp -a l, which automatically created a new client cert.  When trying to connect now, though, I get this:

```
# burp -a l
2023-07-14 20:45:21 -0500: burp[25304] Connecting to server:4971
2023-07-14 20:45:21 -0500: burp[25304] main socket 4: network read problem in asfd_do_read_ssl: 1 - 0=Success
40F718AC4B7F0000:error:0A00041B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:../openssl-3.0.9/ssl/record/rec_layer_s3.c:1586:SSL alert number 51
2023-07-14 20:45:21 -0500: burp[25304] This is probably caused by the peer exiting.
2023-07-14 20:45:21 -0500: burp[25304] Please check the peer's logs.
2023-07-14 20:45:21 -0500: burp[25304] problem with auth
```

The server log, unfortunately, doesn't tell me anything more helpful:

```
Jul 14 20:46:02 server burp[13484]: Connect from peer: 192.168.0.3:41266
Jul 14 20:46:02 server burp[13484]: 0/5 child processes running on listen 0.0.0.0:4971
Jul 14 20:46:02 server burp[13484]: Child 1 available
Jul 14 20:46:02 server burp[13484]: forked child on 0.0.0.0:4971: 4675
Jul 14 20:46:02 server burp[4675]: SSL_accept error: 1
Jul 14 20:46:02 server burp[4675]: exit child
Jul 14 20:46:02 server burp[13484]: pipe from child 7: end of data
Jul 14 20:46:02 server burp[13484]: pipe from child 7: disconnected fd 7
```

Sorry to bug you about this, but any ideas here?

**Comment by nitro322** [comment]
just realized I could close the issue myself

**Comment by grke** [comment]
Thanks for the update!
