### ISSUE TITLE
About 3.1.4 release

### ISSUE THREAD

**Issue by chenrui333** [grke/burp#920]
👋 Curious if 3.1.4 release is the latest stable release, if so, the website might need to update the information regarding it. Thanks!

![image](https://github.com/grke/burp/assets/1580956/07af73cd-0726-4ba6-8b98-fd2f74d1e0b2)

relates to Homebrew/homebrew-core#138580

**Comment by jumbo-grke** [comment]
No, the latest release is not the same as the stable release.

**Comment by chenrui333** [comment]
Thanks @grke @jumbo-grke!
