### ISSUE TITLE
Question : why speed is slow on first backup ?

### ISSUE THREAD

**Issue by Kalimeiro** [grke/burp#925]
Hi,

I'm going to test latest build of burp 3.1.x to see whats change.

My computer have a I9-13900K and 990 Pro NVME, and of course lot of memory, connected to a switch with RJ45 cable running at 2.5 Gbps.
My server is a R9-5950X with lot of ECC memory and 8 x sata SSD with ZFS RAIDZ-2, connected to the same switch than my pc but with SFP+, speed is 10Gbps.

When i start the first backup, bandwith used is around 30Mbps, time to time he grow at 300Mbps but impossible to have better transfert speed, result : ~4 hours for ~230GB of data.

Someone can explain why burp is slow ?

**Comment by grke** [comment]
Hello,
I'm glad you found a way.
