### ISSUE TITLE
Summary e-Mail is always blank

### ISSUE THREAD

**Issue by fuzzyeric** [grke/burp#928]
The "Daily backup summary" is always blank, even on days where files are backed up.  A full set of headers appears.  Example:

> From root@[tera003 server FQDN]  Mon May  6 06:00:02 2024
> X-Original-To: fuzzy
> To: fuzzy@[tera003 server FQDN]
> From: burp@[tera003 server FQDN]
> Subject: Daily backup summary
> Content-Type: text/plain; charset=utf-8
> Date: Mon,  6 May 2024 06:00:01 +0000 (UTC)
> 

There is one burp client, a Windows laptop.

Maybe relevant log entries:
> May 11 18:24:26 tera003 burp[83270]: could not open '/etc/burp/clientconfdir/tera003' for reading.
> May 11 18:24:27 tera003 burp[83270]: unable to authorise on server
> May 11 18:24:27 tera003 burp[83270]: exit child

The clientconfdir/tera003 item once existed during testing before deployment.  I don't know where remains a reference to tera003 as a client.  The clientconfdir is

.
├── disabled
│   └── testclient
├── incexc
│   ├── example
│   └── windows10
└── theWindowsClient

Running on
* Ubuntu Server 22.04.3 LTS  (upgrade to 24.04 scheduled two weeks out)
* burp 2.4.0-3ubuntu1 amd64 (upgrades to 3.1.4-3.1build3 in two weeks)

Any hints for getting non-blank summaries?

**Comment by grke** [comment]
On Sat, May 11, 2024 at 12:43:43PM -0700, Eric Towers wrote:
>    The "Daily backup summary" is always blank, even on days where files are
>    backed up. A full set of headers appears. Example:
> 
>      From ***@***.*** server FQDN] Mon May 6 06:00:02 2024
>      X-Original-To: fuzzy
>      To: ***@***.*** server FQDN]
>      From: ***@***.*** server FQDN]
>      Subject: Daily backup summary
>      Content-Type: text/plain; charset=utf-8
>      Date: Mon, 6 May 2024 06:00:01 +0000 (UTC)
> 
>    There is one burp client, a Windows laptop.
> 
>    Maybe relevant log entries:
> 
>      May 11 18:24:26 tera003 burp[83270]: could not open
>      '/etc/burp/clientconfdir/tera003' for reading.
>      May 11 18:24:27 tera003 burp[83270]: unable to authorise on server
>      May 11 18:24:27 tera003 burp[83270]: exit child
> 
>    The clientconfdir/tera003 item once existed during testing before
>    deployment. I don't know where remains a reference to tera003 as a client.
>    The clientconfdir is
> 
>    .
>    ├── disabled
>    │   └── testclient
>    ├── incexc
>    │   ├── example
>    │   └── windows10
>    └── theWindowsClient
> 
>    Running on
> 
>      * Ubuntu Server 22.04.3 LTS (upgrade to 24.04 scheduled two weeks out)
>      * burp 2.4.0-3ubuntu1 amd64 (upgrades to 3.1.4-3.1build3 in two weeks)
> 
>    Any hints for getting non-blank summaries?

Hello,

It looks like the client side is configured to use 'tera003' as the client
name.

**Comment by fuzzyeric** [comment]
Well, the backed up
   [burp server target
directory]/theWindowsClient/current/data/t/c:/Program Files/Burp/burp.conf
is encrypted(?)/compressed(?) and I find no way to restore the file at the
server so I can neither confirm nor deny the claim.  Since files are
backing up to the theWindowsClient client's target directory it would
*appear* that the client and server agree that they should be using the
theWindowsClient as the client name.

**Comment by grke** [comment]
Do you not have access to the laptop itself?

Going on what you have written so far, it looks like there are at least two clients trying to access the server:

1) tera003
2) theWindowsClient

Can you give more information on how you have set up the "Daily backup summary" to run?
Most likely there are these components:
1) a line in a cron job that calls something like "summary_script" with some arguments
2) "summary_script" itself

If you are using "summary script" from the burp source, it pipes the email into sendmail.
The body is the output of:
/sbin/burp -c <config file> -a S
Where <config file> is the first argument that the cron job gives it, which is most likely /etc/burp/burp.conf.

Most likely, this command is not working for some reason and you need to debug it.
It uses the server status monitor, using the server-side /etc/burp/burp.conf as a client.
You might find that 'tera003' is what you have in the server-side /etc/burp/burp.conf, which would explain the unexplained client mentioned above.
